---
{{- $token := (lookup "v1" "Secret" "d8-monitoring" "prometheus-token").data.token | b64dec -}}
apiVersion: deckhouse.io/v1
kind: GrafanaAdditionalDatasource
metadata:
  name: prom-3
spec:
  access: Proxy
  jsonData:
    httpHeaderName1: Authorization
    tlsSkipVerify: true
    timeInterval: 30s
  secureJsonData:
    httpHeaderValue1: bearer {{ $token }} 
  type: prometheus
  url: https://prom-3.d8-monitoring.svc.cluster.local:9090
