name: Custom setup werf + crane

description: Setup werf, crane and login into registry

inputs:
  registry:
    required: true
  registry_login:
    required: true
  registry_password:
    required: true
  channel:
    description: 'The one of the following channel: alpha, beta, ea, stable, rock-solid'
    default: 'stable'
    required: false

runs:
  using: "composite"
  steps:
    - uses: werf/actions/install@v2
      with:
        channel: ${{ inputs.channel }}

    - name: Print werf version
      shell: bash
      run: werf version

    - name: Login into registry ${{ inputs.registry }}
      shell: bash
      run: werf cr login -u ${{ inputs.registry_login }} -p ${{ inputs.registry_password }} ${{ inputs.registry }}
