// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package processor_test

import (
	"context"
	pp_pkg_model "github.com/prometheus/prometheus/pp-pkg/model"
	"github.com/prometheus/prometheus/pp/go/cppbridge"
	"sync"
)

// AdapterMock is a mock implementation of processor.Adapter.
//
//	func TestSomethingThatUsesAdapter(t *testing.T) {
//
//		// make and configure a mocked processor.Adapter
//		mockedAdapter := &AdapterMock{
//			AppendHashdexFunc: func(ctx context.Context, hashdex cppbridge.ShardedData, state *cppbridge.StateV2, commitToWal bool) (cppbridge.RelabelerStats, error) {
//				panic("mock out the AppendHashdex method")
//			},
//			AppendSnappyProtobufFunc: func(ctx context.Context, compressedData pp_pkg_model.ProtobufData, state *cppbridge.StateV2, commitToWal bool) error {
//				panic("mock out the AppendSnappyProtobuf method")
//			},
//			AppendTimeSeriesFunc: func(ctx context.Context, data pp_pkg_model.TimeSeriesBatch, state *cppbridge.StateV2, commitToWal bool) (cppbridge.RelabelerStats, error) {
//				panic("mock out the AppendTimeSeries method")
//			},
//			MergeOutOfOrderChunksFunc: func()  {
//				panic("mock out the MergeOutOfOrderChunks method")
//			},
//		}
//
//		// use mockedAdapter in code that requires processor.Adapter
//		// and then make assertions.
//
//	}
type AdapterMock struct {
	// AppendHashdexFunc mocks the AppendHashdex method.
	AppendHashdexFunc func(ctx context.Context, hashdex cppbridge.ShardedData, state *cppbridge.StateV2, commitToWal bool) (cppbridge.RelabelerStats, error)

	// AppendSnappyProtobufFunc mocks the AppendSnappyProtobuf method.
	AppendSnappyProtobufFunc func(ctx context.Context, compressedData pp_pkg_model.ProtobufData, state *cppbridge.StateV2, commitToWal bool) error

	// AppendTimeSeriesFunc mocks the AppendTimeSeries method.
	AppendTimeSeriesFunc func(ctx context.Context, data pp_pkg_model.TimeSeriesBatch, state *cppbridge.StateV2, commitToWal bool) (cppbridge.RelabelerStats, error)

	// MergeOutOfOrderChunksFunc mocks the MergeOutOfOrderChunks method.
	MergeOutOfOrderChunksFunc func()

	// calls tracks calls to the methods.
	calls struct {
		// AppendHashdex holds details about calls to the AppendHashdex method.
		AppendHashdex []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Hashdex is the hashdex argument value.
			Hashdex cppbridge.ShardedData
			// State is the state argument value.
			State *cppbridge.StateV2
			// CommitToWal is the commitToWal argument value.
			CommitToWal bool
		}
		// AppendSnappyProtobuf holds details about calls to the AppendSnappyProtobuf method.
		AppendSnappyProtobuf []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// CompressedData is the compressedData argument value.
			CompressedData pp_pkg_model.ProtobufData
			// State is the state argument value.
			State *cppbridge.StateV2
			// CommitToWal is the commitToWal argument value.
			CommitToWal bool
		}
		// AppendTimeSeries holds details about calls to the AppendTimeSeries method.
		AppendTimeSeries []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Data is the data argument value.
			Data pp_pkg_model.TimeSeriesBatch
			// State is the state argument value.
			State *cppbridge.StateV2
			// CommitToWal is the commitToWal argument value.
			CommitToWal bool
		}
		// MergeOutOfOrderChunks holds details about calls to the MergeOutOfOrderChunks method.
		MergeOutOfOrderChunks []struct {
		}
	}
	lockAppendHashdex         sync.RWMutex
	lockAppendSnappyProtobuf  sync.RWMutex
	lockAppendTimeSeries      sync.RWMutex
	lockMergeOutOfOrderChunks sync.RWMutex
}

// AppendHashdex calls AppendHashdexFunc.
func (mock *AdapterMock) AppendHashdex(ctx context.Context, hashdex cppbridge.ShardedData, state *cppbridge.StateV2, commitToWal bool) (cppbridge.RelabelerStats, error) {
	if mock.AppendHashdexFunc == nil {
		panic("AdapterMock.AppendHashdexFunc: method is nil but Adapter.AppendHashdex was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Hashdex     cppbridge.ShardedData
		State       *cppbridge.StateV2
		CommitToWal bool
	}{
		Ctx:         ctx,
		Hashdex:     hashdex,
		State:       state,
		CommitToWal: commitToWal,
	}
	mock.lockAppendHashdex.Lock()
	mock.calls.AppendHashdex = append(mock.calls.AppendHashdex, callInfo)
	mock.lockAppendHashdex.Unlock()
	return mock.AppendHashdexFunc(ctx, hashdex, state, commitToWal)
}

// AppendHashdexCalls gets all the calls that were made to AppendHashdex.
// Check the length with:
//
//	len(mockedAdapter.AppendHashdexCalls())
func (mock *AdapterMock) AppendHashdexCalls() []struct {
	Ctx         context.Context
	Hashdex     cppbridge.ShardedData
	State       *cppbridge.StateV2
	CommitToWal bool
} {
	var calls []struct {
		Ctx         context.Context
		Hashdex     cppbridge.ShardedData
		State       *cppbridge.StateV2
		CommitToWal bool
	}
	mock.lockAppendHashdex.RLock()
	calls = mock.calls.AppendHashdex
	mock.lockAppendHashdex.RUnlock()
	return calls
}

// AppendSnappyProtobuf calls AppendSnappyProtobufFunc.
func (mock *AdapterMock) AppendSnappyProtobuf(ctx context.Context, compressedData pp_pkg_model.ProtobufData, state *cppbridge.StateV2, commitToWal bool) error {
	if mock.AppendSnappyProtobufFunc == nil {
		panic("AdapterMock.AppendSnappyProtobufFunc: method is nil but Adapter.AppendSnappyProtobuf was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		CompressedData pp_pkg_model.ProtobufData
		State          *cppbridge.StateV2
		CommitToWal    bool
	}{
		Ctx:            ctx,
		CompressedData: compressedData,
		State:          state,
		CommitToWal:    commitToWal,
	}
	mock.lockAppendSnappyProtobuf.Lock()
	mock.calls.AppendSnappyProtobuf = append(mock.calls.AppendSnappyProtobuf, callInfo)
	mock.lockAppendSnappyProtobuf.Unlock()
	return mock.AppendSnappyProtobufFunc(ctx, compressedData, state, commitToWal)
}

// AppendSnappyProtobufCalls gets all the calls that were made to AppendSnappyProtobuf.
// Check the length with:
//
//	len(mockedAdapter.AppendSnappyProtobufCalls())
func (mock *AdapterMock) AppendSnappyProtobufCalls() []struct {
	Ctx            context.Context
	CompressedData pp_pkg_model.ProtobufData
	State          *cppbridge.StateV2
	CommitToWal    bool
} {
	var calls []struct {
		Ctx            context.Context
		CompressedData pp_pkg_model.ProtobufData
		State          *cppbridge.StateV2
		CommitToWal    bool
	}
	mock.lockAppendSnappyProtobuf.RLock()
	calls = mock.calls.AppendSnappyProtobuf
	mock.lockAppendSnappyProtobuf.RUnlock()
	return calls
}

// AppendTimeSeries calls AppendTimeSeriesFunc.
func (mock *AdapterMock) AppendTimeSeries(ctx context.Context, data pp_pkg_model.TimeSeriesBatch, state *cppbridge.StateV2, commitToWal bool) (cppbridge.RelabelerStats, error) {
	if mock.AppendTimeSeriesFunc == nil {
		panic("AdapterMock.AppendTimeSeriesFunc: method is nil but Adapter.AppendTimeSeries was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Data        pp_pkg_model.TimeSeriesBatch
		State       *cppbridge.StateV2
		CommitToWal bool
	}{
		Ctx:         ctx,
		Data:        data,
		State:       state,
		CommitToWal: commitToWal,
	}
	mock.lockAppendTimeSeries.Lock()
	mock.calls.AppendTimeSeries = append(mock.calls.AppendTimeSeries, callInfo)
	mock.lockAppendTimeSeries.Unlock()
	return mock.AppendTimeSeriesFunc(ctx, data, state, commitToWal)
}

// AppendTimeSeriesCalls gets all the calls that were made to AppendTimeSeries.
// Check the length with:
//
//	len(mockedAdapter.AppendTimeSeriesCalls())
func (mock *AdapterMock) AppendTimeSeriesCalls() []struct {
	Ctx         context.Context
	Data        pp_pkg_model.TimeSeriesBatch
	State       *cppbridge.StateV2
	CommitToWal bool
} {
	var calls []struct {
		Ctx         context.Context
		Data        pp_pkg_model.TimeSeriesBatch
		State       *cppbridge.StateV2
		CommitToWal bool
	}
	mock.lockAppendTimeSeries.RLock()
	calls = mock.calls.AppendTimeSeries
	mock.lockAppendTimeSeries.RUnlock()
	return calls
}

// MergeOutOfOrderChunks calls MergeOutOfOrderChunksFunc.
func (mock *AdapterMock) MergeOutOfOrderChunks() {
	if mock.MergeOutOfOrderChunksFunc == nil {
		panic("AdapterMock.MergeOutOfOrderChunksFunc: method is nil but Adapter.MergeOutOfOrderChunks was just called")
	}
	callInfo := struct {
	}{}
	mock.lockMergeOutOfOrderChunks.Lock()
	mock.calls.MergeOutOfOrderChunks = append(mock.calls.MergeOutOfOrderChunks, callInfo)
	mock.lockMergeOutOfOrderChunks.Unlock()
	mock.MergeOutOfOrderChunksFunc()
}

// MergeOutOfOrderChunksCalls gets all the calls that were made to MergeOutOfOrderChunks.
// Check the length with:
//
//	len(mockedAdapter.MergeOutOfOrderChunksCalls())
func (mock *AdapterMock) MergeOutOfOrderChunksCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockMergeOutOfOrderChunks.RLock()
	calls = mock.calls.MergeOutOfOrderChunks
	mock.lockMergeOutOfOrderChunks.RUnlock()
	return calls
}
