// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package processor_test

import (
	"context"
	"github.com/prometheus/prometheus/pp-pkg/handler/model"
	"github.com/prometheus/prometheus/pp-pkg/handler/processor"
	pp_pkg_model "github.com/prometheus/prometheus/pp-pkg/model"
	"github.com/prometheus/prometheus/pp/go/cppbridge"
	"sync"
)

// Ensure, that AdapterMock does implement processor.Adapter.
// If this is not the case, regenerate this file with moq.
var _ processor.Adapter = &AdapterMock{}

// AdapterMock is a mock implementation of processor.Adapter.
//
//	func TestSomethingThatUsesAdapter(t *testing.T) {
//
//		// make and configure a mocked processor.Adapter
//		mockedAdapter := &AdapterMock{
//			AppendHashdexFunc: func(ctx context.Context, hashdex cppbridge.ShardedData, state *cppbridge.StateV2, commitToWal bool) error {
//				panic("mock out the AppendHashdex method")
//			},
//			AppendScraperHashdexFunc: func(ctx context.Context, hashdex cppbridge.ShardedData, state *cppbridge.StateV2, commitToWal bool) (cppbridge.RelabelerStats, error) {
//				panic("mock out the AppendScraperHashdex method")
//			},
//			AppendSnappyProtobufFunc: func(ctx context.Context, compressedData pp_pkg_model.ProtobufData, state *cppbridge.StateV2, commitToWal bool) error {
//				panic("mock out the AppendSnappyProtobuf method")
//			},
//			AppendTimeSeriesFunc: func(ctx context.Context, data pp_pkg_model.TimeSeriesBatch, state *cppbridge.StateV2, commitToWal bool) (cppbridge.RelabelerStats, error) {
//				panic("mock out the AppendTimeSeries method")
//			},
//			MergeOutOfOrderChunksFunc: func(ctx context.Context)  {
//				panic("mock out the MergeOutOfOrderChunks method")
//			},
//		}
//
//		// use mockedAdapter in code that requires processor.Adapter
//		// and then make assertions.
//
//	}
type AdapterMock struct {
	// AppendHashdexFunc mocks the AppendHashdex method.
	AppendHashdexFunc func(ctx context.Context, hashdex cppbridge.ShardedData, state *cppbridge.StateV2, commitToWal bool) error

	// AppendScraperHashdexFunc mocks the AppendScraperHashdex method.
	AppendScraperHashdexFunc func(ctx context.Context, hashdex cppbridge.ShardedData, state *cppbridge.StateV2, commitToWal bool) (cppbridge.RelabelerStats, error)

	// AppendSnappyProtobufFunc mocks the AppendSnappyProtobuf method.
	AppendSnappyProtobufFunc func(ctx context.Context, compressedData pp_pkg_model.ProtobufData, state *cppbridge.StateV2, commitToWal bool) error

	// AppendTimeSeriesFunc mocks the AppendTimeSeries method.
	AppendTimeSeriesFunc func(ctx context.Context, data pp_pkg_model.TimeSeriesBatch, state *cppbridge.StateV2, commitToWal bool) (cppbridge.RelabelerStats, error)

	// MergeOutOfOrderChunksFunc mocks the MergeOutOfOrderChunks method.
	MergeOutOfOrderChunksFunc func(ctx context.Context)

	// calls tracks calls to the methods.
	calls struct {
		// AppendHashdex holds details about calls to the AppendHashdex method.
		AppendHashdex []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Hashdex is the hashdex argument value.
			Hashdex cppbridge.ShardedData
			// State is the state argument value.
			State *cppbridge.StateV2
			// CommitToWal is the commitToWal argument value.
			CommitToWal bool
		}
		// AppendScraperHashdex holds details about calls to the AppendScraperHashdex method.
		AppendScraperHashdex []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Hashdex is the hashdex argument value.
			Hashdex cppbridge.ShardedData
			// State is the state argument value.
			State *cppbridge.StateV2
			// CommitToWal is the commitToWal argument value.
			CommitToWal bool
		}
		// AppendSnappyProtobuf holds details about calls to the AppendSnappyProtobuf method.
		AppendSnappyProtobuf []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// CompressedData is the compressedData argument value.
			CompressedData pp_pkg_model.ProtobufData
			// State is the state argument value.
			State *cppbridge.StateV2
			// CommitToWal is the commitToWal argument value.
			CommitToWal bool
		}
		// AppendTimeSeries holds details about calls to the AppendTimeSeries method.
		AppendTimeSeries []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Data is the data argument value.
			Data pp_pkg_model.TimeSeriesBatch
			// State is the state argument value.
			State *cppbridge.StateV2
			// CommitToWal is the commitToWal argument value.
			CommitToWal bool
		}
		// MergeOutOfOrderChunks holds details about calls to the MergeOutOfOrderChunks method.
		MergeOutOfOrderChunks []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockAppendHashdex         sync.RWMutex
	lockAppendScraperHashdex  sync.RWMutex
	lockAppendSnappyProtobuf  sync.RWMutex
	lockAppendTimeSeries      sync.RWMutex
	lockMergeOutOfOrderChunks sync.RWMutex
}

// AppendHashdex calls AppendHashdexFunc.
func (mock *AdapterMock) AppendHashdex(ctx context.Context, hashdex cppbridge.ShardedData, state *cppbridge.StateV2, commitToWal bool) error {
	if mock.AppendHashdexFunc == nil {
		panic("AdapterMock.AppendHashdexFunc: method is nil but Adapter.AppendHashdex was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Hashdex     cppbridge.ShardedData
		State       *cppbridge.StateV2
		CommitToWal bool
	}{
		Ctx:         ctx,
		Hashdex:     hashdex,
		State:       state,
		CommitToWal: commitToWal,
	}
	mock.lockAppendHashdex.Lock()
	mock.calls.AppendHashdex = append(mock.calls.AppendHashdex, callInfo)
	mock.lockAppendHashdex.Unlock()
	return mock.AppendHashdexFunc(ctx, hashdex, state, commitToWal)
}

// AppendHashdexCalls gets all the calls that were made to AppendHashdex.
// Check the length with:
//
//	len(mockedAdapter.AppendHashdexCalls())
func (mock *AdapterMock) AppendHashdexCalls() []struct {
	Ctx         context.Context
	Hashdex     cppbridge.ShardedData
	State       *cppbridge.StateV2
	CommitToWal bool
} {
	var calls []struct {
		Ctx         context.Context
		Hashdex     cppbridge.ShardedData
		State       *cppbridge.StateV2
		CommitToWal bool
	}
	mock.lockAppendHashdex.RLock()
	calls = mock.calls.AppendHashdex
	mock.lockAppendHashdex.RUnlock()
	return calls
}

// AppendScraperHashdex calls AppendScraperHashdexFunc.
func (mock *AdapterMock) AppendScraperHashdex(ctx context.Context, hashdex cppbridge.ShardedData, state *cppbridge.StateV2, commitToWal bool) (cppbridge.RelabelerStats, error) {
	if mock.AppendScraperHashdexFunc == nil {
		panic("AdapterMock.AppendScraperHashdexFunc: method is nil but Adapter.AppendScraperHashdex was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Hashdex     cppbridge.ShardedData
		State       *cppbridge.StateV2
		CommitToWal bool
	}{
		Ctx:         ctx,
		Hashdex:     hashdex,
		State:       state,
		CommitToWal: commitToWal,
	}
	mock.lockAppendScraperHashdex.Lock()
	mock.calls.AppendScraperHashdex = append(mock.calls.AppendScraperHashdex, callInfo)
	mock.lockAppendScraperHashdex.Unlock()
	return mock.AppendScraperHashdexFunc(ctx, hashdex, state, commitToWal)
}

// AppendScraperHashdexCalls gets all the calls that were made to AppendScraperHashdex.
// Check the length with:
//
//	len(mockedAdapter.AppendScraperHashdexCalls())
func (mock *AdapterMock) AppendScraperHashdexCalls() []struct {
	Ctx         context.Context
	Hashdex     cppbridge.ShardedData
	State       *cppbridge.StateV2
	CommitToWal bool
} {
	var calls []struct {
		Ctx         context.Context
		Hashdex     cppbridge.ShardedData
		State       *cppbridge.StateV2
		CommitToWal bool
	}
	mock.lockAppendScraperHashdex.RLock()
	calls = mock.calls.AppendScraperHashdex
	mock.lockAppendScraperHashdex.RUnlock()
	return calls
}

// AppendSnappyProtobuf calls AppendSnappyProtobufFunc.
func (mock *AdapterMock) AppendSnappyProtobuf(ctx context.Context, compressedData pp_pkg_model.ProtobufData, state *cppbridge.StateV2, commitToWal bool) error {
	if mock.AppendSnappyProtobufFunc == nil {
		panic("AdapterMock.AppendSnappyProtobufFunc: method is nil but Adapter.AppendSnappyProtobuf was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		CompressedData pp_pkg_model.ProtobufData
		State          *cppbridge.StateV2
		CommitToWal    bool
	}{
		Ctx:            ctx,
		CompressedData: compressedData,
		State:          state,
		CommitToWal:    commitToWal,
	}
	mock.lockAppendSnappyProtobuf.Lock()
	mock.calls.AppendSnappyProtobuf = append(mock.calls.AppendSnappyProtobuf, callInfo)
	mock.lockAppendSnappyProtobuf.Unlock()
	return mock.AppendSnappyProtobufFunc(ctx, compressedData, state, commitToWal)
}

// AppendSnappyProtobufCalls gets all the calls that were made to AppendSnappyProtobuf.
// Check the length with:
//
//	len(mockedAdapter.AppendSnappyProtobufCalls())
func (mock *AdapterMock) AppendSnappyProtobufCalls() []struct {
	Ctx            context.Context
	CompressedData pp_pkg_model.ProtobufData
	State          *cppbridge.StateV2
	CommitToWal    bool
} {
	var calls []struct {
		Ctx            context.Context
		CompressedData pp_pkg_model.ProtobufData
		State          *cppbridge.StateV2
		CommitToWal    bool
	}
	mock.lockAppendSnappyProtobuf.RLock()
	calls = mock.calls.AppendSnappyProtobuf
	mock.lockAppendSnappyProtobuf.RUnlock()
	return calls
}

// AppendTimeSeries calls AppendTimeSeriesFunc.
func (mock *AdapterMock) AppendTimeSeries(ctx context.Context, data pp_pkg_model.TimeSeriesBatch, state *cppbridge.StateV2, commitToWal bool) (cppbridge.RelabelerStats, error) {
	if mock.AppendTimeSeriesFunc == nil {
		panic("AdapterMock.AppendTimeSeriesFunc: method is nil but Adapter.AppendTimeSeries was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Data        pp_pkg_model.TimeSeriesBatch
		State       *cppbridge.StateV2
		CommitToWal bool
	}{
		Ctx:         ctx,
		Data:        data,
		State:       state,
		CommitToWal: commitToWal,
	}
	mock.lockAppendTimeSeries.Lock()
	mock.calls.AppendTimeSeries = append(mock.calls.AppendTimeSeries, callInfo)
	mock.lockAppendTimeSeries.Unlock()
	return mock.AppendTimeSeriesFunc(ctx, data, state, commitToWal)
}

// AppendTimeSeriesCalls gets all the calls that were made to AppendTimeSeries.
// Check the length with:
//
//	len(mockedAdapter.AppendTimeSeriesCalls())
func (mock *AdapterMock) AppendTimeSeriesCalls() []struct {
	Ctx         context.Context
	Data        pp_pkg_model.TimeSeriesBatch
	State       *cppbridge.StateV2
	CommitToWal bool
} {
	var calls []struct {
		Ctx         context.Context
		Data        pp_pkg_model.TimeSeriesBatch
		State       *cppbridge.StateV2
		CommitToWal bool
	}
	mock.lockAppendTimeSeries.RLock()
	calls = mock.calls.AppendTimeSeries
	mock.lockAppendTimeSeries.RUnlock()
	return calls
}

// MergeOutOfOrderChunks calls MergeOutOfOrderChunksFunc.
func (mock *AdapterMock) MergeOutOfOrderChunks(ctx context.Context) {
	if mock.MergeOutOfOrderChunksFunc == nil {
		panic("AdapterMock.MergeOutOfOrderChunksFunc: method is nil but Adapter.MergeOutOfOrderChunks was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockMergeOutOfOrderChunks.Lock()
	mock.calls.MergeOutOfOrderChunks = append(mock.calls.MergeOutOfOrderChunks, callInfo)
	mock.lockMergeOutOfOrderChunks.Unlock()
	mock.MergeOutOfOrderChunksFunc(ctx)
}

// MergeOutOfOrderChunksCalls gets all the calls that were made to MergeOutOfOrderChunks.
// Check the length with:
//
//	len(mockedAdapter.MergeOutOfOrderChunksCalls())
func (mock *AdapterMock) MergeOutOfOrderChunksCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockMergeOutOfOrderChunks.RLock()
	calls = mock.calls.MergeOutOfOrderChunks
	mock.lockMergeOutOfOrderChunks.RUnlock()
	return calls
}

// Ensure, that StatesStorageMock does implement processor.StatesStorage.
// If this is not the case, regenerate this file with moq.
var _ processor.StatesStorage = &StatesStorageMock{}

// StatesStorageMock is a mock implementation of processor.StatesStorage.
//
//	func TestSomethingThatUsesStatesStorage(t *testing.T) {
//
//		// make and configure a mocked processor.StatesStorage
//		mockedStatesStorage := &StatesStorageMock{
//			GetStateByIDFunc: func(stateID string) (*cppbridge.StateV2, bool) {
//				panic("mock out the GetStateByID method")
//			},
//		}
//
//		// use mockedStatesStorage in code that requires processor.StatesStorage
//		// and then make assertions.
//
//	}
type StatesStorageMock struct {
	// GetStateByIDFunc mocks the GetStateByID method.
	GetStateByIDFunc func(stateID string) (*cppbridge.StateV2, bool)

	// calls tracks calls to the methods.
	calls struct {
		// GetStateByID holds details about calls to the GetStateByID method.
		GetStateByID []struct {
			// StateID is the stateID argument value.
			StateID string
		}
	}
	lockGetStateByID sync.RWMutex
}

// GetStateByID calls GetStateByIDFunc.
func (mock *StatesStorageMock) GetStateByID(stateID string) (*cppbridge.StateV2, bool) {
	if mock.GetStateByIDFunc == nil {
		panic("StatesStorageMock.GetStateByIDFunc: method is nil but StatesStorage.GetStateByID was just called")
	}
	callInfo := struct {
		StateID string
	}{
		StateID: stateID,
	}
	mock.lockGetStateByID.Lock()
	mock.calls.GetStateByID = append(mock.calls.GetStateByID, callInfo)
	mock.lockGetStateByID.Unlock()
	return mock.GetStateByIDFunc(stateID)
}

// GetStateByIDCalls gets all the calls that were made to GetStateByID.
// Check the length with:
//
//	len(mockedStatesStorage.GetStateByIDCalls())
func (mock *StatesStorageMock) GetStateByIDCalls() []struct {
	StateID string
} {
	var calls []struct {
		StateID string
	}
	mock.lockGetStateByID.RLock()
	calls = mock.calls.GetStateByID
	mock.lockGetStateByID.RUnlock()
	return calls
}

// Ensure, that RemoteWriteMock does implement processor.RemoteWrite.
// If this is not the case, regenerate this file with moq.
var _ processor.RemoteWrite = &RemoteWriteMock{}

// RemoteWriteMock is a mock implementation of processor.RemoteWrite.
//
//	func TestSomethingThatUsesRemoteWrite(t *testing.T) {
//
//		// make and configure a mocked processor.RemoteWrite
//		mockedRemoteWrite := &RemoteWriteMock{
//			MetadataFunc: func() model.Metadata {
//				panic("mock out the Metadata method")
//			},
//			ReadFunc: func(ctx context.Context) (*model.RemoteWriteBuffer, error) {
//				panic("mock out the Read method")
//			},
//			WriteFunc: func(ctx context.Context, status model.RemoteWriteProcessingStatus) error {
//				panic("mock out the Write method")
//			},
//		}
//
//		// use mockedRemoteWrite in code that requires processor.RemoteWrite
//		// and then make assertions.
//
//	}
type RemoteWriteMock struct {
	// MetadataFunc mocks the Metadata method.
	MetadataFunc func() model.Metadata

	// ReadFunc mocks the Read method.
	ReadFunc func(ctx context.Context) (*model.RemoteWriteBuffer, error)

	// WriteFunc mocks the Write method.
	WriteFunc func(ctx context.Context, status model.RemoteWriteProcessingStatus) error

	// calls tracks calls to the methods.
	calls struct {
		// Metadata holds details about calls to the Metadata method.
		Metadata []struct {
		}
		// Read holds details about calls to the Read method.
		Read []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Write holds details about calls to the Write method.
		Write []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Status is the status argument value.
			Status model.RemoteWriteProcessingStatus
		}
	}
	lockMetadata sync.RWMutex
	lockRead     sync.RWMutex
	lockWrite    sync.RWMutex
}

// Metadata calls MetadataFunc.
func (mock *RemoteWriteMock) Metadata() model.Metadata {
	if mock.MetadataFunc == nil {
		panic("RemoteWriteMock.MetadataFunc: method is nil but RemoteWrite.Metadata was just called")
	}
	callInfo := struct {
	}{}
	mock.lockMetadata.Lock()
	mock.calls.Metadata = append(mock.calls.Metadata, callInfo)
	mock.lockMetadata.Unlock()
	return mock.MetadataFunc()
}

// MetadataCalls gets all the calls that were made to Metadata.
// Check the length with:
//
//	len(mockedRemoteWrite.MetadataCalls())
func (mock *RemoteWriteMock) MetadataCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockMetadata.RLock()
	calls = mock.calls.Metadata
	mock.lockMetadata.RUnlock()
	return calls
}

// Read calls ReadFunc.
func (mock *RemoteWriteMock) Read(ctx context.Context) (*model.RemoteWriteBuffer, error) {
	if mock.ReadFunc == nil {
		panic("RemoteWriteMock.ReadFunc: method is nil but RemoteWrite.Read was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockRead.Lock()
	mock.calls.Read = append(mock.calls.Read, callInfo)
	mock.lockRead.Unlock()
	return mock.ReadFunc(ctx)
}

// ReadCalls gets all the calls that were made to Read.
// Check the length with:
//
//	len(mockedRemoteWrite.ReadCalls())
func (mock *RemoteWriteMock) ReadCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockRead.RLock()
	calls = mock.calls.Read
	mock.lockRead.RUnlock()
	return calls
}

// Write calls WriteFunc.
func (mock *RemoteWriteMock) Write(ctx context.Context, status model.RemoteWriteProcessingStatus) error {
	if mock.WriteFunc == nil {
		panic("RemoteWriteMock.WriteFunc: method is nil but RemoteWrite.Write was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Status model.RemoteWriteProcessingStatus
	}{
		Ctx:    ctx,
		Status: status,
	}
	mock.lockWrite.Lock()
	mock.calls.Write = append(mock.calls.Write, callInfo)
	mock.lockWrite.Unlock()
	return mock.WriteFunc(ctx, status)
}

// WriteCalls gets all the calls that were made to Write.
// Check the length with:
//
//	len(mockedRemoteWrite.WriteCalls())
func (mock *RemoteWriteMock) WriteCalls() []struct {
	Ctx    context.Context
	Status model.RemoteWriteProcessingStatus
} {
	var calls []struct {
		Ctx    context.Context
		Status model.RemoteWriteProcessingStatus
	}
	mock.lockWrite.RLock()
	calls = mock.calls.Write
	mock.lockWrite.RUnlock()
	return calls
}

// Ensure, that MetricStreamMock does implement processor.MetricStream.
// If this is not the case, regenerate this file with moq.
var _ processor.MetricStream = &MetricStreamMock{}

// MetricStreamMock is a mock implementation of processor.MetricStream.
//
//	func TestSomethingThatUsesMetricStream(t *testing.T) {
//
//		// make and configure a mocked processor.MetricStream
//		mockedMetricStream := &MetricStreamMock{
//			MetadataFunc: func() model.Metadata {
//				panic("mock out the Metadata method")
//			},
//			ReadFunc: func(ctx context.Context) (*model.Segment, error) {
//				panic("mock out the Read method")
//			},
//			WriteFunc: func(ctx context.Context, status model.StreamSegmentProcessingStatus) error {
//				panic("mock out the Write method")
//			},
//		}
//
//		// use mockedMetricStream in code that requires processor.MetricStream
//		// and then make assertions.
//
//	}
type MetricStreamMock struct {
	// MetadataFunc mocks the Metadata method.
	MetadataFunc func() model.Metadata

	// ReadFunc mocks the Read method.
	ReadFunc func(ctx context.Context) (*model.Segment, error)

	// WriteFunc mocks the Write method.
	WriteFunc func(ctx context.Context, status model.StreamSegmentProcessingStatus) error

	// calls tracks calls to the methods.
	calls struct {
		// Metadata holds details about calls to the Metadata method.
		Metadata []struct {
		}
		// Read holds details about calls to the Read method.
		Read []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Write holds details about calls to the Write method.
		Write []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Status is the status argument value.
			Status model.StreamSegmentProcessingStatus
		}
	}
	lockMetadata sync.RWMutex
	lockRead     sync.RWMutex
	lockWrite    sync.RWMutex
}

// Metadata calls MetadataFunc.
func (mock *MetricStreamMock) Metadata() model.Metadata {
	if mock.MetadataFunc == nil {
		panic("MetricStreamMock.MetadataFunc: method is nil but MetricStream.Metadata was just called")
	}
	callInfo := struct {
	}{}
	mock.lockMetadata.Lock()
	mock.calls.Metadata = append(mock.calls.Metadata, callInfo)
	mock.lockMetadata.Unlock()
	return mock.MetadataFunc()
}

// MetadataCalls gets all the calls that were made to Metadata.
// Check the length with:
//
//	len(mockedMetricStream.MetadataCalls())
func (mock *MetricStreamMock) MetadataCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockMetadata.RLock()
	calls = mock.calls.Metadata
	mock.lockMetadata.RUnlock()
	return calls
}

// Read calls ReadFunc.
func (mock *MetricStreamMock) Read(ctx context.Context) (*model.Segment, error) {
	if mock.ReadFunc == nil {
		panic("MetricStreamMock.ReadFunc: method is nil but MetricStream.Read was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockRead.Lock()
	mock.calls.Read = append(mock.calls.Read, callInfo)
	mock.lockRead.Unlock()
	return mock.ReadFunc(ctx)
}

// ReadCalls gets all the calls that were made to Read.
// Check the length with:
//
//	len(mockedMetricStream.ReadCalls())
func (mock *MetricStreamMock) ReadCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockRead.RLock()
	calls = mock.calls.Read
	mock.lockRead.RUnlock()
	return calls
}

// Write calls WriteFunc.
func (mock *MetricStreamMock) Write(ctx context.Context, status model.StreamSegmentProcessingStatus) error {
	if mock.WriteFunc == nil {
		panic("MetricStreamMock.WriteFunc: method is nil but MetricStream.Write was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Status model.StreamSegmentProcessingStatus
	}{
		Ctx:    ctx,
		Status: status,
	}
	mock.lockWrite.Lock()
	mock.calls.Write = append(mock.calls.Write, callInfo)
	mock.lockWrite.Unlock()
	return mock.WriteFunc(ctx, status)
}

// WriteCalls gets all the calls that were made to Write.
// Check the length with:
//
//	len(mockedMetricStream.WriteCalls())
func (mock *MetricStreamMock) WriteCalls() []struct {
	Ctx    context.Context
	Status model.StreamSegmentProcessingStatus
} {
	var calls []struct {
		Ctx    context.Context
		Status model.StreamSegmentProcessingStatus
	}
	mock.lockWrite.RLock()
	calls = mock.calls.Write
	mock.lockWrite.RUnlock()
	return calls
}

// Ensure, that RefillMock does implement processor.Refill.
// If this is not the case, regenerate this file with moq.
var _ processor.Refill = &RefillMock{}

// RefillMock is a mock implementation of processor.Refill.
//
//	func TestSomethingThatUsesRefill(t *testing.T) {
//
//		// make and configure a mocked processor.Refill
//		mockedRefill := &RefillMock{
//			MetadataFunc: func() model.Metadata {
//				panic("mock out the Metadata method")
//			},
//			ReadFunc: func(ctx context.Context) (*model.Segment, error) {
//				panic("mock out the Read method")
//			},
//			WriteFunc: func(ctx context.Context, status model.RefillProcessingStatus) error {
//				panic("mock out the Write method")
//			},
//		}
//
//		// use mockedRefill in code that requires processor.Refill
//		// and then make assertions.
//
//	}
type RefillMock struct {
	// MetadataFunc mocks the Metadata method.
	MetadataFunc func() model.Metadata

	// ReadFunc mocks the Read method.
	ReadFunc func(ctx context.Context) (*model.Segment, error)

	// WriteFunc mocks the Write method.
	WriteFunc func(ctx context.Context, status model.RefillProcessingStatus) error

	// calls tracks calls to the methods.
	calls struct {
		// Metadata holds details about calls to the Metadata method.
		Metadata []struct {
		}
		// Read holds details about calls to the Read method.
		Read []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Write holds details about calls to the Write method.
		Write []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Status is the status argument value.
			Status model.RefillProcessingStatus
		}
	}
	lockMetadata sync.RWMutex
	lockRead     sync.RWMutex
	lockWrite    sync.RWMutex
}

// Metadata calls MetadataFunc.
func (mock *RefillMock) Metadata() model.Metadata {
	if mock.MetadataFunc == nil {
		panic("RefillMock.MetadataFunc: method is nil but Refill.Metadata was just called")
	}
	callInfo := struct {
	}{}
	mock.lockMetadata.Lock()
	mock.calls.Metadata = append(mock.calls.Metadata, callInfo)
	mock.lockMetadata.Unlock()
	return mock.MetadataFunc()
}

// MetadataCalls gets all the calls that were made to Metadata.
// Check the length with:
//
//	len(mockedRefill.MetadataCalls())
func (mock *RefillMock) MetadataCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockMetadata.RLock()
	calls = mock.calls.Metadata
	mock.lockMetadata.RUnlock()
	return calls
}

// Read calls ReadFunc.
func (mock *RefillMock) Read(ctx context.Context) (*model.Segment, error) {
	if mock.ReadFunc == nil {
		panic("RefillMock.ReadFunc: method is nil but Refill.Read was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockRead.Lock()
	mock.calls.Read = append(mock.calls.Read, callInfo)
	mock.lockRead.Unlock()
	return mock.ReadFunc(ctx)
}

// ReadCalls gets all the calls that were made to Read.
// Check the length with:
//
//	len(mockedRefill.ReadCalls())
func (mock *RefillMock) ReadCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockRead.RLock()
	calls = mock.calls.Read
	mock.lockRead.RUnlock()
	return calls
}

// Write calls WriteFunc.
func (mock *RefillMock) Write(ctx context.Context, status model.RefillProcessingStatus) error {
	if mock.WriteFunc == nil {
		panic("RefillMock.WriteFunc: method is nil but Refill.Write was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Status model.RefillProcessingStatus
	}{
		Ctx:    ctx,
		Status: status,
	}
	mock.lockWrite.Lock()
	mock.calls.Write = append(mock.calls.Write, callInfo)
	mock.lockWrite.Unlock()
	return mock.WriteFunc(ctx, status)
}

// WriteCalls gets all the calls that were made to Write.
// Check the length with:
//
//	len(mockedRefill.WriteCalls())
func (mock *RefillMock) WriteCalls() []struct {
	Ctx    context.Context
	Status model.RefillProcessingStatus
} {
	var calls []struct {
		Ctx    context.Context
		Status model.RefillProcessingStatus
	}
	mock.lockWrite.RLock()
	calls = mock.calls.Write
	mock.lockWrite.RUnlock()
	return calls
}
