// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package processor_test

import (
	"context"
	"github.com/prometheus/prometheus/pp-pkg/handler/model"
	"sync"
)

// RefillMock is a mock implementation of processor.Refill.
//
//	func TestSomethingThatUsesRefill(t *testing.T) {
//
//		// make and configure a mocked processor.Refill
//		mockedRefill := &RefillMock{
//			MetadataFunc: func() model.Metadata {
//				panic("mock out the Metadata method")
//			},
//			ReadFunc: func(ctx context.Context) (*model.Segment, error) {
//				panic("mock out the Read method")
//			},
//			WriteFunc: func(ctx context.Context, status model.RefillProcessingStatus) error {
//				panic("mock out the Write method")
//			},
//		}
//
//		// use mockedRefill in code that requires processor.Refill
//		// and then make assertions.
//
//	}
type RefillMock struct {
	// MetadataFunc mocks the Metadata method.
	MetadataFunc func() model.Metadata

	// ReadFunc mocks the Read method.
	ReadFunc func(ctx context.Context) (*model.Segment, error)

	// WriteFunc mocks the Write method.
	WriteFunc func(ctx context.Context, status model.RefillProcessingStatus) error

	// calls tracks calls to the methods.
	calls struct {
		// Metadata holds details about calls to the Metadata method.
		Metadata []struct {
		}
		// Read holds details about calls to the Read method.
		Read []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Write holds details about calls to the Write method.
		Write []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Status is the status argument value.
			Status model.RefillProcessingStatus
		}
	}
	lockMetadata sync.RWMutex
	lockRead     sync.RWMutex
	lockWrite    sync.RWMutex
}

// Metadata calls MetadataFunc.
func (mock *RefillMock) Metadata() model.Metadata {
	if mock.MetadataFunc == nil {
		panic("RefillMock.MetadataFunc: method is nil but Refill.Metadata was just called")
	}
	callInfo := struct {
	}{}
	mock.lockMetadata.Lock()
	mock.calls.Metadata = append(mock.calls.Metadata, callInfo)
	mock.lockMetadata.Unlock()
	return mock.MetadataFunc()
}

// MetadataCalls gets all the calls that were made to Metadata.
// Check the length with:
//
//	len(mockedRefill.MetadataCalls())
func (mock *RefillMock) MetadataCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockMetadata.RLock()
	calls = mock.calls.Metadata
	mock.lockMetadata.RUnlock()
	return calls
}

// Read calls ReadFunc.
func (mock *RefillMock) Read(ctx context.Context) (*model.Segment, error) {
	if mock.ReadFunc == nil {
		panic("RefillMock.ReadFunc: method is nil but Refill.Read was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockRead.Lock()
	mock.calls.Read = append(mock.calls.Read, callInfo)
	mock.lockRead.Unlock()
	return mock.ReadFunc(ctx)
}

// ReadCalls gets all the calls that were made to Read.
// Check the length with:
//
//	len(mockedRefill.ReadCalls())
func (mock *RefillMock) ReadCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockRead.RLock()
	calls = mock.calls.Read
	mock.lockRead.RUnlock()
	return calls
}

// Write calls WriteFunc.
func (mock *RefillMock) Write(ctx context.Context, status model.RefillProcessingStatus) error {
	if mock.WriteFunc == nil {
		panic("RefillMock.WriteFunc: method is nil but Refill.Write was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Status model.RefillProcessingStatus
	}{
		Ctx:    ctx,
		Status: status,
	}
	mock.lockWrite.Lock()
	mock.calls.Write = append(mock.calls.Write, callInfo)
	mock.lockWrite.Unlock()
	return mock.WriteFunc(ctx, status)
}

// WriteCalls gets all the calls that were made to Write.
// Check the length with:
//
//	len(mockedRefill.WriteCalls())
func (mock *RefillMock) WriteCalls() []struct {
	Ctx    context.Context
	Status model.RefillProcessingStatus
} {
	var calls []struct {
		Ctx    context.Context
		Status model.RefillProcessingStatus
	}
	mock.lockWrite.RLock()
	calls = mock.calls.Write
	mock.lockWrite.RUnlock()
	return calls
}
