// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package processor_test

import (
	"github.com/prometheus/prometheus/pp/go/cppbridge"
	"sync"
)

// StatesStorageMock is a mock implementation of processor.StatesStorage.
//
//	func TestSomethingThatUsesStatesStorage(t *testing.T) {
//
//		// make and configure a mocked processor.StatesStorage
//		mockedStatesStorage := &StatesStorageMock{
//			GetStateByIDFunc: func(stateID string) (*cppbridge.StateV2, bool) {
//				panic("mock out the GetStateByID method")
//			},
//		}
//
//		// use mockedStatesStorage in code that requires processor.StatesStorage
//		// and then make assertions.
//
//	}
type StatesStorageMock struct {
	// GetStateByIDFunc mocks the GetStateByID method.
	GetStateByIDFunc func(stateID string) (*cppbridge.StateV2, bool)

	// calls tracks calls to the methods.
	calls struct {
		// GetStateByID holds details about calls to the GetStateByID method.
		GetStateByID []struct {
			// StateID is the stateID argument value.
			StateID string
		}
	}
	lockGetStateByID sync.RWMutex
}

// GetStateByID calls GetStateByIDFunc.
func (mock *StatesStorageMock) GetStateByID(stateID string) (*cppbridge.StateV2, bool) {
	if mock.GetStateByIDFunc == nil {
		panic("StatesStorageMock.GetStateByIDFunc: method is nil but StatesStorage.GetStateByID was just called")
	}
	callInfo := struct {
		StateID string
	}{
		StateID: stateID,
	}
	mock.lockGetStateByID.Lock()
	mock.calls.GetStateByID = append(mock.calls.GetStateByID, callInfo)
	mock.lockGetStateByID.Unlock()
	return mock.GetStateByIDFunc(stateID)
}

// GetStateByIDCalls gets all the calls that were made to GetStateByID.
// Check the length with:
//
//	len(mockedStatesStorage.GetStateByIDCalls())
func (mock *StatesStorageMock) GetStateByIDCalls() []struct {
	StateID string
} {
	var calls []struct {
		StateID string
	}
	mock.lockGetStateByID.RLock()
	calls = mock.calls.GetStateByID
	mock.lockGetStateByID.RUnlock()
	return calls
}
