// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"sync"
)

// ReadyNotifierMock is a mock implementation of web.ReadyNotifier.
//
//	func TestSomethingThatUsesReadyNotifier(t *testing.T) {
//
//		// make and configure a mocked web.ReadyNotifier
//		mockedReadyNotifier := &ReadyNotifierMock{
//			NotifyReadyFunc: func()  {
//				panic("mock out the NotifyReady method")
//			},
//		}
//
//		// use mockedReadyNotifier in code that requires web.ReadyNotifier
//		// and then make assertions.
//
//	}
type ReadyNotifierMock struct {
	// NotifyReadyFunc mocks the NotifyReady method.
	NotifyReadyFunc func()

	// calls tracks calls to the methods.
	calls struct {
		// NotifyReady holds details about calls to the NotifyReady method.
		NotifyReady []struct {
		}
	}
	lockNotifyReady sync.RWMutex
}

// NotifyReady calls NotifyReadyFunc.
func (mock *ReadyNotifierMock) NotifyReady() {
	if mock.NotifyReadyFunc == nil {
		panic("ReadyNotifierMock.NotifyReadyFunc: method is nil but ReadyNotifier.NotifyReady was just called")
	}
	callInfo := struct {
	}{}
	mock.lockNotifyReady.Lock()
	mock.calls.NotifyReady = append(mock.calls.NotifyReady, callInfo)
	mock.lockNotifyReady.Unlock()
	mock.NotifyReadyFunc()
}

// NotifyReadyCalls gets all the calls that were made to NotifyReady.
// Check the length with:
//
//	len(mockedReadyNotifier.NotifyReadyCalls())
func (mock *ReadyNotifierMock) NotifyReadyCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockNotifyReady.RLock()
	calls = mock.calls.NotifyReady
	mock.lockNotifyReady.RUnlock()
	return calls
}
