// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/prometheus/prometheus/model/labels"
	"github.com/prometheus/prometheus/tsdb"
	"sync"
)

// TSDBAdminStatsMock is a mock implementation of web.TSDBAdminStats.
//
//	func TestSomethingThatUsesTSDBAdminStats(t *testing.T) {
//
//		// make and configure a mocked web.TSDBAdminStats
//		mockedTSDBAdminStats := &TSDBAdminStatsMock{
//			CleanTombstonesFunc: func() error {
//				panic("mock out the CleanTombstones method")
//			},
//			DeleteFunc: func(ctx context.Context, mint int64, maxt int64, ms ...*labels.Matcher) error {
//				panic("mock out the Delete method")
//			},
//			SnapshotFunc: func(dir string, withHead bool) error {
//				panic("mock out the Snapshot method")
//			},
//			StatsFunc: func(statsByLabelName string, limit int) (*tsdb.Stats, error) {
//				panic("mock out the Stats method")
//			},
//			WALReplayStatusFunc: func() (tsdb.WALReplayStatus, error) {
//				panic("mock out the WALReplayStatus method")
//			},
//		}
//
//		// use mockedTSDBAdminStats in code that requires web.TSDBAdminStats
//		// and then make assertions.
//
//	}
type TSDBAdminStatsMock struct {
	// CleanTombstonesFunc mocks the CleanTombstones method.
	CleanTombstonesFunc func() error

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, mint int64, maxt int64, ms ...*labels.Matcher) error

	// SnapshotFunc mocks the Snapshot method.
	SnapshotFunc func(dir string, withHead bool) error

	// StatsFunc mocks the Stats method.
	StatsFunc func(statsByLabelName string, limit int) (*tsdb.Stats, error)

	// WALReplayStatusFunc mocks the WALReplayStatus method.
	WALReplayStatusFunc func() (tsdb.WALReplayStatus, error)

	// calls tracks calls to the methods.
	calls struct {
		// CleanTombstones holds details about calls to the CleanTombstones method.
		CleanTombstones []struct {
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Mint is the mint argument value.
			Mint int64
			// Maxt is the maxt argument value.
			Maxt int64
			// Ms is the ms argument value.
			Ms []*labels.Matcher
		}
		// Snapshot holds details about calls to the Snapshot method.
		Snapshot []struct {
			// Dir is the dir argument value.
			Dir string
			// WithHead is the withHead argument value.
			WithHead bool
		}
		// Stats holds details about calls to the Stats method.
		Stats []struct {
			// StatsByLabelName is the statsByLabelName argument value.
			StatsByLabelName string
			// Limit is the limit argument value.
			Limit int
		}
		// WALReplayStatus holds details about calls to the WALReplayStatus method.
		WALReplayStatus []struct {
		}
	}
	lockCleanTombstones sync.RWMutex
	lockDelete          sync.RWMutex
	lockSnapshot        sync.RWMutex
	lockStats           sync.RWMutex
	lockWALReplayStatus sync.RWMutex
}

// CleanTombstones calls CleanTombstonesFunc.
func (mock *TSDBAdminStatsMock) CleanTombstones() error {
	if mock.CleanTombstonesFunc == nil {
		panic("TSDBAdminStatsMock.CleanTombstonesFunc: method is nil but TSDBAdminStats.CleanTombstones was just called")
	}
	callInfo := struct {
	}{}
	mock.lockCleanTombstones.Lock()
	mock.calls.CleanTombstones = append(mock.calls.CleanTombstones, callInfo)
	mock.lockCleanTombstones.Unlock()
	return mock.CleanTombstonesFunc()
}

// CleanTombstonesCalls gets all the calls that were made to CleanTombstones.
// Check the length with:
//
//	len(mockedTSDBAdminStats.CleanTombstonesCalls())
func (mock *TSDBAdminStatsMock) CleanTombstonesCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockCleanTombstones.RLock()
	calls = mock.calls.CleanTombstones
	mock.lockCleanTombstones.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *TSDBAdminStatsMock) Delete(ctx context.Context, mint int64, maxt int64, ms ...*labels.Matcher) error {
	if mock.DeleteFunc == nil {
		panic("TSDBAdminStatsMock.DeleteFunc: method is nil but TSDBAdminStats.Delete was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Mint int64
		Maxt int64
		Ms   []*labels.Matcher
	}{
		Ctx:  ctx,
		Mint: mint,
		Maxt: maxt,
		Ms:   ms,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, mint, maxt, ms...)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedTSDBAdminStats.DeleteCalls())
func (mock *TSDBAdminStatsMock) DeleteCalls() []struct {
	Ctx  context.Context
	Mint int64
	Maxt int64
	Ms   []*labels.Matcher
} {
	var calls []struct {
		Ctx  context.Context
		Mint int64
		Maxt int64
		Ms   []*labels.Matcher
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Snapshot calls SnapshotFunc.
func (mock *TSDBAdminStatsMock) Snapshot(dir string, withHead bool) error {
	if mock.SnapshotFunc == nil {
		panic("TSDBAdminStatsMock.SnapshotFunc: method is nil but TSDBAdminStats.Snapshot was just called")
	}
	callInfo := struct {
		Dir      string
		WithHead bool
	}{
		Dir:      dir,
		WithHead: withHead,
	}
	mock.lockSnapshot.Lock()
	mock.calls.Snapshot = append(mock.calls.Snapshot, callInfo)
	mock.lockSnapshot.Unlock()
	return mock.SnapshotFunc(dir, withHead)
}

// SnapshotCalls gets all the calls that were made to Snapshot.
// Check the length with:
//
//	len(mockedTSDBAdminStats.SnapshotCalls())
func (mock *TSDBAdminStatsMock) SnapshotCalls() []struct {
	Dir      string
	WithHead bool
} {
	var calls []struct {
		Dir      string
		WithHead bool
	}
	mock.lockSnapshot.RLock()
	calls = mock.calls.Snapshot
	mock.lockSnapshot.RUnlock()
	return calls
}

// Stats calls StatsFunc.
func (mock *TSDBAdminStatsMock) Stats(statsByLabelName string, limit int) (*tsdb.Stats, error) {
	if mock.StatsFunc == nil {
		panic("TSDBAdminStatsMock.StatsFunc: method is nil but TSDBAdminStats.Stats was just called")
	}
	callInfo := struct {
		StatsByLabelName string
		Limit            int
	}{
		StatsByLabelName: statsByLabelName,
		Limit:            limit,
	}
	mock.lockStats.Lock()
	mock.calls.Stats = append(mock.calls.Stats, callInfo)
	mock.lockStats.Unlock()
	return mock.StatsFunc(statsByLabelName, limit)
}

// StatsCalls gets all the calls that were made to Stats.
// Check the length with:
//
//	len(mockedTSDBAdminStats.StatsCalls())
func (mock *TSDBAdminStatsMock) StatsCalls() []struct {
	StatsByLabelName string
	Limit            int
} {
	var calls []struct {
		StatsByLabelName string
		Limit            int
	}
	mock.lockStats.RLock()
	calls = mock.calls.Stats
	mock.lockStats.RUnlock()
	return calls
}

// WALReplayStatus calls WALReplayStatusFunc.
func (mock *TSDBAdminStatsMock) WALReplayStatus() (tsdb.WALReplayStatus, error) {
	if mock.WALReplayStatusFunc == nil {
		panic("TSDBAdminStatsMock.WALReplayStatusFunc: method is nil but TSDBAdminStats.WALReplayStatus was just called")
	}
	callInfo := struct {
	}{}
	mock.lockWALReplayStatus.Lock()
	mock.calls.WALReplayStatus = append(mock.calls.WALReplayStatus, callInfo)
	mock.lockWALReplayStatus.Unlock()
	return mock.WALReplayStatusFunc()
}

// WALReplayStatusCalls gets all the calls that were made to WALReplayStatus.
// Check the length with:
//
//	len(mockedTSDBAdminStats.WALReplayStatusCalls())
func (mock *TSDBAdminStatsMock) WALReplayStatusCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockWALReplayStatus.RLock()
	calls = mock.calls.WALReplayStatus
	mock.lockWALReplayStatus.RUnlock()
	return calls
}
