// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package head_test

import (
	"sync"
)

// ShardMock is a mock implementation of head.Shard.
//
//	func TestSomethingThatUsesShard(t *testing.T) {
//
//		// make and configure a mocked head.Shard
//		mockedShard := &ShardMock{
//			CloseFunc: func() error {
//				panic("mock out the Close method")
//			},
//			ShardIDFunc: func() uint16 {
//				panic("mock out the ShardID method")
//			},
//		}
//
//		// use mockedShard in code that requires head.Shard
//		// and then make assertions.
//
//	}
type ShardMock struct {
	// CloseFunc mocks the Close method.
	CloseFunc func() error

	// ShardIDFunc mocks the ShardID method.
	ShardIDFunc func() uint16

	// calls tracks calls to the methods.
	calls struct {
		// Close holds details about calls to the Close method.
		Close []struct {
		}
		// ShardID holds details about calls to the ShardID method.
		ShardID []struct {
		}
	}
	lockClose   sync.RWMutex
	lockShardID sync.RWMutex
}

// Close calls CloseFunc.
func (mock *ShardMock) Close() error {
	if mock.CloseFunc == nil {
		panic("ShardMock.CloseFunc: method is nil but Shard.Close was just called")
	}
	callInfo := struct {
	}{}
	mock.lockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	mock.lockClose.Unlock()
	return mock.CloseFunc()
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//
//	len(mockedShard.CloseCalls())
func (mock *ShardMock) CloseCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockClose.RLock()
	calls = mock.calls.Close
	mock.lockClose.RUnlock()
	return calls
}

// ShardID calls ShardIDFunc.
func (mock *ShardMock) ShardID() uint16 {
	if mock.ShardIDFunc == nil {
		panic("ShardMock.ShardIDFunc: method is nil but Shard.ShardID was just called")
	}
	callInfo := struct {
	}{}
	mock.lockShardID.Lock()
	mock.calls.ShardID = append(mock.calls.ShardID, callInfo)
	mock.lockShardID.Unlock()
	return mock.ShardIDFunc()
}

// ShardIDCalls gets all the calls that were made to ShardID.
// Check the length with:
//
//	len(mockedShard.ShardIDCalls())
func (mock *ShardMock) ShardIDCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockShardID.RLock()
	calls = mock.calls.ShardID
	mock.lockShardID.RUnlock()
	return calls
}
