// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package catalog_test

import (
	"github.com/prometheus/prometheus/pp/go/storage/catalog"
	"sync"
)

// LogMock is a mock implementation of catalog.Log.
//
//	func TestSomethingThatUsesLog(t *testing.T) {
//
//		// make and configure a mocked catalog.Log
//		mockedLog := &LogMock{
//			ReWriteFunc: func(srecords ...*catalog.SerializedRecord) error {
//				panic("mock out the ReWrite method")
//			},
//			ReadFunc: func(sr *catalog.SerializedRecord) error {
//				panic("mock out the Read method")
//			},
//			SizeFunc: func() int {
//				panic("mock out the Size method")
//			},
//			WriteFunc: func(srecord *catalog.SerializedRecord) error {
//				panic("mock out the Write method")
//			},
//		}
//
//		// use mockedLog in code that requires catalog.Log
//		// and then make assertions.
//
//	}
type LogMock struct {
	// ReWriteFunc mocks the ReWrite method.
	ReWriteFunc func(srecords ...*catalog.SerializedRecord) error

	// ReadFunc mocks the Read method.
	ReadFunc func(sr *catalog.SerializedRecord) error

	// SizeFunc mocks the Size method.
	SizeFunc func() int

	// WriteFunc mocks the Write method.
	WriteFunc func(srecord *catalog.SerializedRecord) error

	// calls tracks calls to the methods.
	calls struct {
		// ReWrite holds details about calls to the ReWrite method.
		ReWrite []struct {
			// Srecords is the srecords argument value.
			Srecords []*catalog.SerializedRecord
		}
		// Read holds details about calls to the Read method.
		Read []struct {
			// Sr is the sr argument value.
			Sr *catalog.SerializedRecord
		}
		// Size holds details about calls to the Size method.
		Size []struct {
		}
		// Write holds details about calls to the Write method.
		Write []struct {
			// Srecord is the srecord argument value.
			Srecord *catalog.SerializedRecord
		}
	}
	lockReWrite sync.RWMutex
	lockRead    sync.RWMutex
	lockSize    sync.RWMutex
	lockWrite   sync.RWMutex
}

// ReWrite calls ReWriteFunc.
func (mock *LogMock) ReWrite(srecords ...*catalog.SerializedRecord) error {
	if mock.ReWriteFunc == nil {
		panic("LogMock.ReWriteFunc: method is nil but Log.ReWrite was just called")
	}
	callInfo := struct {
		Srecords []*catalog.SerializedRecord
	}{
		Srecords: srecords,
	}
	mock.lockReWrite.Lock()
	mock.calls.ReWrite = append(mock.calls.ReWrite, callInfo)
	mock.lockReWrite.Unlock()
	return mock.ReWriteFunc(srecords...)
}

// ReWriteCalls gets all the calls that were made to ReWrite.
// Check the length with:
//
//	len(mockedLog.ReWriteCalls())
func (mock *LogMock) ReWriteCalls() []struct {
	Srecords []*catalog.SerializedRecord
} {
	var calls []struct {
		Srecords []*catalog.SerializedRecord
	}
	mock.lockReWrite.RLock()
	calls = mock.calls.ReWrite
	mock.lockReWrite.RUnlock()
	return calls
}

// Read calls ReadFunc.
func (mock *LogMock) Read(sr *catalog.SerializedRecord) error {
	if mock.ReadFunc == nil {
		panic("LogMock.ReadFunc: method is nil but Log.Read was just called")
	}
	callInfo := struct {
		Sr *catalog.SerializedRecord
	}{
		Sr: sr,
	}
	mock.lockRead.Lock()
	mock.calls.Read = append(mock.calls.Read, callInfo)
	mock.lockRead.Unlock()
	return mock.ReadFunc(sr)
}

// ReadCalls gets all the calls that were made to Read.
// Check the length with:
//
//	len(mockedLog.ReadCalls())
func (mock *LogMock) ReadCalls() []struct {
	Sr *catalog.SerializedRecord
} {
	var calls []struct {
		Sr *catalog.SerializedRecord
	}
	mock.lockRead.RLock()
	calls = mock.calls.Read
	mock.lockRead.RUnlock()
	return calls
}

// Size calls SizeFunc.
func (mock *LogMock) Size() int {
	if mock.SizeFunc == nil {
		panic("LogMock.SizeFunc: method is nil but Log.Size was just called")
	}
	callInfo := struct {
	}{}
	mock.lockSize.Lock()
	mock.calls.Size = append(mock.calls.Size, callInfo)
	mock.lockSize.Unlock()
	return mock.SizeFunc()
}

// SizeCalls gets all the calls that were made to Size.
// Check the length with:
//
//	len(mockedLog.SizeCalls())
func (mock *LogMock) SizeCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockSize.RLock()
	calls = mock.calls.Size
	mock.lockSize.RUnlock()
	return calls
}

// Write calls WriteFunc.
func (mock *LogMock) Write(srecord *catalog.SerializedRecord) error {
	if mock.WriteFunc == nil {
		panic("LogMock.WriteFunc: method is nil but Log.Write was just called")
	}
	callInfo := struct {
		Srecord *catalog.SerializedRecord
	}{
		Srecord: srecord,
	}
	mock.lockWrite.Lock()
	mock.calls.Write = append(mock.calls.Write, callInfo)
	mock.lockWrite.Unlock()
	return mock.WriteFunc(srecord)
}

// WriteCalls gets all the calls that were made to Write.
// Check the length with:
//
//	len(mockedLog.WriteCalls())
func (mock *LogMock) WriteCalls() []struct {
	Srecord *catalog.SerializedRecord
} {
	var calls []struct {
		Srecord *catalog.SerializedRecord
	}
	mock.lockWrite.RLock()
	calls = mock.calls.Write
	mock.lockWrite.RUnlock()
	return calls
}
