blank_issues_enabled: false
contact_links:
  - name: 🤔 Ask a question
    url: https://github.com/deckhouse/prompp/discussions/new?category=q-a
    about: Ask and discuss questions with other community members

  - name: 💬 Telegram channel
    url: https://t.me/prom_plus_plus
    about: Please ask and answer questions here
