// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package wal_test

import (
	"github.com/prometheus/prometheus/pp/go/storage/head/shard/wal"
	"io"
	"sync"
)

// Ensure, that ReadSegmentMock does implement wal.ReadSegment.
// If this is not the case, regenerate this file with moq.
var _ wal.ReadSegment = &ReadSegmentMock{}

// ReadSegmentMock is a mock implementation of wal.ReadSegment.
//
//	func TestSomethingThatUsesReadSegment(t *testing.T) {
//
//		// make and configure a mocked wal.ReadSegment
//		mockedReadSegment := &ReadSegmentMock{
//			ReadFromFunc: func(r io.Reader) (int64, error) {
//				panic("mock out the ReadFrom method")
//			},
//			ResetFunc: func()  {
//				panic("mock out the Reset method")
//			},
//		}
//
//		// use mockedReadSegment in code that requires wal.ReadSegment
//		// and then make assertions.
//
//	}
type ReadSegmentMock struct {
	// ReadFromFunc mocks the ReadFrom method.
	ReadFromFunc func(r io.Reader) (int64, error)

	// ResetFunc mocks the Reset method.
	ResetFunc func()

	// calls tracks calls to the methods.
	calls struct {
		// ReadFrom holds details about calls to the ReadFrom method.
		ReadFrom []struct {
			// R is the r argument value.
			R io.Reader
		}
		// Reset holds details about calls to the Reset method.
		Reset []struct {
		}
	}
	lockReadFrom sync.RWMutex
	lockReset    sync.RWMutex
}

// ReadFrom calls ReadFromFunc.
func (mock *ReadSegmentMock) ReadFrom(r io.Reader) (int64, error) {
	if mock.ReadFromFunc == nil {
		panic("ReadSegmentMock.ReadFromFunc: method is nil but ReadSegment.ReadFrom was just called")
	}
	callInfo := struct {
		R io.Reader
	}{
		R: r,
	}
	mock.lockReadFrom.Lock()
	mock.calls.ReadFrom = append(mock.calls.ReadFrom, callInfo)
	mock.lockReadFrom.Unlock()
	return mock.ReadFromFunc(r)
}

// ReadFromCalls gets all the calls that were made to ReadFrom.
// Check the length with:
//
//	len(mockedReadSegment.ReadFromCalls())
func (mock *ReadSegmentMock) ReadFromCalls() []struct {
	R io.Reader
} {
	var calls []struct {
		R io.Reader
	}
	mock.lockReadFrom.RLock()
	calls = mock.calls.ReadFrom
	mock.lockReadFrom.RUnlock()
	return calls
}

// Reset calls ResetFunc.
func (mock *ReadSegmentMock) Reset() {
	if mock.ResetFunc == nil {
		panic("ReadSegmentMock.ResetFunc: method is nil but ReadSegment.Reset was just called")
	}
	callInfo := struct {
	}{}
	mock.lockReset.Lock()
	mock.calls.Reset = append(mock.calls.Reset, callInfo)
	mock.lockReset.Unlock()
	mock.ResetFunc()
}

// ResetCalls gets all the calls that were made to Reset.
// Check the length with:
//
//	len(mockedReadSegment.ResetCalls())
func (mock *ReadSegmentMock) ResetCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockReset.RLock()
	calls = mock.calls.Reset
	mock.lockReset.RUnlock()
	return calls
}
