// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package wal_test

import (
	"github.com/prometheus/prometheus/pp/go/cppbridge"
	"github.com/prometheus/prometheus/pp/go/storage/head/shard/wal"
	"io"
	"sync"
)

// SegmentWriterMock is a mock implementation of wal.SegmentWriter.
//
//	func TestSomethingThatUsesSegmentWriter(t *testing.T) {
//
//		// make and configure a mocked wal.SegmentWriter
//		mockedSegmentWriter := &SegmentWriterMock{
//			CloseFunc: func() error {
//				panic("mock out the Close method")
//			},
//			CurrentSizeFunc: func() int64 {
//				panic("mock out the CurrentSize method")
//			},
//			FlushFunc: func() error {
//				panic("mock out the Flush method")
//			},
//			SyncFunc: func() error {
//				panic("mock out the Sync method")
//			},
//			WriteFunc: func(segment TSegment) error {
//				panic("mock out the Write method")
//			},
//		}
//
//		// use mockedSegmentWriter in code that requires wal.SegmentWriter
//		// and then make assertions.
//
//	}
type SegmentWriterMock[TSegment wal.EncodedSegment] struct {
	// CloseFunc mocks the Close method.
	CloseFunc func() error

	// CurrentSizeFunc mocks the CurrentSize method.
	CurrentSizeFunc func() int64

	// FlushFunc mocks the Flush method.
	FlushFunc func() error

	// SyncFunc mocks the Sync method.
	SyncFunc func() error

	// WriteFunc mocks the Write method.
	WriteFunc func(segment TSegment) error

	// calls tracks calls to the methods.
	calls struct {
		// Close holds details about calls to the Close method.
		Close []struct {
		}
		// CurrentSize holds details about calls to the CurrentSize method.
		CurrentSize []struct {
		}
		// Flush holds details about calls to the Flush method.
		Flush []struct {
		}
		// Sync holds details about calls to the Sync method.
		Sync []struct {
		}
		// Write holds details about calls to the Write method.
		Write []struct {
			// Segment is the segment argument value.
			Segment TSegment
		}
	}
	lockClose       sync.RWMutex
	lockCurrentSize sync.RWMutex
	lockFlush       sync.RWMutex
	lockSync        sync.RWMutex
	lockWrite       sync.RWMutex
}

// Close calls CloseFunc.
func (mock *SegmentWriterMock[TSegment]) Close() error {
	if mock.CloseFunc == nil {
		panic("SegmentWriterMock.CloseFunc: method is nil but SegmentWriter.Close was just called")
	}
	callInfo := struct {
	}{}
	mock.lockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	mock.lockClose.Unlock()
	return mock.CloseFunc()
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//
//	len(mockedSegmentWriter.CloseCalls())
func (mock *SegmentWriterMock[TSegment]) CloseCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockClose.RLock()
	calls = mock.calls.Close
	mock.lockClose.RUnlock()
	return calls
}

// CurrentSize calls CurrentSizeFunc.
func (mock *SegmentWriterMock[TSegment]) CurrentSize() int64 {
	if mock.CurrentSizeFunc == nil {
		panic("SegmentWriterMock.CurrentSizeFunc: method is nil but SegmentWriter.CurrentSize was just called")
	}
	callInfo := struct {
	}{}
	mock.lockCurrentSize.Lock()
	mock.calls.CurrentSize = append(mock.calls.CurrentSize, callInfo)
	mock.lockCurrentSize.Unlock()
	return mock.CurrentSizeFunc()
}

// CurrentSizeCalls gets all the calls that were made to CurrentSize.
// Check the length with:
//
//	len(mockedSegmentWriter.CurrentSizeCalls())
func (mock *SegmentWriterMock[TSegment]) CurrentSizeCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockCurrentSize.RLock()
	calls = mock.calls.CurrentSize
	mock.lockCurrentSize.RUnlock()
	return calls
}

// Flush calls FlushFunc.
func (mock *SegmentWriterMock[TSegment]) Flush() error {
	if mock.FlushFunc == nil {
		panic("SegmentWriterMock.FlushFunc: method is nil but SegmentWriter.Flush was just called")
	}
	callInfo := struct {
	}{}
	mock.lockFlush.Lock()
	mock.calls.Flush = append(mock.calls.Flush, callInfo)
	mock.lockFlush.Unlock()
	return mock.FlushFunc()
}

// FlushCalls gets all the calls that were made to Flush.
// Check the length with:
//
//	len(mockedSegmentWriter.FlushCalls())
func (mock *SegmentWriterMock[TSegment]) FlushCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockFlush.RLock()
	calls = mock.calls.Flush
	mock.lockFlush.RUnlock()
	return calls
}

// Sync calls SyncFunc.
func (mock *SegmentWriterMock[TSegment]) Sync() error {
	if mock.SyncFunc == nil {
		panic("SegmentWriterMock.SyncFunc: method is nil but SegmentWriter.Sync was just called")
	}
	callInfo := struct {
	}{}
	mock.lockSync.Lock()
	mock.calls.Sync = append(mock.calls.Sync, callInfo)
	mock.lockSync.Unlock()
	return mock.SyncFunc()
}

// SyncCalls gets all the calls that were made to Sync.
// Check the length with:
//
//	len(mockedSegmentWriter.SyncCalls())
func (mock *SegmentWriterMock[TSegment]) SyncCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockSync.RLock()
	calls = mock.calls.Sync
	mock.lockSync.RUnlock()
	return calls
}

// Write calls WriteFunc.
func (mock *SegmentWriterMock[TSegment]) Write(segment TSegment) error {
	if mock.WriteFunc == nil {
		panic("SegmentWriterMock.WriteFunc: method is nil but SegmentWriter.Write was just called")
	}
	callInfo := struct {
		Segment TSegment
	}{
		Segment: segment,
	}
	mock.lockWrite.Lock()
	mock.calls.Write = append(mock.calls.Write, callInfo)
	mock.lockWrite.Unlock()
	return mock.WriteFunc(segment)
}

// WriteCalls gets all the calls that were made to Write.
// Check the length with:
//
//	len(mockedSegmentWriter.WriteCalls())
func (mock *SegmentWriterMock[TSegment]) WriteCalls() []struct {
	Segment TSegment
} {
	var calls []struct {
		Segment TSegment
	}
	mock.lockWrite.RLock()
	calls = mock.calls.Write
	mock.lockWrite.RUnlock()
	return calls
}

// EncoderMock is a mock implementation of wal.Encoder.
//
//	func TestSomethingThatUsesEncoder(t *testing.T) {
//
//		// make and configure a mocked wal.Encoder
//		mockedEncoder := &EncoderMock{
//			EncodeFunc: func(innerSeriesSlice []cppbridge.InnerSeries) (uint32, error) {
//				panic("mock out the Encode method")
//			},
//			FinalizeFunc: func() (TSegment, error) {
//				panic("mock out the Finalize method")
//			},
//			MaxWrittenItemIndexFunc: func() uint32 {
//				panic("mock out the MaxWrittenItemIndex method")
//			},
//		}
//
//		// use mockedEncoder in code that requires wal.Encoder
//		// and then make assertions.
//
//	}
type EncoderMock[TSegment wal.EncodedSegment] struct {
	// EncodeFunc mocks the Encode method.
	EncodeFunc func(innerSeriesSlice []cppbridge.InnerSeries) (uint32, error)

	// FinalizeFunc mocks the Finalize method.
	FinalizeFunc func() (TSegment, error)

	// MaxWrittenItemIndexFunc mocks the MaxWrittenItemIndex method.
	MaxWrittenItemIndexFunc func() uint32

	// calls tracks calls to the methods.
	calls struct {
		// Encode holds details about calls to the Encode method.
		Encode []struct {
			// InnerSeriesSlice is the innerSeriesSlice argument value.
			InnerSeriesSlice []cppbridge.InnerSeries
		}
		// Finalize holds details about calls to the Finalize method.
		Finalize []struct {
		}
		// MaxWrittenItemIndex holds details about calls to the MaxWrittenItemIndex method.
		MaxWrittenItemIndex []struct {
		}
	}
	lockEncode              sync.RWMutex
	lockFinalize            sync.RWMutex
	lockMaxWrittenItemIndex sync.RWMutex
}

// Encode calls EncodeFunc.
func (mock *EncoderMock[TSegment]) Encode(innerSeriesSlice []cppbridge.InnerSeries) (uint32, error) {
	if mock.EncodeFunc == nil {
		panic("EncoderMock.EncodeFunc: method is nil but Encoder.Encode was just called")
	}
	callInfo := struct {
		InnerSeriesSlice []cppbridge.InnerSeries
	}{
		InnerSeriesSlice: innerSeriesSlice,
	}
	mock.lockEncode.Lock()
	mock.calls.Encode = append(mock.calls.Encode, callInfo)
	mock.lockEncode.Unlock()
	return mock.EncodeFunc(innerSeriesSlice)
}

// EncodeCalls gets all the calls that were made to Encode.
// Check the length with:
//
//	len(mockedEncoder.EncodeCalls())
func (mock *EncoderMock[TSegment]) EncodeCalls() []struct {
	InnerSeriesSlice []cppbridge.InnerSeries
} {
	var calls []struct {
		InnerSeriesSlice []cppbridge.InnerSeries
	}
	mock.lockEncode.RLock()
	calls = mock.calls.Encode
	mock.lockEncode.RUnlock()
	return calls
}

// Finalize calls FinalizeFunc.
func (mock *EncoderMock[TSegment]) Finalize() (TSegment, error) {
	if mock.FinalizeFunc == nil {
		panic("EncoderMock.FinalizeFunc: method is nil but Encoder.Finalize was just called")
	}
	callInfo := struct {
	}{}
	mock.lockFinalize.Lock()
	mock.calls.Finalize = append(mock.calls.Finalize, callInfo)
	mock.lockFinalize.Unlock()
	return mock.FinalizeFunc()
}

// FinalizeCalls gets all the calls that were made to Finalize.
// Check the length with:
//
//	len(mockedEncoder.FinalizeCalls())
func (mock *EncoderMock[TSegment]) FinalizeCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockFinalize.RLock()
	calls = mock.calls.Finalize
	mock.lockFinalize.RUnlock()
	return calls
}

// MaxWrittenItemIndex calls MaxWrittenItemIndexFunc.
func (mock *EncoderMock[TSegment]) MaxWrittenItemIndex() uint32 {
	if mock.MaxWrittenItemIndexFunc == nil {
		panic("EncoderMock.MaxWrittenItemIndexFunc: method is nil but Encoder.MaxWrittenItemIndex was just called")
	}
	callInfo := struct {
	}{}
	mock.lockMaxWrittenItemIndex.Lock()
	mock.calls.MaxWrittenItemIndex = append(mock.calls.MaxWrittenItemIndex, callInfo)
	mock.lockMaxWrittenItemIndex.Unlock()
	return mock.MaxWrittenItemIndexFunc()
}

// MaxWrittenItemIndexCalls gets all the calls that were made to MaxWrittenItemIndex.
// Check the length with:
//
//	len(mockedEncoder.MaxWrittenItemIndexCalls())
func (mock *EncoderMock[TSegment]) MaxWrittenItemIndexCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockMaxWrittenItemIndex.RLock()
	calls = mock.calls.MaxWrittenItemIndex
	mock.lockMaxWrittenItemIndex.RUnlock()
	return calls
}

// EncodedSegmentMock is a mock implementation of wal.EncodedSegment.
//
//	func TestSomethingThatUsesEncodedSegment(t *testing.T) {
//
//		// make and configure a mocked wal.EncodedSegment
//		mockedEncodedSegment := &EncodedSegmentMock{
//			CRC32Func: func() uint32 {
//				panic("mock out the CRC32 method")
//			},
//			SamplesFunc: func() uint32 {
//				panic("mock out the Samples method")
//			},
//			SizeFunc: func() int64 {
//				panic("mock out the Size method")
//			},
//			WriteToFunc: func(w io.Writer) (int64, error) {
//				panic("mock out the WriteTo method")
//			},
//		}
//
//		// use mockedEncodedSegment in code that requires wal.EncodedSegment
//		// and then make assertions.
//
//	}
type EncodedSegmentMock struct {
	// CRC32Func mocks the CRC32 method.
	CRC32Func func() uint32

	// SamplesFunc mocks the Samples method.
	SamplesFunc func() uint32

	// SizeFunc mocks the Size method.
	SizeFunc func() int64

	// WriteToFunc mocks the WriteTo method.
	WriteToFunc func(w io.Writer) (int64, error)

	// calls tracks calls to the methods.
	calls struct {
		// CRC32 holds details about calls to the CRC32 method.
		CRC32 []struct {
		}
		// Samples holds details about calls to the Samples method.
		Samples []struct {
		}
		// Size holds details about calls to the Size method.
		Size []struct {
		}
		// WriteTo holds details about calls to the WriteTo method.
		WriteTo []struct {
			// W is the w argument value.
			W io.Writer
		}
	}
	lockCRC32   sync.RWMutex
	lockSamples sync.RWMutex
	lockSize    sync.RWMutex
	lockWriteTo sync.RWMutex
}

// CRC32 calls CRC32Func.
func (mock *EncodedSegmentMock) CRC32() uint32 {
	if mock.CRC32Func == nil {
		panic("EncodedSegmentMock.CRC32Func: method is nil but EncodedSegment.CRC32 was just called")
	}
	callInfo := struct {
	}{}
	mock.lockCRC32.Lock()
	mock.calls.CRC32 = append(mock.calls.CRC32, callInfo)
	mock.lockCRC32.Unlock()
	return mock.CRC32Func()
}

// CRC32Calls gets all the calls that were made to CRC32.
// Check the length with:
//
//	len(mockedEncodedSegment.CRC32Calls())
func (mock *EncodedSegmentMock) CRC32Calls() []struct {
} {
	var calls []struct {
	}
	mock.lockCRC32.RLock()
	calls = mock.calls.CRC32
	mock.lockCRC32.RUnlock()
	return calls
}

// Samples calls SamplesFunc.
func (mock *EncodedSegmentMock) Samples() uint32 {
	if mock.SamplesFunc == nil {
		panic("EncodedSegmentMock.SamplesFunc: method is nil but EncodedSegment.Samples was just called")
	}
	callInfo := struct {
	}{}
	mock.lockSamples.Lock()
	mock.calls.Samples = append(mock.calls.Samples, callInfo)
	mock.lockSamples.Unlock()
	return mock.SamplesFunc()
}

// SamplesCalls gets all the calls that were made to Samples.
// Check the length with:
//
//	len(mockedEncodedSegment.SamplesCalls())
func (mock *EncodedSegmentMock) SamplesCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockSamples.RLock()
	calls = mock.calls.Samples
	mock.lockSamples.RUnlock()
	return calls
}

// Size calls SizeFunc.
func (mock *EncodedSegmentMock) Size() int64 {
	if mock.SizeFunc == nil {
		panic("EncodedSegmentMock.SizeFunc: method is nil but EncodedSegment.Size was just called")
	}
	callInfo := struct {
	}{}
	mock.lockSize.Lock()
	mock.calls.Size = append(mock.calls.Size, callInfo)
	mock.lockSize.Unlock()
	return mock.SizeFunc()
}

// SizeCalls gets all the calls that were made to Size.
// Check the length with:
//
//	len(mockedEncodedSegment.SizeCalls())
func (mock *EncodedSegmentMock) SizeCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockSize.RLock()
	calls = mock.calls.Size
	mock.lockSize.RUnlock()
	return calls
}

// WriteTo calls WriteToFunc.
func (mock *EncodedSegmentMock) WriteTo(w io.Writer) (int64, error) {
	if mock.WriteToFunc == nil {
		panic("EncodedSegmentMock.WriteToFunc: method is nil but EncodedSegment.WriteTo was just called")
	}
	callInfo := struct {
		W io.Writer
	}{
		W: w,
	}
	mock.lockWriteTo.Lock()
	mock.calls.WriteTo = append(mock.calls.WriteTo, callInfo)
	mock.lockWriteTo.Unlock()
	return mock.WriteToFunc(w)
}

// WriteToCalls gets all the calls that were made to WriteTo.
// Check the length with:
//
//	len(mockedEncodedSegment.WriteToCalls())
func (mock *EncodedSegmentMock) WriteToCalls() []struct {
	W io.Writer
} {
	var calls []struct {
		W io.Writer
	}
	mock.lockWriteTo.RLock()
	calls = mock.calls.WriteTo
	mock.lockWriteTo.RUnlock()
	return calls
}
