/* Generated by re2c */
#include <cstring>

#include "prometheus/textparse/escape.h"
#include "tokenizer.h"

// NOLINTBEGIN
enum YYCONDTYPE {
  yycinit,
  yyccomment,
  yycmeta_name,
  yycmeta_text_with_leading_spaces,
  yycexemplar_labels,
  yyclabels,
  yyclabel_value,
  yycexemplar_label_value,
  yycvalue,
  yyctimestamp,
  yycexemplar_value,
  yycexemplar_timestamp
};

// NOLINTEND

namespace PromPP::Prometheus::textparse::OpenMetrics {

Tokenizer::Tokenizer() : condition_{yycinit} {}

Tokenizer::Tokenizer(std::string_view str)
    : start_ptr_(str.data()),
      cursor_ptr_(start_ptr_),
      limit_ptr_(start_ptr_ + str.size()),
      marker_ptr_(start_ptr_),
      token_ptr_(start_ptr_),
      condition_{yycinit} {}

void Tokenizer::tokenize(std::string_view str) noexcept {
  start_ptr_ = str.data();
  cursor_ptr_ = start_ptr_;
  limit_ptr_ = start_ptr_ + str.size();
  marker_ptr_ = start_ptr_;
  token_ptr_ = start_ptr_;

  condition_ = yycinit;
}

Token Tokenizer::consume_comment(Token token) noexcept {
  if (cursor_ptr_ = static_cast<const char*>(std::memchr(cursor_ptr_, '\n', limit_ptr_ - cursor_ptr_)); cursor_ptr_ != nullptr) [[likely]] {
    condition_ = yycinit;
    return token;
  }

  cursor_ptr_ = limit_ptr_;
  return Token::kInvalid;
}

Token Tokenizer::consume_escaped_string(Token token) noexcept {
  while (true) {
    if (cursor_ptr_ = static_cast<const char*>(std::memchr(cursor_ptr_, '"', limit_ptr_ - cursor_ptr_)); cursor_ptr_ == nullptr) [[unlikely]] {
      cursor_ptr_ = limit_ptr_;
      return Token::kInvalid;
    }

    if (is_escaped_char(cursor_ptr_, token_ptr_ + 1)) [[unlikely]] {
      ++cursor_ptr_;
      continue;
    }

    break;
  }

  ++cursor_ptr_;
  return token;
}

// NOLINTBEGIN
Token Tokenizer::next_impl() noexcept {
  token_ptr_ = cursor_ptr_;

  {
    unsigned char yych;
    unsigned int yyaccept = 0;
    static const int yyctable[12] = {(int)((char*) && yyc_init - (char*) && yyc_init),
                                     (int)((char*) && yyc_comment - (char*) && yyc_init),
                                     (int)((char*) && yyc_meta_name - (char*) && yyc_init),
                                     (int)((char*) && yyc_meta_text_with_leading_spaces - (char*) && yyc_init),
                                     (int)((char*) && yyc_exemplar_labels - (char*) && yyc_init),
                                     (int)((char*) && yyc_labels - (char*) && yyc_init),
                                     (int)((char*) && yyc_label_value - (char*) && yyc_init),
                                     (int)((char*) && yyc_exemplar_label_value - (char*) && yyc_init),
                                     (int)((char*) && yyc_value - (char*) && yyc_init),
                                     (int)((char*) && yyc_timestamp - (char*) && yyc_init),
                                     (int)((char*) && yyc_exemplar_value - (char*) && yyc_init),
                                     (int)((char*) && yyc_exemplar_timestamp - (char*) && yyc_init)};
    static const unsigned char yybm_init[256] = {
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 0,  0,  0,  0,  0,  0,  0,  0,  0,  128, 0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 0, 0,  0,  0,  0,  0,  64, 64, 64, 64, 64,  64, 64, 64, 64,
        64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 0,  0,  0,  0,  64, 0, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,  64, 64, 64, 64,
        64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,   0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,   0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,   0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,   0};
    static const unsigned char yybm_comment[256] = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0};
    static const unsigned char yybm_meta_name[256] = {
        0, 0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 0, 0, 0, 0,
        0, 0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 0, 0, 0, 0, 0,
        0, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 0, 0, 0, 0, 128,
        0, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 0, 0, 0, 0, 0,
        0, 0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 0, 0, 0, 0,
        0, 0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 0, 0, 0, 0,
        0, 0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 0, 0, 0, 0,
        0, 0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 0, 0, 0, 0};
    static const unsigned char yybm_meta_text_with_leading_spaces[256] = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0};
    static const unsigned char yybm_exemplar_labels[256] = {
        0, 0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 0, 0, 0, 0,
        0, 0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 0,   0, 0, 0, 0, 0,
        0, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 0, 0, 0, 0, 128,
        0, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 0, 0, 0, 0, 0,
        0, 0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 0, 0, 0, 0,
        0, 0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 0, 0, 0, 0,
        0, 0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 0, 0, 0, 0,
        0, 0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 0, 0, 0, 0};
    static const unsigned char yybm_labels[256] = {
        0, 0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 0, 0, 0, 0,
        0, 0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 0,   0, 0, 0, 0, 0,
        0, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 0, 0, 0, 0, 128,
        0, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 0, 0, 0, 0, 0,
        0, 0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 0, 0, 0, 0,
        0, 0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 0, 0, 0, 0,
        0, 0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 0, 0, 0, 0,
        0, 0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 0, 0, 0, 0};
    static const unsigned char yybm_value[256] = {
        128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 0,   128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128,
        128, 128, 128, 0,   128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128,
        128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128,
        128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128,
        128, 128, 128, 128, 128, 128, 128, 0,   128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128,
        128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128,
        128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128,
        128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128,
        128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128};
    static const unsigned char yybm_timestamp[256] = {
        128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 0,   128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128,
        128, 128, 128, 0,   128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128,
        128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128,
        128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128,
        128, 128, 128, 128, 128, 128, 128, 0,   128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128,
        128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128,
        128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128,
        128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128,
        128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128};
    static const unsigned char yybm_exemplar_value[256] = {
        128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 0,   128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128,
        128, 128, 128, 0,   128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128,
        128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128,
        128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128,
        128, 128, 128, 128, 128, 128, 128, 0,   128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128,
        128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128,
        128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128,
        128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128,
        128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128};
    static const unsigned char yybm_exemplar_timestamp[256] = {
        128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 0,   128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128,
        128, 128, 128, 0,   128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128,
        128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128,
        128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128,
        128, 128, 128, 128, 128, 128, 128, 0,   128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128,
        128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128,
        128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128,
        128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128,
        128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128};
    goto*((char*) && yyc_init + yyctable[condition_]);
  /* *********************************** */
  yyc_init:
    marker_ptr_ = cursor_ptr_;
    if ((limit_ptr_ - cursor_ptr_) < 2) {
      if (limit_ptr_ == cursor_ptr_) {
        return Token::kEOF;
      }
    }
    yych = *cursor_ptr_;
    {
      static const int yytarget[256] = {(int)((char*) && yy2 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy3 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy4 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy5 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy5 - (char*) && yy1),
                                        (int)((char*) && yy5 - (char*) && yy1), (int)((char*) && yy5 - (char*) && yy1), (int)((char*) && yy5 - (char*) && yy1),
                                        (int)((char*) && yy5 - (char*) && yy1), (int)((char*) && yy5 - (char*) && yy1), (int)((char*) && yy5 - (char*) && yy1),
                                        (int)((char*) && yy5 - (char*) && yy1), (int)((char*) && yy5 - (char*) && yy1), (int)((char*) && yy5 - (char*) && yy1),
                                        (int)((char*) && yy5 - (char*) && yy1), (int)((char*) && yy5 - (char*) && yy1), (int)((char*) && yy5 - (char*) && yy1),
                                        (int)((char*) && yy5 - (char*) && yy1), (int)((char*) && yy5 - (char*) && yy1), (int)((char*) && yy5 - (char*) && yy1),
                                        (int)((char*) && yy5 - (char*) && yy1), (int)((char*) && yy5 - (char*) && yy1), (int)((char*) && yy5 - (char*) && yy1),
                                        (int)((char*) && yy5 - (char*) && yy1), (int)((char*) && yy5 - (char*) && yy1), (int)((char*) && yy5 - (char*) && yy1),
                                        (int)((char*) && yy5 - (char*) && yy1), (int)((char*) && yy5 - (char*) && yy1), (int)((char*) && yy5 - (char*) && yy1),
                                        (int)((char*) && yy5 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy5 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy5 - (char*) && yy1), (int)((char*) && yy5 - (char*) && yy1),
                                        (int)((char*) && yy5 - (char*) && yy1), (int)((char*) && yy5 - (char*) && yy1), (int)((char*) && yy5 - (char*) && yy1),
                                        (int)((char*) && yy5 - (char*) && yy1), (int)((char*) && yy5 - (char*) && yy1), (int)((char*) && yy5 - (char*) && yy1),
                                        (int)((char*) && yy5 - (char*) && yy1), (int)((char*) && yy5 - (char*) && yy1), (int)((char*) && yy5 - (char*) && yy1),
                                        (int)((char*) && yy5 - (char*) && yy1), (int)((char*) && yy5 - (char*) && yy1), (int)((char*) && yy5 - (char*) && yy1),
                                        (int)((char*) && yy5 - (char*) && yy1), (int)((char*) && yy5 - (char*) && yy1), (int)((char*) && yy5 - (char*) && yy1),
                                        (int)((char*) && yy5 - (char*) && yy1), (int)((char*) && yy5 - (char*) && yy1), (int)((char*) && yy5 - (char*) && yy1),
                                        (int)((char*) && yy5 - (char*) && yy1), (int)((char*) && yy5 - (char*) && yy1), (int)((char*) && yy5 - (char*) && yy1),
                                        (int)((char*) && yy5 - (char*) && yy1), (int)((char*) && yy5 - (char*) && yy1), (int)((char*) && yy5 - (char*) && yy1),
                                        (int)((char*) && yy6 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1)};
      goto*((char*) && yy1 + yytarget[yych]);
    }
  yy1: { return Token::kInvalid; }
  yy2:
    ++cursor_ptr_;
    {
      return Token::kEOF;
    }
  yy3:
    ++cursor_ptr_;
    {
      return Token::kLinebreak;
    }
  yy4:
    yych = *++cursor_ptr_;
    if (yybm_init[0 + yych] & 128)
      goto yy7;
    cursor_ptr_ = marker_ptr_;
    goto yy1;
  yy5:
    ++cursor_ptr_;
    if (limit_ptr_ <= cursor_ptr_) {
      if (limit_ptr_ == cursor_ptr_) {
        return Token::kEOF;
      }
    }
    yych = *cursor_ptr_;
    if (yybm_init[0 + yych] & 64)
      goto yy5;
    condition_ = yycvalue;
    {
      return Token::kMetricName;
    }
  yy6:
    ++cursor_ptr_;
    condition_ = yyclabels;
    {
      return Token::kBraceOpen;
    }
  yy7:
    ++cursor_ptr_;
    if (limit_ptr_ <= cursor_ptr_) {
      if (limit_ptr_ == cursor_ptr_) {
        return Token::kEOF;
      }
    }
    yych = *cursor_ptr_;
    if (yybm_init[0 + yych] & 128)
      goto yy7;
    condition_ = yyccomment;
    {
      token_ptr_ = cursor_ptr_;
    }
  /* *********************************** */
  yyc_comment:
    marker_ptr_ = cursor_ptr_;
    if ((limit_ptr_ - cursor_ptr_) < 5) {
      if (limit_ptr_ == cursor_ptr_) {
        return Token::kEOF;
      }
    }
    yych = *cursor_ptr_;
    if (yych <= 'H') {
      if (yych == 'E')
        goto yy10;
      if (yych >= 'H')
        goto yy12;
    } else {
      if (yych <= 'S')
        goto yy9;
      if (yych <= 'T')
        goto yy13;
      if (yych <= 'U')
        goto yy14;
    }
  yy9:
    condition_ = yycinit;
    {
      return Token::kInvalid;
    }
  yy10:
    yych = *++cursor_ptr_;
    if (yych == 'O')
      goto yy15;
  yy11:
    cursor_ptr_ = marker_ptr_;
    goto yy9;
  yy12:
    yych = *++cursor_ptr_;
    if (yych == 'E')
      goto yy16;
    goto yy11;
  yy13:
    yych = *++cursor_ptr_;
    if (yych == 'Y')
      goto yy17;
    goto yy11;
  yy14:
    yych = *++cursor_ptr_;
    if (yych == 'N')
      goto yy18;
    goto yy11;
  yy15:
    yych = *++cursor_ptr_;
    if (yych == 'F')
      goto yy19;
    goto yy11;
  yy16:
    yych = *++cursor_ptr_;
    if (yych == 'L')
      goto yy21;
    goto yy11;
  yy17:
    yych = *++cursor_ptr_;
    if (yych == 'P')
      goto yy22;
    goto yy11;
  yy18:
    yych = *++cursor_ptr_;
    if (yych == 'I')
      goto yy23;
    goto yy11;
  yy19:
    yych = *++cursor_ptr_;
    if (yych == '\n')
      goto yy24;
  yy20:
    condition_ = yycinit;
    {
      return Token::kEOFWord;
    }
  yy21:
    yych = *++cursor_ptr_;
    if (yych == 'P')
      goto yy25;
    goto yy11;
  yy22:
    yych = *++cursor_ptr_;
    if (yych == 'E')
      goto yy26;
    goto yy11;
  yy23:
    yych = *++cursor_ptr_;
    if (yych == 'T')
      goto yy27;
    goto yy11;
  yy24:
    ++cursor_ptr_;
    goto yy20;
  yy25:
    yych = *++cursor_ptr_;
    if (yybm_comment[0 + yych] & 128)
      goto yy28;
    goto yy11;
  yy26:
    yych = *++cursor_ptr_;
    if (yych == ' ')
      goto yy29;
    goto yy11;
  yy27:
    yych = *++cursor_ptr_;
    if (yych == ' ')
      goto yy30;
    goto yy11;
  yy28:
    ++cursor_ptr_;
    if (limit_ptr_ <= cursor_ptr_) {
      if (limit_ptr_ == cursor_ptr_) {
        return Token::kEOF;
      }
    }
    yych = *cursor_ptr_;
    if (yybm_comment[0 + yych] & 128)
      goto yy28;
    condition_ = yycmeta_name;
    {
      return Token::kHelp;
    }
  yy29:
    ++cursor_ptr_;
    if (limit_ptr_ <= cursor_ptr_) {
      if (limit_ptr_ == cursor_ptr_) {
        return Token::kEOF;
      }
    }
    yych = *cursor_ptr_;
    if (yych == ' ')
      goto yy29;
    condition_ = yycmeta_name;
    {
      return Token::kType;
    }
  yy30:
    ++cursor_ptr_;
    if (limit_ptr_ <= cursor_ptr_) {
      if (limit_ptr_ == cursor_ptr_) {
        return Token::kEOF;
      }
    }
    yych = *cursor_ptr_;
    if (yych == ' ')
      goto yy30;
    condition_ = yycmeta_name;
    {
      return Token::kUnit;
    }
  /* *********************************** */
  yyc_meta_name:
    marker_ptr_ = cursor_ptr_;
    if (limit_ptr_ <= cursor_ptr_) {
      if (limit_ptr_ == cursor_ptr_) {
        return Token::kEOF;
      }
    }
    yych = *cursor_ptr_;
    {
      static const int yytarget[256] = {
          (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32),
          (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32),
          (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32),
          (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32),
          (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32),
          (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32),
          (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32),
          (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32),
          (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32),
          (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32),
          (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32),
          (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy33 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32),
          (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32),
          (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32),
          (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32),
          (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32),
          (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32),
          (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32),
          (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32),
          (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy34 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32),
          (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32),
          (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy34 - (char*) && yy32),
          (int)((char*) && yy34 - (char*) && yy32), (int)((char*) && yy34 - (char*) && yy32), (int)((char*) && yy34 - (char*) && yy32),
          (int)((char*) && yy34 - (char*) && yy32), (int)((char*) && yy34 - (char*) && yy32), (int)((char*) && yy34 - (char*) && yy32),
          (int)((char*) && yy34 - (char*) && yy32), (int)((char*) && yy34 - (char*) && yy32), (int)((char*) && yy34 - (char*) && yy32),
          (int)((char*) && yy34 - (char*) && yy32), (int)((char*) && yy34 - (char*) && yy32), (int)((char*) && yy34 - (char*) && yy32),
          (int)((char*) && yy34 - (char*) && yy32), (int)((char*) && yy34 - (char*) && yy32), (int)((char*) && yy34 - (char*) && yy32),
          (int)((char*) && yy34 - (char*) && yy32), (int)((char*) && yy34 - (char*) && yy32), (int)((char*) && yy34 - (char*) && yy32),
          (int)((char*) && yy34 - (char*) && yy32), (int)((char*) && yy34 - (char*) && yy32), (int)((char*) && yy34 - (char*) && yy32),
          (int)((char*) && yy34 - (char*) && yy32), (int)((char*) && yy34 - (char*) && yy32), (int)((char*) && yy34 - (char*) && yy32),
          (int)((char*) && yy34 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32),
          (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy34 - (char*) && yy32),
          (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy34 - (char*) && yy32), (int)((char*) && yy34 - (char*) && yy32),
          (int)((char*) && yy34 - (char*) && yy32), (int)((char*) && yy34 - (char*) && yy32), (int)((char*) && yy34 - (char*) && yy32),
          (int)((char*) && yy34 - (char*) && yy32), (int)((char*) && yy34 - (char*) && yy32), (int)((char*) && yy34 - (char*) && yy32),
          (int)((char*) && yy34 - (char*) && yy32), (int)((char*) && yy34 - (char*) && yy32), (int)((char*) && yy34 - (char*) && yy32),
          (int)((char*) && yy34 - (char*) && yy32), (int)((char*) && yy34 - (char*) && yy32), (int)((char*) && yy34 - (char*) && yy32),
          (int)((char*) && yy34 - (char*) && yy32), (int)((char*) && yy34 - (char*) && yy32), (int)((char*) && yy34 - (char*) && yy32),
          (int)((char*) && yy34 - (char*) && yy32), (int)((char*) && yy34 - (char*) && yy32), (int)((char*) && yy34 - (char*) && yy32),
          (int)((char*) && yy34 - (char*) && yy32), (int)((char*) && yy34 - (char*) && yy32), (int)((char*) && yy34 - (char*) && yy32),
          (int)((char*) && yy34 - (char*) && yy32), (int)((char*) && yy34 - (char*) && yy32), (int)((char*) && yy34 - (char*) && yy32),
          (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32),
          (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32),
          (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32),
          (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32),
          (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32),
          (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32),
          (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32),
          (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32),
          (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32),
          (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32),
          (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32),
          (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32),
          (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32),
          (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32),
          (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32),
          (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32),
          (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32),
          (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32),
          (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32),
          (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32),
          (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32),
          (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32),
          (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32),
          (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32),
          (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32),
          (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32),
          (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32),
          (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32),
          (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32),
          (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32),
          (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32),
          (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32),
          (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32),
          (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32),
          (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32),
          (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32),
          (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32),
          (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32),
          (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32),
          (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32),
          (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32),
          (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32),
          (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32),
          (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32), (int)((char*) && yy32 - (char*) && yy32),
          (int)((char*) && yy32 - (char*) && yy32)};
      goto*((char*) && yy32 + yytarget[yych]);
    }
  yy32: { return Token::kInvalid; }
  yy33:
    ++cursor_ptr_;
    condition_ = yycmeta_text_with_leading_spaces;
    {
      return consume_escaped_string(Token::kMetricName);
    }
  yy34:
    ++cursor_ptr_;
    if (limit_ptr_ <= cursor_ptr_) {
      if (limit_ptr_ == cursor_ptr_) {
        return Token::kEOF;
      }
    }
    yych = *cursor_ptr_;
    if (yybm_meta_name[0 + yych] & 128)
      goto yy34;
    if (yych == ' ')
      goto yy35;
    cursor_ptr_ = marker_ptr_;
    goto yy32;
  yy35:
    ++cursor_ptr_;
    condition_ = yycmeta_text_with_leading_spaces;
    {
      --cursor_ptr_;
      return Token::kMetricName;
    }
  /* *********************************** */
  yyc_meta_text_with_leading_spaces:
    goto yy36;
  yy37:
    ++cursor_ptr_;
  yy36:
    if (limit_ptr_ <= cursor_ptr_) {
      if (limit_ptr_ == cursor_ptr_) {
        return Token::kEOF;
      }
    }
    yych = *cursor_ptr_;
    if (yybm_meta_text_with_leading_spaces[0 + yych] & 128)
      goto yy37;
    condition_ = yycinit;
    {
      token_ptr_ = cursor_ptr_;
      return consume_comment(Token::kText);
    }
  /* *********************************** */
  yyc_exemplar_labels:
    if (limit_ptr_ <= cursor_ptr_) {
      if (limit_ptr_ == cursor_ptr_) {
        return Token::kEOF;
      }
    }
    yych = *cursor_ptr_;
    {
      static const int yytarget[256] = {
          (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39),
          (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39),
          (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39),
          (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39),
          (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39),
          (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39),
          (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39),
          (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39),
          (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39),
          (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39),
          (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39),
          (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy40 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39),
          (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39),
          (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39),
          (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy41 - (char*) && yy39),
          (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39),
          (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39),
          (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39),
          (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39),
          (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39),
          (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy42 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39),
          (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy43 - (char*) && yy39),
          (int)((char*) && yy43 - (char*) && yy39), (int)((char*) && yy43 - (char*) && yy39), (int)((char*) && yy43 - (char*) && yy39),
          (int)((char*) && yy43 - (char*) && yy39), (int)((char*) && yy43 - (char*) && yy39), (int)((char*) && yy43 - (char*) && yy39),
          (int)((char*) && yy43 - (char*) && yy39), (int)((char*) && yy43 - (char*) && yy39), (int)((char*) && yy43 - (char*) && yy39),
          (int)((char*) && yy43 - (char*) && yy39), (int)((char*) && yy43 - (char*) && yy39), (int)((char*) && yy43 - (char*) && yy39),
          (int)((char*) && yy43 - (char*) && yy39), (int)((char*) && yy43 - (char*) && yy39), (int)((char*) && yy43 - (char*) && yy39),
          (int)((char*) && yy43 - (char*) && yy39), (int)((char*) && yy43 - (char*) && yy39), (int)((char*) && yy43 - (char*) && yy39),
          (int)((char*) && yy43 - (char*) && yy39), (int)((char*) && yy43 - (char*) && yy39), (int)((char*) && yy43 - (char*) && yy39),
          (int)((char*) && yy43 - (char*) && yy39), (int)((char*) && yy43 - (char*) && yy39), (int)((char*) && yy43 - (char*) && yy39),
          (int)((char*) && yy43 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39),
          (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy43 - (char*) && yy39),
          (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy43 - (char*) && yy39), (int)((char*) && yy43 - (char*) && yy39),
          (int)((char*) && yy43 - (char*) && yy39), (int)((char*) && yy43 - (char*) && yy39), (int)((char*) && yy43 - (char*) && yy39),
          (int)((char*) && yy43 - (char*) && yy39), (int)((char*) && yy43 - (char*) && yy39), (int)((char*) && yy43 - (char*) && yy39),
          (int)((char*) && yy43 - (char*) && yy39), (int)((char*) && yy43 - (char*) && yy39), (int)((char*) && yy43 - (char*) && yy39),
          (int)((char*) && yy43 - (char*) && yy39), (int)((char*) && yy43 - (char*) && yy39), (int)((char*) && yy43 - (char*) && yy39),
          (int)((char*) && yy43 - (char*) && yy39), (int)((char*) && yy43 - (char*) && yy39), (int)((char*) && yy43 - (char*) && yy39),
          (int)((char*) && yy43 - (char*) && yy39), (int)((char*) && yy43 - (char*) && yy39), (int)((char*) && yy43 - (char*) && yy39),
          (int)((char*) && yy43 - (char*) && yy39), (int)((char*) && yy43 - (char*) && yy39), (int)((char*) && yy43 - (char*) && yy39),
          (int)((char*) && yy43 - (char*) && yy39), (int)((char*) && yy43 - (char*) && yy39), (int)((char*) && yy43 - (char*) && yy39),
          (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy44 - (char*) && yy39),
          (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39),
          (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39),
          (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39),
          (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39),
          (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39),
          (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39),
          (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39),
          (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39),
          (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39),
          (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39),
          (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39),
          (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39),
          (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39),
          (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39),
          (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39),
          (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39),
          (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39),
          (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39),
          (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39),
          (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39),
          (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39),
          (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39),
          (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39),
          (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39),
          (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39),
          (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39),
          (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39),
          (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39),
          (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39),
          (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39),
          (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39),
          (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39),
          (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39),
          (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39),
          (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39),
          (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39),
          (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39),
          (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39),
          (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39),
          (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39),
          (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39),
          (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39),
          (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39), (int)((char*) && yy39 - (char*) && yy39),
          (int)((char*) && yy39 - (char*) && yy39)};
      goto*((char*) && yy39 + yytarget[yych]);
    }
  yy39: { return Token::kInvalid; }
  yy40:
    ++cursor_ptr_;
    {
      return consume_escaped_string(Token::kQuotedString);
    }
  yy41:
    ++cursor_ptr_;
    {
      return Token::kComma;
    }
  yy42:
    ++cursor_ptr_;
    condition_ = yycexemplar_label_value;
    {
      return Token::kEqual;
    }
  yy43:
    ++cursor_ptr_;
    if (limit_ptr_ <= cursor_ptr_) {
      if (limit_ptr_ == cursor_ptr_) {
        return Token::kEOF;
      }
    }
    yych = *cursor_ptr_;
    if (yybm_exemplar_labels[0 + yych] & 128)
      goto yy43;
    {
      return Token::kLabelName;
    }
  yy44:
    ++cursor_ptr_;
    condition_ = yycexemplar_value;
    {
      return Token::kBraceClose;
    }
  /* *********************************** */
  yyc_labels:
    if (limit_ptr_ <= cursor_ptr_) {
      if (limit_ptr_ == cursor_ptr_) {
        return Token::kEOF;
      }
    }
    yych = *cursor_ptr_;
    {
      static const int yytarget[256] = {
          (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46),
          (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46),
          (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46),
          (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46),
          (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46),
          (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46),
          (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46),
          (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46),
          (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46),
          (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46),
          (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46),
          (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy47 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46),
          (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46),
          (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46),
          (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy48 - (char*) && yy46),
          (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46),
          (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46),
          (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46),
          (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46),
          (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46),
          (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy49 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46),
          (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy50 - (char*) && yy46),
          (int)((char*) && yy50 - (char*) && yy46), (int)((char*) && yy50 - (char*) && yy46), (int)((char*) && yy50 - (char*) && yy46),
          (int)((char*) && yy50 - (char*) && yy46), (int)((char*) && yy50 - (char*) && yy46), (int)((char*) && yy50 - (char*) && yy46),
          (int)((char*) && yy50 - (char*) && yy46), (int)((char*) && yy50 - (char*) && yy46), (int)((char*) && yy50 - (char*) && yy46),
          (int)((char*) && yy50 - (char*) && yy46), (int)((char*) && yy50 - (char*) && yy46), (int)((char*) && yy50 - (char*) && yy46),
          (int)((char*) && yy50 - (char*) && yy46), (int)((char*) && yy50 - (char*) && yy46), (int)((char*) && yy50 - (char*) && yy46),
          (int)((char*) && yy50 - (char*) && yy46), (int)((char*) && yy50 - (char*) && yy46), (int)((char*) && yy50 - (char*) && yy46),
          (int)((char*) && yy50 - (char*) && yy46), (int)((char*) && yy50 - (char*) && yy46), (int)((char*) && yy50 - (char*) && yy46),
          (int)((char*) && yy50 - (char*) && yy46), (int)((char*) && yy50 - (char*) && yy46), (int)((char*) && yy50 - (char*) && yy46),
          (int)((char*) && yy50 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46),
          (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy50 - (char*) && yy46),
          (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy50 - (char*) && yy46), (int)((char*) && yy50 - (char*) && yy46),
          (int)((char*) && yy50 - (char*) && yy46), (int)((char*) && yy50 - (char*) && yy46), (int)((char*) && yy50 - (char*) && yy46),
          (int)((char*) && yy50 - (char*) && yy46), (int)((char*) && yy50 - (char*) && yy46), (int)((char*) && yy50 - (char*) && yy46),
          (int)((char*) && yy50 - (char*) && yy46), (int)((char*) && yy50 - (char*) && yy46), (int)((char*) && yy50 - (char*) && yy46),
          (int)((char*) && yy50 - (char*) && yy46), (int)((char*) && yy50 - (char*) && yy46), (int)((char*) && yy50 - (char*) && yy46),
          (int)((char*) && yy50 - (char*) && yy46), (int)((char*) && yy50 - (char*) && yy46), (int)((char*) && yy50 - (char*) && yy46),
          (int)((char*) && yy50 - (char*) && yy46), (int)((char*) && yy50 - (char*) && yy46), (int)((char*) && yy50 - (char*) && yy46),
          (int)((char*) && yy50 - (char*) && yy46), (int)((char*) && yy50 - (char*) && yy46), (int)((char*) && yy50 - (char*) && yy46),
          (int)((char*) && yy50 - (char*) && yy46), (int)((char*) && yy50 - (char*) && yy46), (int)((char*) && yy50 - (char*) && yy46),
          (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy51 - (char*) && yy46),
          (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46),
          (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46),
          (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46),
          (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46),
          (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46),
          (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46),
          (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46),
          (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46),
          (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46),
          (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46),
          (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46),
          (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46),
          (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46),
          (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46),
          (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46),
          (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46),
          (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46),
          (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46),
          (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46),
          (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46),
          (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46),
          (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46),
          (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46),
          (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46),
          (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46),
          (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46),
          (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46),
          (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46),
          (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46),
          (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46),
          (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46),
          (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46),
          (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46),
          (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46),
          (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46),
          (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46),
          (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46),
          (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46),
          (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46),
          (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46),
          (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46),
          (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46),
          (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46), (int)((char*) && yy46 - (char*) && yy46),
          (int)((char*) && yy46 - (char*) && yy46)};
      goto*((char*) && yy46 + yytarget[yych]);
    }
  yy46: { return Token::kInvalid; }
  yy47:
    ++cursor_ptr_;
    {
      return consume_escaped_string(Token::kQuotedString);
    }
  yy48:
    ++cursor_ptr_;
    {
      return Token::kComma;
    }
  yy49:
    ++cursor_ptr_;
    condition_ = yyclabel_value;
    {
      return Token::kEqual;
    }
  yy50:
    ++cursor_ptr_;
    if (limit_ptr_ <= cursor_ptr_) {
      if (limit_ptr_ == cursor_ptr_) {
        return Token::kEOF;
      }
    }
    yych = *cursor_ptr_;
    if (yybm_labels[0 + yych] & 128)
      goto yy50;
    {
      return Token::kLabelName;
    }
  yy51:
    ++cursor_ptr_;
    condition_ = yycvalue;
    {
      return Token::kBraceClose;
    }
  /* *********************************** */
  yyc_label_value:
    if (limit_ptr_ <= cursor_ptr_) {
      if (limit_ptr_ == cursor_ptr_) {
        return Token::kEOF;
      }
    }
    yych = *cursor_ptr_;
    if (yych == '"')
      goto yy53;
    {
      return Token::kInvalid;
    }
  yy53:
    ++cursor_ptr_;
    condition_ = yyclabels;
    {
      return consume_escaped_string(Token::kLabelValue);
    }
  /* *********************************** */
  yyc_exemplar_label_value:
    if (limit_ptr_ <= cursor_ptr_) {
      if (limit_ptr_ == cursor_ptr_) {
        return Token::kEOF;
      }
    }
    yych = *cursor_ptr_;
    if (yych == '"')
      goto yy55;
    {
      return Token::kInvalid;
    }
  yy55:
    ++cursor_ptr_;
    condition_ = yycexemplar_labels;
    {
      return consume_escaped_string(Token::kLabelValue);
    }
  /* *********************************** */
  yyc_value:
    marker_ptr_ = cursor_ptr_;
    if ((limit_ptr_ - cursor_ptr_) < 2) {
      if (limit_ptr_ == cursor_ptr_) {
        return Token::kEOF;
      }
    }
    yych = *cursor_ptr_;
    if (yych == ' ')
      goto yy58;
    if (yych == '{')
      goto yy59;
  yy57: { return Token::kInvalid; }
  yy58:
    yych = *++cursor_ptr_;
    if (yybm_value[0 + yych] & 128)
      goto yy60;
    cursor_ptr_ = marker_ptr_;
    goto yy57;
  yy59:
    ++cursor_ptr_;
    condition_ = yyclabels;
    {
      return Token::kBraceOpen;
    }
  yy60:
    ++cursor_ptr_;
    if (limit_ptr_ <= cursor_ptr_) {
      if (limit_ptr_ == cursor_ptr_) {
        return Token::kEOF;
      }
    }
    yych = *cursor_ptr_;
    if (yybm_value[0 + yych] & 128)
      goto yy60;
    condition_ = yyctimestamp;
    {
      ++token_ptr_;
      return Token::kValue;
    }
  /* *********************************** */
  yyc_timestamp:
    marker_ptr_ = cursor_ptr_;
    if ((limit_ptr_ - cursor_ptr_) < 4) {
      if (limit_ptr_ == cursor_ptr_) {
        return Token::kEOF;
      }
    }
    yych = *cursor_ptr_;
    if (yych == '\n')
      goto yy63;
    if (yych == ' ')
      goto yy64;
  yy62: { return Token::kInvalid; }
  yy63:
    ++cursor_ptr_;
    condition_ = yycinit;
    {
      return Token::kLinebreak;
    }
  yy64:
    yych = *++cursor_ptr_;
    {
      static const int yytarget[256] = {
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy65 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy65 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy69 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy65 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65), (int)((char*) && yy66 - (char*) && yy65),
          (int)((char*) && yy66 - (char*) && yy65)};
      goto*((char*) && yy65 + yytarget[yych]);
    }
  yy65:
    cursor_ptr_ = marker_ptr_;
    if (yyaccept == 0)
      goto yy62;
    else
      goto yy68;
  yy66:
    ++cursor_ptr_;
    if (limit_ptr_ <= cursor_ptr_) {
      if (limit_ptr_ == cursor_ptr_) {
        return Token::kEOF;
      }
    }
    yych = *cursor_ptr_;
  yy67:
    if (yybm_timestamp[0 + yych] & 128)
      goto yy66;
  yy68: {
    ++token_ptr_;
    return Token::kTimestamp;
  }
  yy69:
    yyaccept = 1;
    yych = *(marker_ptr_ = ++cursor_ptr_);
    if (yych != ' ')
      goto yy67;
    yych = *++cursor_ptr_;
    if (yych != '{')
      goto yy65;
    ++cursor_ptr_;
    condition_ = yycexemplar_labels;
    {
      return Token::kExemplar;
    }
  /* *********************************** */
  yyc_exemplar_value:
    marker_ptr_ = cursor_ptr_;
    if ((limit_ptr_ - cursor_ptr_) < 2) {
      if (limit_ptr_ == cursor_ptr_) {
        return Token::kEOF;
      }
    }
    yych = *cursor_ptr_;
    if (yych == ' ')
      goto yy72;
  yy71: { return Token::kInvalid; }
  yy72:
    yych = *++cursor_ptr_;
    if (yybm_exemplar_value[0 + yych] & 128)
      goto yy73;
    cursor_ptr_ = marker_ptr_;
    goto yy71;
  yy73:
    ++cursor_ptr_;
    if (limit_ptr_ <= cursor_ptr_) {
      if (limit_ptr_ == cursor_ptr_) {
        return Token::kEOF;
      }
    }
    yych = *cursor_ptr_;
    if (yybm_exemplar_value[0 + yych] & 128)
      goto yy73;
    condition_ = yycexemplar_timestamp;
    {
      ++token_ptr_;
      return Token::kValue;
    }
  /* *********************************** */
  yyc_exemplar_timestamp:
    marker_ptr_ = cursor_ptr_;
    if ((limit_ptr_ - cursor_ptr_) < 2) {
      if (limit_ptr_ == cursor_ptr_) {
        return Token::kEOF;
      }
    }
    yych = *cursor_ptr_;
    if (yych == '\n')
      goto yy76;
    if (yych == ' ')
      goto yy77;
  yy75: { return Token::kInvalid; }
  yy76:
    ++cursor_ptr_;
    condition_ = yycinit;
    {
      return Token::kLinebreak;
    }
  yy77:
    yych = *++cursor_ptr_;
    if (yybm_exemplar_timestamp[0 + yych] & 128)
      goto yy78;
    cursor_ptr_ = marker_ptr_;
    goto yy75;
  yy78:
    ++cursor_ptr_;
    if (limit_ptr_ <= cursor_ptr_) {
      if (limit_ptr_ == cursor_ptr_) {
        return Token::kEOF;
      }
    }
    yych = *cursor_ptr_;
    if (yybm_exemplar_timestamp[0 + yych] & 128)
      goto yy78;
    {
      ++token_ptr_;
      return Token::kTimestamp;
    }
  }
}
// NOLINTEND

}  // namespace PromPP::Prometheus::textparse::OpenMetrics
