// Code generated by "enumer -type=TypeTask"; DO NOT EDIT.

package relabeler

import (
	"fmt"
	"strings"
)

const _TypeTaskName = "UnknownTaskHeadInputRelabelingHeadAppendRelabelerSeriesWalCommitWalFlushWalWriteHeadCopyAddedSeriesDistributorOutputRelabelingDistributorUpdateRelabelerStateHeadLSSAllocatedMemoryLSSHeadStatusChunkQuerierSelectLSSQueryChunkQuerierLabelValuesChunkQuerierLabelNamesQuerierSelectInstantLSSQueryQuerierSelectRangeLSSQueryQuerierLabelValuesQuerierLabelNamesdataStorageMarkerDataStorageAppendInnerSeriesDataStorageMergeOutOfOrderChunksHeadDataStorageAllocatedMemoryDataStorageHeadStatusChunkQuerierSelectDataStorageQueryQuerierSelectInstantDataStorageQueryQuerierSelectRangeDataStorageQueryBlockWriteHeadUpdateRelabelerState"

var _TypeTaskIndex = [...]uint16{0, 11, 30, 55, 64, 72, 80, 99, 126, 157, 179, 192, 218, 241, 263, 291, 317, 335, 352, 369, 397, 429, 459, 480, 514, 550, 584, 594, 618}

const _TypeTaskLowerName = "unknowntaskheadinputrelabelingheadappendrelabelerserieswalcommitwalflushwalwriteheadcopyaddedseriesdistributoroutputrelabelingdistributorupdaterelabelerstateheadlssallocatedmemorylssheadstatuschunkquerierselectlssquerychunkquerierlabelvalueschunkquerierlabelnamesquerierselectinstantlssqueryquerierselectrangelssqueryquerierlabelvaluesquerierlabelnamesdatastoragemarkerdatastorageappendinnerseriesdatastoragemergeoutoforderchunksheaddatastorageallocatedmemorydatastorageheadstatuschunkquerierselectdatastoragequeryquerierselectinstantdatastoragequeryquerierselectrangedatastoragequeryblockwriteheadupdaterelabelerstate"

func (i TypeTask) String() string {
	if i >= TypeTask(len(_TypeTaskIndex)-1) {
		return fmt.Sprintf("TypeTask(%d)", i)
	}
	return _TypeTaskName[_TypeTaskIndex[i]:_TypeTaskIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _TypeTaskNoOp() {
	var x [1]struct{}
	_ = x[UnknownTask-(0)]
	_ = x[HeadInputRelabeling-(1)]
	_ = x[HeadAppendRelabelerSeries-(2)]
	_ = x[WalCommit-(3)]
	_ = x[WalFlush-(4)]
	_ = x[WalWrite-(5)]
	_ = x[HeadCopyAddedSeries-(6)]
	_ = x[DistributorOutputRelabeling-(7)]
	_ = x[DistributorUpdateRelabelerState-(8)]
	_ = x[HeadLSSAllocatedMemory-(9)]
	_ = x[LSSHeadStatus-(10)]
	_ = x[ChunkQuerierSelectLSSQuery-(11)]
	_ = x[ChunkQuerierLabelValues-(12)]
	_ = x[ChunkQuerierLabelNames-(13)]
	_ = x[QuerierSelectInstantLSSQuery-(14)]
	_ = x[QuerierSelectRangeLSSQuery-(15)]
	_ = x[QuerierLabelValues-(16)]
	_ = x[QuerierLabelNames-(17)]
	_ = x[dataStorageMarker-(18)]
	_ = x[DataStorageAppendInnerSeries-(19)]
	_ = x[DataStorageMergeOutOfOrderChunks-(20)]
	_ = x[HeadDataStorageAllocatedMemory-(21)]
	_ = x[DataStorageHeadStatus-(22)]
	_ = x[ChunkQuerierSelectDataStorageQuery-(23)]
	_ = x[QuerierSelectInstantDataStorageQuery-(24)]
	_ = x[QuerierSelectRangeDataStorageQuery-(25)]
	_ = x[BlockWrite-(26)]
	_ = x[HeadUpdateRelabelerState-(27)]
}

var _TypeTaskValues = []TypeTask{UnknownTask, HeadInputRelabeling, HeadAppendRelabelerSeries, WalCommit, WalFlush, WalWrite, HeadCopyAddedSeries, DistributorOutputRelabeling, DistributorUpdateRelabelerState, HeadLSSAllocatedMemory, LSSHeadStatus, ChunkQuerierSelectLSSQuery, ChunkQuerierLabelValues, ChunkQuerierLabelNames, QuerierSelectInstantLSSQuery, QuerierSelectRangeLSSQuery, QuerierLabelValues, QuerierLabelNames, dataStorageMarker, DataStorageAppendInnerSeries, DataStorageMergeOutOfOrderChunks, HeadDataStorageAllocatedMemory, DataStorageHeadStatus, ChunkQuerierSelectDataStorageQuery, QuerierSelectInstantDataStorageQuery, QuerierSelectRangeDataStorageQuery, BlockWrite, HeadUpdateRelabelerState}

var _TypeTaskNameToValueMap = map[string]TypeTask{
	_TypeTaskName[0:11]:         UnknownTask,
	_TypeTaskLowerName[0:11]:    UnknownTask,
	_TypeTaskName[11:30]:        HeadInputRelabeling,
	_TypeTaskLowerName[11:30]:   HeadInputRelabeling,
	_TypeTaskName[30:55]:        HeadAppendRelabelerSeries,
	_TypeTaskLowerName[30:55]:   HeadAppendRelabelerSeries,
	_TypeTaskName[55:64]:        WalCommit,
	_TypeTaskLowerName[55:64]:   WalCommit,
	_TypeTaskName[64:72]:        WalFlush,
	_TypeTaskLowerName[64:72]:   WalFlush,
	_TypeTaskName[72:80]:        WalWrite,
	_TypeTaskLowerName[72:80]:   WalWrite,
	_TypeTaskName[80:99]:        HeadCopyAddedSeries,
	_TypeTaskLowerName[80:99]:   HeadCopyAddedSeries,
	_TypeTaskName[99:126]:       DistributorOutputRelabeling,
	_TypeTaskLowerName[99:126]:  DistributorOutputRelabeling,
	_TypeTaskName[126:157]:      DistributorUpdateRelabelerState,
	_TypeTaskLowerName[126:157]: DistributorUpdateRelabelerState,
	_TypeTaskName[157:179]:      HeadLSSAllocatedMemory,
	_TypeTaskLowerName[157:179]: HeadLSSAllocatedMemory,
	_TypeTaskName[179:192]:      LSSHeadStatus,
	_TypeTaskLowerName[179:192]: LSSHeadStatus,
	_TypeTaskName[192:218]:      ChunkQuerierSelectLSSQuery,
	_TypeTaskLowerName[192:218]: ChunkQuerierSelectLSSQuery,
	_TypeTaskName[218:241]:      ChunkQuerierLabelValues,
	_TypeTaskLowerName[218:241]: ChunkQuerierLabelValues,
	_TypeTaskName[241:263]:      ChunkQuerierLabelNames,
	_TypeTaskLowerName[241:263]: ChunkQuerierLabelNames,
	_TypeTaskName[263:291]:      QuerierSelectInstantLSSQuery,
	_TypeTaskLowerName[263:291]: QuerierSelectInstantLSSQuery,
	_TypeTaskName[291:317]:      QuerierSelectRangeLSSQuery,
	_TypeTaskLowerName[291:317]: QuerierSelectRangeLSSQuery,
	_TypeTaskName[317:335]:      QuerierLabelValues,
	_TypeTaskLowerName[317:335]: QuerierLabelValues,
	_TypeTaskName[335:352]:      QuerierLabelNames,
	_TypeTaskLowerName[335:352]: QuerierLabelNames,
	_TypeTaskName[352:369]:      dataStorageMarker,
	_TypeTaskLowerName[352:369]: dataStorageMarker,
	_TypeTaskName[369:397]:      DataStorageAppendInnerSeries,
	_TypeTaskLowerName[369:397]: DataStorageAppendInnerSeries,
	_TypeTaskName[397:429]:      DataStorageMergeOutOfOrderChunks,
	_TypeTaskLowerName[397:429]: DataStorageMergeOutOfOrderChunks,
	_TypeTaskName[429:459]:      HeadDataStorageAllocatedMemory,
	_TypeTaskLowerName[429:459]: HeadDataStorageAllocatedMemory,
	_TypeTaskName[459:480]:      DataStorageHeadStatus,
	_TypeTaskLowerName[459:480]: DataStorageHeadStatus,
	_TypeTaskName[480:514]:      ChunkQuerierSelectDataStorageQuery,
	_TypeTaskLowerName[480:514]: ChunkQuerierSelectDataStorageQuery,
	_TypeTaskName[514:550]:      QuerierSelectInstantDataStorageQuery,
	_TypeTaskLowerName[514:550]: QuerierSelectInstantDataStorageQuery,
	_TypeTaskName[550:584]:      QuerierSelectRangeDataStorageQuery,
	_TypeTaskLowerName[550:584]: QuerierSelectRangeDataStorageQuery,
	_TypeTaskName[584:594]:      BlockWrite,
	_TypeTaskLowerName[584:594]: BlockWrite,
	_TypeTaskName[594:618]:      HeadUpdateRelabelerState,
	_TypeTaskLowerName[594:618]: HeadUpdateRelabelerState,
}

var _TypeTaskNames = []string{
	_TypeTaskName[0:11],
	_TypeTaskName[11:30],
	_TypeTaskName[30:55],
	_TypeTaskName[55:64],
	_TypeTaskName[64:72],
	_TypeTaskName[72:80],
	_TypeTaskName[80:99],
	_TypeTaskName[99:126],
	_TypeTaskName[126:157],
	_TypeTaskName[157:179],
	_TypeTaskName[179:192],
	_TypeTaskName[192:218],
	_TypeTaskName[218:241],
	_TypeTaskName[241:263],
	_TypeTaskName[263:291],
	_TypeTaskName[291:317],
	_TypeTaskName[317:335],
	_TypeTaskName[335:352],
	_TypeTaskName[352:369],
	_TypeTaskName[369:397],
	_TypeTaskName[397:429],
	_TypeTaskName[429:459],
	_TypeTaskName[459:480],
	_TypeTaskName[480:514],
	_TypeTaskName[514:550],
	_TypeTaskName[550:584],
	_TypeTaskName[584:594],
	_TypeTaskName[594:618],
}

// TypeTaskString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func TypeTaskString(s string) (TypeTask, error) {
	if val, ok := _TypeTaskNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _TypeTaskNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to TypeTask values", s)
}

// TypeTaskValues returns all values of the enum
func TypeTaskValues() []TypeTask {
	return _TypeTaskValues
}

// TypeTaskStrings returns a slice of all String values of the enum
func TypeTaskStrings() []string {
	strs := make([]string, len(_TypeTaskNames))
	copy(strs, _TypeTaskNames)
	return strs
}

// IsATypeTask returns "true" if the value is listed in the enum definition. "false" otherwise
func (i TypeTask) IsATypeTask() bool {
	for _, v := range _TypeTaskValues {
		if i == v {
			return true
		}
	}
	return false
}
