// Code generated by "enumer -type=TypeTask"; DO NOT EDIT.

package relabeler

import (
	"fmt"
	"strings"
)

const _TypeTaskName = "UnknownHeadInputRelabelingHeadAppendRelabelerSeriesHeadUpdateRelabelerStateHeadAllocatedMemoryHeadStatusTypeHeadCopyAddedSeriesDataStorageAppendInnerSeriesDataStorageMergeOutOfOrderChunksBlockWriteWalCommitCommitToWalWalFlushWalDataStorageAddChunkQuerierSelectChunkQuerierLabelValuesChunkQuerierLabelNamesQuerierSelectInstantLSSQueryQuerierSelectInstantDataStorageQueryQuerierSelectRangeLSSQueryQuerierSelectRangeDataStorageQueryQuerierLabelValuesQuerierLabelNamesDistributorWriteMetricsDistributorOutputRelabelingDistributorUpdateRelabelerStateOther"

var _TypeTaskIndex = [...]uint16{0, 7, 26, 51, 75, 94, 108, 127, 155, 187, 197, 206, 217, 225, 242, 260, 283, 305, 333, 369, 395, 429, 447, 464, 487, 514, 545, 550}

const _TypeTaskLowerName = "unknownheadinputrelabelingheadappendrelabelerseriesheadupdaterelabelerstateheadallocatedmemoryheadstatustypeheadcopyaddedseriesdatastorageappendinnerseriesdatastoragemergeoutoforderchunksblockwritewalcommitcommittowalwalflushwaldatastorageaddchunkquerierselectchunkquerierlabelvalueschunkquerierlabelnamesquerierselectinstantlssqueryquerierselectinstantdatastoragequeryquerierselectrangelssqueryquerierselectrangedatastoragequeryquerierlabelvaluesquerierlabelnamesdistributorwritemetricsdistributoroutputrelabelingdistributorupdaterelabelerstateother"

func (i TypeTask) String() string {
	if i >= TypeTask(len(_TypeTaskIndex)-1) {
		return fmt.Sprintf("TypeTask(%d)", i)
	}
	return _TypeTaskName[_TypeTaskIndex[i]:_TypeTaskIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _TypeTaskNoOp() {
	var x [1]struct{}
	_ = x[Unknown-(0)]
	_ = x[HeadInputRelabeling-(1)]
	_ = x[HeadAppendRelabelerSeries-(2)]
	_ = x[HeadUpdateRelabelerState-(3)]
	_ = x[HeadAllocatedMemory-(4)]
	_ = x[HeadStatusType-(5)]
	_ = x[HeadCopyAddedSeries-(6)]
	_ = x[DataStorageAppendInnerSeries-(7)]
	_ = x[DataStorageMergeOutOfOrderChunks-(8)]
	_ = x[BlockWrite-(9)]
	_ = x[WalCommit-(10)]
	_ = x[CommitToWal-(11)]
	_ = x[WalFlush-(12)]
	_ = x[WalDataStorageAdd-(13)]
	_ = x[ChunkQuerierSelect-(14)]
	_ = x[ChunkQuerierLabelValues-(15)]
	_ = x[ChunkQuerierLabelNames-(16)]
	_ = x[QuerierSelectInstantLSSQuery-(17)]
	_ = x[QuerierSelectInstantDataStorageQuery-(18)]
	_ = x[QuerierSelectRangeLSSQuery-(19)]
	_ = x[QuerierSelectRangeDataStorageQuery-(20)]
	_ = x[QuerierLabelValues-(21)]
	_ = x[QuerierLabelNames-(22)]
	_ = x[DistributorWriteMetrics-(23)]
	_ = x[DistributorOutputRelabeling-(24)]
	_ = x[DistributorUpdateRelabelerState-(25)]
	_ = x[Other-(26)]
}

var _TypeTaskValues = []TypeTask{Unknown, HeadInputRelabeling, HeadAppendRelabelerSeries, HeadUpdateRelabelerState, HeadAllocatedMemory, HeadStatusType, HeadCopyAddedSeries, DataStorageAppendInnerSeries, DataStorageMergeOutOfOrderChunks, BlockWrite, WalCommit, CommitToWal, WalFlush, WalDataStorageAdd, ChunkQuerierSelect, ChunkQuerierLabelValues, ChunkQuerierLabelNames, QuerierSelectInstantLSSQuery, QuerierSelectInstantDataStorageQuery, QuerierSelectRangeLSSQuery, QuerierSelectRangeDataStorageQuery, QuerierLabelValues, QuerierLabelNames, DistributorWriteMetrics, DistributorOutputRelabeling, DistributorUpdateRelabelerState, Other}

var _TypeTaskNameToValueMap = map[string]TypeTask{
	_TypeTaskName[0:7]:          Unknown,
	_TypeTaskLowerName[0:7]:     Unknown,
	_TypeTaskName[7:26]:         HeadInputRelabeling,
	_TypeTaskLowerName[7:26]:    HeadInputRelabeling,
	_TypeTaskName[26:51]:        HeadAppendRelabelerSeries,
	_TypeTaskLowerName[26:51]:   HeadAppendRelabelerSeries,
	_TypeTaskName[51:75]:        HeadUpdateRelabelerState,
	_TypeTaskLowerName[51:75]:   HeadUpdateRelabelerState,
	_TypeTaskName[75:94]:        HeadAllocatedMemory,
	_TypeTaskLowerName[75:94]:   HeadAllocatedMemory,
	_TypeTaskName[94:108]:       HeadStatusType,
	_TypeTaskLowerName[94:108]:  HeadStatusType,
	_TypeTaskName[108:127]:      HeadCopyAddedSeries,
	_TypeTaskLowerName[108:127]: HeadCopyAddedSeries,
	_TypeTaskName[127:155]:      DataStorageAppendInnerSeries,
	_TypeTaskLowerName[127:155]: DataStorageAppendInnerSeries,
	_TypeTaskName[155:187]:      DataStorageMergeOutOfOrderChunks,
	_TypeTaskLowerName[155:187]: DataStorageMergeOutOfOrderChunks,
	_TypeTaskName[187:197]:      BlockWrite,
	_TypeTaskLowerName[187:197]: BlockWrite,
	_TypeTaskName[197:206]:      WalCommit,
	_TypeTaskLowerName[197:206]: WalCommit,
	_TypeTaskName[206:217]:      CommitToWal,
	_TypeTaskLowerName[206:217]: CommitToWal,
	_TypeTaskName[217:225]:      WalFlush,
	_TypeTaskLowerName[217:225]: WalFlush,
	_TypeTaskName[225:242]:      WalDataStorageAdd,
	_TypeTaskLowerName[225:242]: WalDataStorageAdd,
	_TypeTaskName[242:260]:      ChunkQuerierSelect,
	_TypeTaskLowerName[242:260]: ChunkQuerierSelect,
	_TypeTaskName[260:283]:      ChunkQuerierLabelValues,
	_TypeTaskLowerName[260:283]: ChunkQuerierLabelValues,
	_TypeTaskName[283:305]:      ChunkQuerierLabelNames,
	_TypeTaskLowerName[283:305]: ChunkQuerierLabelNames,
	_TypeTaskName[305:333]:      QuerierSelectInstantLSSQuery,
	_TypeTaskLowerName[305:333]: QuerierSelectInstantLSSQuery,
	_TypeTaskName[333:369]:      QuerierSelectInstantDataStorageQuery,
	_TypeTaskLowerName[333:369]: QuerierSelectInstantDataStorageQuery,
	_TypeTaskName[369:395]:      QuerierSelectRangeLSSQuery,
	_TypeTaskLowerName[369:395]: QuerierSelectRangeLSSQuery,
	_TypeTaskName[395:429]:      QuerierSelectRangeDataStorageQuery,
	_TypeTaskLowerName[395:429]: QuerierSelectRangeDataStorageQuery,
	_TypeTaskName[429:447]:      QuerierLabelValues,
	_TypeTaskLowerName[429:447]: QuerierLabelValues,
	_TypeTaskName[447:464]:      QuerierLabelNames,
	_TypeTaskLowerName[447:464]: QuerierLabelNames,
	_TypeTaskName[464:487]:      DistributorWriteMetrics,
	_TypeTaskLowerName[464:487]: DistributorWriteMetrics,
	_TypeTaskName[487:514]:      DistributorOutputRelabeling,
	_TypeTaskLowerName[487:514]: DistributorOutputRelabeling,
	_TypeTaskName[514:545]:      DistributorUpdateRelabelerState,
	_TypeTaskLowerName[514:545]: DistributorUpdateRelabelerState,
	_TypeTaskName[545:550]:      Other,
	_TypeTaskLowerName[545:550]: Other,
}

var _TypeTaskNames = []string{
	_TypeTaskName[0:7],
	_TypeTaskName[7:26],
	_TypeTaskName[26:51],
	_TypeTaskName[51:75],
	_TypeTaskName[75:94],
	_TypeTaskName[94:108],
	_TypeTaskName[108:127],
	_TypeTaskName[127:155],
	_TypeTaskName[155:187],
	_TypeTaskName[187:197],
	_TypeTaskName[197:206],
	_TypeTaskName[206:217],
	_TypeTaskName[217:225],
	_TypeTaskName[225:242],
	_TypeTaskName[242:260],
	_TypeTaskName[260:283],
	_TypeTaskName[283:305],
	_TypeTaskName[305:333],
	_TypeTaskName[333:369],
	_TypeTaskName[369:395],
	_TypeTaskName[395:429],
	_TypeTaskName[429:447],
	_TypeTaskName[447:464],
	_TypeTaskName[464:487],
	_TypeTaskName[487:514],
	_TypeTaskName[514:545],
	_TypeTaskName[545:550],
}

// TypeTaskString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func TypeTaskString(s string) (TypeTask, error) {
	if val, ok := _TypeTaskNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _TypeTaskNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to TypeTask values", s)
}

// TypeTaskValues returns all values of the enum
func TypeTaskValues() []TypeTask {
	return _TypeTaskValues
}

// TypeTaskStrings returns a slice of all String values of the enum
func TypeTaskStrings() []string {
	strs := make([]string, len(_TypeTaskNames))
	copy(strs, _TypeTaskNames)
	return strs
}

// IsATypeTask returns "true" if the value is listed in the enum definition. "false" otherwise
func (i TypeTask) IsATypeTask() bool {
	for _, v := range _TypeTaskValues {
		if i == v {
			return true
		}
	}
	return false
}
