// Code generated by "enumer -type=TypeTask"; DO NOT EDIT.

package relabeler

import (
	"fmt"
	"strings"
)

const _TypeTaskName = "UnknownLSSHeadInputRelabelingLSSHeadAppendRelabelerSeriesDataStorageAppendInnerSeriesDataStorageMergeOutOfOrderChunksWalCommitWalFlushWalWriteLSSHeadCopyAddedSeriesBlockWriteDistributorOutputRelabelingDistributorUpdateRelabelerStatedataStorageMarkerLSSHeadAllocatedMemoryDataStorageHeadAllocatedMemoryDataStorageHeadStatusLSSHeadStatusLSSQueryChunkQuerierSelectDataStorageQueryChunkQuerierSelectLSSLabelValuesChunkQuerierLSSLabelNamesChunkQuerierLSSQueryQuerierSelectInstantDataStorageQueryQuerierSelectInstantLSSQueryQuerierSelectRangeDataStorageQueryQuerierSelectRangeLSSLabelValuesQuerierLSSLabelNamesQuerier"

var _TypeTaskIndex = [...]uint16{0, 7, 29, 57, 85, 117, 126, 134, 142, 164, 174, 201, 232, 249, 271, 301, 322, 335, 361, 395, 421, 446, 474, 510, 536, 570, 591, 611}

const _TypeTaskLowerName = "unknownlssheadinputrelabelinglssheadappendrelabelerseriesdatastorageappendinnerseriesdatastoragemergeoutoforderchunkswalcommitwalflushwalwritelssheadcopyaddedseriesblockwritedistributoroutputrelabelingdistributorupdaterelabelerstatedatastoragemarkerlssheadallocatedmemorydatastorageheadallocatedmemorydatastorageheadstatuslssheadstatuslssquerychunkquerierselectdatastoragequerychunkquerierselectlsslabelvalueschunkquerierlsslabelnameschunkquerierlssqueryquerierselectinstantdatastoragequeryquerierselectinstantlssqueryquerierselectrangedatastoragequeryquerierselectrangelsslabelvaluesquerierlsslabelnamesquerier"

func (i TypeTask) String() string {
	if i >= TypeTask(len(_TypeTaskIndex)-1) {
		return fmt.Sprintf("TypeTask(%d)", i)
	}
	return _TypeTaskName[_TypeTaskIndex[i]:_TypeTaskIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _TypeTaskNoOp() {
	var x [1]struct{}
	_ = x[Unknown-(0)]
	_ = x[LSSHeadInputRelabeling-(1)]
	_ = x[LSSHeadAppendRelabelerSeries-(2)]
	_ = x[DataStorageAppendInnerSeries-(3)]
	_ = x[DataStorageMergeOutOfOrderChunks-(4)]
	_ = x[WalCommit-(5)]
	_ = x[WalFlush-(6)]
	_ = x[WalWrite-(7)]
	_ = x[LSSHeadCopyAddedSeries-(8)]
	_ = x[BlockWrite-(9)]
	_ = x[DistributorOutputRelabeling-(10)]
	_ = x[DistributorUpdateRelabelerState-(11)]
	_ = x[dataStorageMarker-(12)]
	_ = x[LSSHeadAllocatedMemory-(13)]
	_ = x[DataStorageHeadAllocatedMemory-(14)]
	_ = x[DataStorageHeadStatus-(15)]
	_ = x[LSSHeadStatus-(16)]
	_ = x[LSSQueryChunkQuerierSelect-(17)]
	_ = x[DataStorageQueryChunkQuerierSelect-(18)]
	_ = x[LSSLabelValuesChunkQuerier-(19)]
	_ = x[LSSLabelNamesChunkQuerier-(20)]
	_ = x[LSSQueryQuerierSelectInstant-(21)]
	_ = x[DataStorageQueryQuerierSelectInstant-(22)]
	_ = x[LSSQueryQuerierSelectRange-(23)]
	_ = x[DataStorageQueryQuerierSelectRange-(24)]
	_ = x[LSSLabelValuesQuerier-(25)]
	_ = x[LSSLabelNamesQuerier-(26)]
}

var _TypeTaskValues = []TypeTask{Unknown, LSSHeadInputRelabeling, LSSHeadAppendRelabelerSeries, DataStorageAppendInnerSeries, DataStorageMergeOutOfOrderChunks, WalCommit, WalFlush, WalWrite, LSSHeadCopyAddedSeries, BlockWrite, DistributorOutputRelabeling, DistributorUpdateRelabelerState, dataStorageMarker, LSSHeadAllocatedMemory, DataStorageHeadAllocatedMemory, DataStorageHeadStatus, LSSHeadStatus, LSSQueryChunkQuerierSelect, DataStorageQueryChunkQuerierSelect, LSSLabelValuesChunkQuerier, LSSLabelNamesChunkQuerier, LSSQueryQuerierSelectInstant, DataStorageQueryQuerierSelectInstant, LSSQueryQuerierSelectRange, DataStorageQueryQuerierSelectRange, LSSLabelValuesQuerier, LSSLabelNamesQuerier}

var _TypeTaskNameToValueMap = map[string]TypeTask{
	_TypeTaskName[0:7]:          Unknown,
	_TypeTaskLowerName[0:7]:     Unknown,
	_TypeTaskName[7:29]:         LSSHeadInputRelabeling,
	_TypeTaskLowerName[7:29]:    LSSHeadInputRelabeling,
	_TypeTaskName[29:57]:        LSSHeadAppendRelabelerSeries,
	_TypeTaskLowerName[29:57]:   LSSHeadAppendRelabelerSeries,
	_TypeTaskName[57:85]:        DataStorageAppendInnerSeries,
	_TypeTaskLowerName[57:85]:   DataStorageAppendInnerSeries,
	_TypeTaskName[85:117]:       DataStorageMergeOutOfOrderChunks,
	_TypeTaskLowerName[85:117]:  DataStorageMergeOutOfOrderChunks,
	_TypeTaskName[117:126]:      WalCommit,
	_TypeTaskLowerName[117:126]: WalCommit,
	_TypeTaskName[126:134]:      WalFlush,
	_TypeTaskLowerName[126:134]: WalFlush,
	_TypeTaskName[134:142]:      WalWrite,
	_TypeTaskLowerName[134:142]: WalWrite,
	_TypeTaskName[142:164]:      LSSHeadCopyAddedSeries,
	_TypeTaskLowerName[142:164]: LSSHeadCopyAddedSeries,
	_TypeTaskName[164:174]:      BlockWrite,
	_TypeTaskLowerName[164:174]: BlockWrite,
	_TypeTaskName[174:201]:      DistributorOutputRelabeling,
	_TypeTaskLowerName[174:201]: DistributorOutputRelabeling,
	_TypeTaskName[201:232]:      DistributorUpdateRelabelerState,
	_TypeTaskLowerName[201:232]: DistributorUpdateRelabelerState,
	_TypeTaskName[232:249]:      dataStorageMarker,
	_TypeTaskLowerName[232:249]: dataStorageMarker,
	_TypeTaskName[249:271]:      LSSHeadAllocatedMemory,
	_TypeTaskLowerName[249:271]: LSSHeadAllocatedMemory,
	_TypeTaskName[271:301]:      DataStorageHeadAllocatedMemory,
	_TypeTaskLowerName[271:301]: DataStorageHeadAllocatedMemory,
	_TypeTaskName[301:322]:      DataStorageHeadStatus,
	_TypeTaskLowerName[301:322]: DataStorageHeadStatus,
	_TypeTaskName[322:335]:      LSSHeadStatus,
	_TypeTaskLowerName[322:335]: LSSHeadStatus,
	_TypeTaskName[335:361]:      LSSQueryChunkQuerierSelect,
	_TypeTaskLowerName[335:361]: LSSQueryChunkQuerierSelect,
	_TypeTaskName[361:395]:      DataStorageQueryChunkQuerierSelect,
	_TypeTaskLowerName[361:395]: DataStorageQueryChunkQuerierSelect,
	_TypeTaskName[395:421]:      LSSLabelValuesChunkQuerier,
	_TypeTaskLowerName[395:421]: LSSLabelValuesChunkQuerier,
	_TypeTaskName[421:446]:      LSSLabelNamesChunkQuerier,
	_TypeTaskLowerName[421:446]: LSSLabelNamesChunkQuerier,
	_TypeTaskName[446:474]:      LSSQueryQuerierSelectInstant,
	_TypeTaskLowerName[446:474]: LSSQueryQuerierSelectInstant,
	_TypeTaskName[474:510]:      DataStorageQueryQuerierSelectInstant,
	_TypeTaskLowerName[474:510]: DataStorageQueryQuerierSelectInstant,
	_TypeTaskName[510:536]:      LSSQueryQuerierSelectRange,
	_TypeTaskLowerName[510:536]: LSSQueryQuerierSelectRange,
	_TypeTaskName[536:570]:      DataStorageQueryQuerierSelectRange,
	_TypeTaskLowerName[536:570]: DataStorageQueryQuerierSelectRange,
	_TypeTaskName[570:591]:      LSSLabelValuesQuerier,
	_TypeTaskLowerName[570:591]: LSSLabelValuesQuerier,
	_TypeTaskName[591:611]:      LSSLabelNamesQuerier,
	_TypeTaskLowerName[591:611]: LSSLabelNamesQuerier,
}

var _TypeTaskNames = []string{
	_TypeTaskName[0:7],
	_TypeTaskName[7:29],
	_TypeTaskName[29:57],
	_TypeTaskName[57:85],
	_TypeTaskName[85:117],
	_TypeTaskName[117:126],
	_TypeTaskName[126:134],
	_TypeTaskName[134:142],
	_TypeTaskName[142:164],
	_TypeTaskName[164:174],
	_TypeTaskName[174:201],
	_TypeTaskName[201:232],
	_TypeTaskName[232:249],
	_TypeTaskName[249:271],
	_TypeTaskName[271:301],
	_TypeTaskName[301:322],
	_TypeTaskName[322:335],
	_TypeTaskName[335:361],
	_TypeTaskName[361:395],
	_TypeTaskName[395:421],
	_TypeTaskName[421:446],
	_TypeTaskName[446:474],
	_TypeTaskName[474:510],
	_TypeTaskName[510:536],
	_TypeTaskName[536:570],
	_TypeTaskName[570:591],
	_TypeTaskName[591:611],
}

// TypeTaskString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func TypeTaskString(s string) (TypeTask, error) {
	if val, ok := _TypeTaskNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _TypeTaskNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to TypeTask values", s)
}

// TypeTaskValues returns all values of the enum
func TypeTaskValues() []TypeTask {
	return _TypeTaskValues
}

// TypeTaskStrings returns a slice of all String values of the enum
func TypeTaskStrings() []string {
	strs := make([]string, len(_TypeTaskNames))
	copy(strs, _TypeTaskNames)
	return strs
}

// IsATypeTask returns "true" if the value is listed in the enum definition. "false" otherwise
func (i TypeTask) IsATypeTask() bool {
	for _, v := range _TypeTaskValues {
		if i == v {
			return true
		}
	}
	return false
}
