/* Generated by re2c */
#include <cstring>

#include "prometheus/textparse/escape.h"
#include "tokenizer.h"

// NOLINTBEGIN
enum YYCONDTYPE { yycinit, yyccomment, yycmeta_name, yycmeta_text_with_leading_spaces, yyclabels, yyclabel_value, yycvalue, yyctimestamp };

// NOLINTEND

namespace PromPP::Prometheus::textparse::Prometheus {

Tokenizer::Tokenizer() : condition_{yycinit} {}

Tokenizer::Tokenizer(std::string_view str)
    : start_ptr_(str.data()),
      cursor_ptr_(start_ptr_),
      limit_ptr_(start_ptr_ + str.size()),
      marker_ptr_(start_ptr_),
      token_ptr_(start_ptr_),
      condition_{yycinit} {}

void Tokenizer::tokenize(std::string_view str) noexcept {
  start_ptr_ = str.data();
  cursor_ptr_ = start_ptr_;
  limit_ptr_ = start_ptr_ + str.size();
  marker_ptr_ = start_ptr_;
  token_ptr_ = start_ptr_;

  condition_ = yycinit;
}

Token Tokenizer::consume_comment(Token token) noexcept {
  if (cursor_ptr_ = static_cast<const char*>(std::memchr(cursor_ptr_, '\n', limit_ptr_ - cursor_ptr_)); cursor_ptr_ == nullptr) [[unlikely]] {
    cursor_ptr_ = limit_ptr_;
  }

  condition_ = yycinit;
  return token;
}

Token Tokenizer::consume_escaped_string(Token token) noexcept {
  while (true) {
    if (cursor_ptr_ = static_cast<const char*>(std::memchr(cursor_ptr_, '"', limit_ptr_ - cursor_ptr_)); cursor_ptr_ == nullptr) [[unlikely]] {
      cursor_ptr_ = limit_ptr_;
      return Token::kInvalid;
    }

    if (is_escaped_char(cursor_ptr_, token_ptr_ + 1)) [[unlikely]] {
      ++cursor_ptr_;
      continue;
    }

    break;
  }

  ++cursor_ptr_;
  return token;
}

// NOLINTBEGIN
Token Tokenizer::next_impl() noexcept {
  token_ptr_ = cursor_ptr_;

  {
    unsigned char yych;
    static const int yyctable[8] = {
        (int)((char*) && yyc_init - (char*) && yyc_init),      (int)((char*) && yyc_comment - (char*) && yyc_init),
        (int)((char*) && yyc_meta_name - (char*) && yyc_init), (int)((char*) && yyc_meta_text_with_leading_spaces - (char*) && yyc_init),
        (int)((char*) && yyc_labels - (char*) && yyc_init),    (int)((char*) && yyc_label_value - (char*) && yyc_init),
        (int)((char*) && yyc_value - (char*) && yyc_init),     (int)((char*) && yyc_timestamp - (char*) && yyc_init)};
    static const unsigned char yybm_init[256] = {
        0,  0,   0,   0,   0,   0,   0,   0,   0,   64,  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 0, 0, 0, 0,
        64, 0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 0, 0, 0, 0, 0,
        0,  128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 0, 0, 0, 0, 128,
        0,  128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 0, 0, 0, 0, 0,
        0,  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 0, 0, 0, 0,
        0,  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 0, 0, 0, 0,
        0,  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 0, 0, 0, 0,
        0,  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 0, 0, 0, 0};
    static const unsigned char yybm_comment[256] = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 128, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0};
    static const unsigned char yybm_meta_name[256] = {
        0,  0,   0,   0,   0,   0,   0,   0,   0,   64,  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 0, 0, 0, 0,
        64, 0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 0, 0, 0, 0, 0,
        0,  128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 0, 0, 0, 0, 128,
        0,  128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 0, 0, 0, 0, 0,
        0,  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 0, 0, 0, 0,
        0,  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 0, 0, 0, 0,
        0,  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 0, 0, 0, 0,
        0,  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 0, 0, 0, 0};
    static const unsigned char yybm_meta_text_with_leading_spaces[256] = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 128, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0};
    static const unsigned char yybm_labels[256] = {
        0,  0,   0,   0,   0,   0,   0,   0,   0,   64,  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 0, 0, 0, 0,
        64, 0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 0,   0, 0, 0, 0, 0,
        0,  128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 0, 0, 0, 0, 128,
        0,  128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 0, 0, 0, 0, 0,
        0,  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 0, 0, 0, 0,
        0,  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 0, 0, 0, 0,
        0,  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 0, 0, 0, 0,
        0,  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 0, 0, 0, 0};
    static const unsigned char yybm_label_value[256] = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 128, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0};
    static const unsigned char yybm_value[256] = {
        64, 64, 64, 64, 64, 64, 64, 64, 64, 128, 0,  64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 128, 64, 64, 64, 64,
        64, 64, 64, 64, 64, 64, 64, 64, 64, 64,  64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,  64, 64, 64, 64,
        64, 64, 64, 64, 64, 64, 64, 64, 64, 64,  64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,  64, 64, 64, 64,
        64, 64, 64, 64, 64, 64, 64, 64, 64, 64,  64, 64, 0,  64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,  64, 64, 64, 64,
        64, 64, 64, 64, 64, 64, 64, 64, 64, 64,  64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,  64, 64, 64, 64,
        64, 64, 64, 64, 64, 64, 64, 64, 64, 64,  64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,  64, 64, 64, 64,
        64, 64, 64, 64, 64, 64, 64, 64, 64, 64,  64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,  64};
    static const unsigned char yybm_timestamp[256] = {
        0, 0, 0, 0, 0, 0,   0,   0,   0,   64,  0,   0,   0,   0,   0,   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  0, 0, 0, 0, 0, 0, 0, 0};
    goto*((char*) && yyc_init + yyctable[condition_]);
  /* *********************************** */
  yyc_init:
    if ((limit_ptr_ - cursor_ptr_) < 2) {
      if (limit_ptr_ == cursor_ptr_) {
        return Token::kEOF;
      }
    }
    yych = *cursor_ptr_;
    {
      static const int yytarget[256] = {(int)((char*) && yy2 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy3 - (char*) && yy1), (int)((char*) && yy4 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy3 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy5 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy6 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy6 - (char*) && yy1),
                                        (int)((char*) && yy6 - (char*) && yy1), (int)((char*) && yy6 - (char*) && yy1), (int)((char*) && yy6 - (char*) && yy1),
                                        (int)((char*) && yy6 - (char*) && yy1), (int)((char*) && yy6 - (char*) && yy1), (int)((char*) && yy6 - (char*) && yy1),
                                        (int)((char*) && yy6 - (char*) && yy1), (int)((char*) && yy6 - (char*) && yy1), (int)((char*) && yy6 - (char*) && yy1),
                                        (int)((char*) && yy6 - (char*) && yy1), (int)((char*) && yy6 - (char*) && yy1), (int)((char*) && yy6 - (char*) && yy1),
                                        (int)((char*) && yy6 - (char*) && yy1), (int)((char*) && yy6 - (char*) && yy1), (int)((char*) && yy6 - (char*) && yy1),
                                        (int)((char*) && yy6 - (char*) && yy1), (int)((char*) && yy6 - (char*) && yy1), (int)((char*) && yy6 - (char*) && yy1),
                                        (int)((char*) && yy6 - (char*) && yy1), (int)((char*) && yy6 - (char*) && yy1), (int)((char*) && yy6 - (char*) && yy1),
                                        (int)((char*) && yy6 - (char*) && yy1), (int)((char*) && yy6 - (char*) && yy1), (int)((char*) && yy6 - (char*) && yy1),
                                        (int)((char*) && yy6 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy6 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy6 - (char*) && yy1), (int)((char*) && yy6 - (char*) && yy1),
                                        (int)((char*) && yy6 - (char*) && yy1), (int)((char*) && yy6 - (char*) && yy1), (int)((char*) && yy6 - (char*) && yy1),
                                        (int)((char*) && yy6 - (char*) && yy1), (int)((char*) && yy6 - (char*) && yy1), (int)((char*) && yy6 - (char*) && yy1),
                                        (int)((char*) && yy6 - (char*) && yy1), (int)((char*) && yy6 - (char*) && yy1), (int)((char*) && yy6 - (char*) && yy1),
                                        (int)((char*) && yy6 - (char*) && yy1), (int)((char*) && yy6 - (char*) && yy1), (int)((char*) && yy6 - (char*) && yy1),
                                        (int)((char*) && yy6 - (char*) && yy1), (int)((char*) && yy6 - (char*) && yy1), (int)((char*) && yy6 - (char*) && yy1),
                                        (int)((char*) && yy6 - (char*) && yy1), (int)((char*) && yy6 - (char*) && yy1), (int)((char*) && yy6 - (char*) && yy1),
                                        (int)((char*) && yy6 - (char*) && yy1), (int)((char*) && yy6 - (char*) && yy1), (int)((char*) && yy6 - (char*) && yy1),
                                        (int)((char*) && yy6 - (char*) && yy1), (int)((char*) && yy6 - (char*) && yy1), (int)((char*) && yy6 - (char*) && yy1),
                                        (int)((char*) && yy7 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1), (int)((char*) && yy1 - (char*) && yy1),
                                        (int)((char*) && yy1 - (char*) && yy1)};
      goto*((char*) && yy1 + yytarget[yych]);
    }
  yy1: { return Token::kInvalid; }
  yy2:
    ++cursor_ptr_;
    {
      return Token::kEOF;
    }
  yy3:
    ++cursor_ptr_;
    if (limit_ptr_ <= cursor_ptr_) {
      if (limit_ptr_ == cursor_ptr_) {
        return Token::kEOF;
      }
    }
    yych = *cursor_ptr_;
    if (yybm_init[0 + yych] & 64)
      goto yy3;
    {
      return Token::kWhitespace;
    }
  yy4:
    ++cursor_ptr_;
    {
      return Token::kLinebreak;
    }
  yy5:
    yych = *++cursor_ptr_;
    if (yych == '\t')
      goto yy8;
    if (yych == ' ')
      goto yy8;
    {
      token_ptr_ = cursor_ptr_;
      return consume_comment();
    }
  yy6:
    ++cursor_ptr_;
    if (limit_ptr_ <= cursor_ptr_) {
      if (limit_ptr_ == cursor_ptr_) {
        return Token::kEOF;
      }
    }
    yych = *cursor_ptr_;
    if (yybm_init[0 + yych] & 128)
      goto yy6;
    condition_ = yycvalue;
    {
      return Token::kMetricName;
    }
  yy7:
    ++cursor_ptr_;
    condition_ = yyclabels;
    {
      return Token::kBraceOpen;
    }
  yy8:
    ++cursor_ptr_;
    if (limit_ptr_ <= cursor_ptr_) {
      if (limit_ptr_ == cursor_ptr_) {
        return Token::kEOF;
      }
    }
    yych = *cursor_ptr_;
    if (yych == '\t')
      goto yy8;
    if (yych == ' ')
      goto yy8;
    condition_ = yyccomment;
    {
      token_ptr_ = cursor_ptr_;
    }
  /* *********************************** */
  yyc_comment:
    marker_ptr_ = cursor_ptr_;
    if ((limit_ptr_ - cursor_ptr_) < 5) {
      if (limit_ptr_ == cursor_ptr_) {
        return Token::kEOF;
      }
    }
    yych = *cursor_ptr_;
    if (yybm_comment[0 + yych] & 128)
      goto yy11;
    if (yych == 'H')
      goto yy12;
    if (yych == 'T')
      goto yy14;
  yy10:
    condition_ = yycinit;
    {
      return consume_comment();
    }
  yy11:
    ++cursor_ptr_;
    if (limit_ptr_ <= cursor_ptr_) {
      if (limit_ptr_ == cursor_ptr_) {
        return Token::kEOF;
      }
    }
    yych = *cursor_ptr_;
    if (yybm_comment[0 + yych] & 128)
      goto yy11;
    {
      return Token::kWhitespace;
    }
  yy12:
    yych = *++cursor_ptr_;
    if (yych == 'E')
      goto yy15;
  yy13:
    cursor_ptr_ = marker_ptr_;
    goto yy10;
  yy14:
    yych = *++cursor_ptr_;
    if (yych == 'Y')
      goto yy16;
    goto yy13;
  yy15:
    yych = *++cursor_ptr_;
    if (yych == 'L')
      goto yy17;
    goto yy13;
  yy16:
    yych = *++cursor_ptr_;
    if (yych == 'P')
      goto yy18;
    goto yy13;
  yy17:
    yych = *++cursor_ptr_;
    if (yych == 'P')
      goto yy19;
    goto yy13;
  yy18:
    yych = *++cursor_ptr_;
    if (yych == 'E')
      goto yy20;
    goto yy13;
  yy19:
    yych = *++cursor_ptr_;
    if (yych == '\t')
      goto yy21;
    if (yych == ' ')
      goto yy21;
    goto yy13;
  yy20:
    yych = *++cursor_ptr_;
    if (yych == '\t')
      goto yy22;
    if (yych == ' ')
      goto yy22;
    goto yy13;
  yy21:
    ++cursor_ptr_;
    if (limit_ptr_ <= cursor_ptr_) {
      if (limit_ptr_ == cursor_ptr_) {
        return Token::kEOF;
      }
    }
    yych = *cursor_ptr_;
    if (yych == '\t')
      goto yy21;
    if (yych == ' ')
      goto yy21;
    condition_ = yycmeta_name;
    {
      return Token::kHelp;
    }
  yy22:
    ++cursor_ptr_;
    if (limit_ptr_ <= cursor_ptr_) {
      if (limit_ptr_ == cursor_ptr_) {
        return Token::kEOF;
      }
    }
    yych = *cursor_ptr_;
    if (yych == '\t')
      goto yy22;
    if (yych == ' ')
      goto yy22;
    condition_ = yycmeta_name;
    {
      return Token::kType;
    }
  /* *********************************** */
  yyc_meta_name:
    if (limit_ptr_ <= cursor_ptr_) {
      if (limit_ptr_ == cursor_ptr_) {
        return Token::kEOF;
      }
    }
    yych = *cursor_ptr_;
    {
      static const int yytarget[256] = {
          (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24),
          (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24),
          (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24),
          (int)((char*) && yy25 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24),
          (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24),
          (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24),
          (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24),
          (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24),
          (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24),
          (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24),
          (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy25 - (char*) && yy24),
          (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy26 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24),
          (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24),
          (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24),
          (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24),
          (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24),
          (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24),
          (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24),
          (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24),
          (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy27 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24),
          (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24),
          (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy27 - (char*) && yy24),
          (int)((char*) && yy27 - (char*) && yy24), (int)((char*) && yy27 - (char*) && yy24), (int)((char*) && yy27 - (char*) && yy24),
          (int)((char*) && yy27 - (char*) && yy24), (int)((char*) && yy27 - (char*) && yy24), (int)((char*) && yy27 - (char*) && yy24),
          (int)((char*) && yy27 - (char*) && yy24), (int)((char*) && yy27 - (char*) && yy24), (int)((char*) && yy27 - (char*) && yy24),
          (int)((char*) && yy27 - (char*) && yy24), (int)((char*) && yy27 - (char*) && yy24), (int)((char*) && yy27 - (char*) && yy24),
          (int)((char*) && yy27 - (char*) && yy24), (int)((char*) && yy27 - (char*) && yy24), (int)((char*) && yy27 - (char*) && yy24),
          (int)((char*) && yy27 - (char*) && yy24), (int)((char*) && yy27 - (char*) && yy24), (int)((char*) && yy27 - (char*) && yy24),
          (int)((char*) && yy27 - (char*) && yy24), (int)((char*) && yy27 - (char*) && yy24), (int)((char*) && yy27 - (char*) && yy24),
          (int)((char*) && yy27 - (char*) && yy24), (int)((char*) && yy27 - (char*) && yy24), (int)((char*) && yy27 - (char*) && yy24),
          (int)((char*) && yy27 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24),
          (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy27 - (char*) && yy24),
          (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy27 - (char*) && yy24), (int)((char*) && yy27 - (char*) && yy24),
          (int)((char*) && yy27 - (char*) && yy24), (int)((char*) && yy27 - (char*) && yy24), (int)((char*) && yy27 - (char*) && yy24),
          (int)((char*) && yy27 - (char*) && yy24), (int)((char*) && yy27 - (char*) && yy24), (int)((char*) && yy27 - (char*) && yy24),
          (int)((char*) && yy27 - (char*) && yy24), (int)((char*) && yy27 - (char*) && yy24), (int)((char*) && yy27 - (char*) && yy24),
          (int)((char*) && yy27 - (char*) && yy24), (int)((char*) && yy27 - (char*) && yy24), (int)((char*) && yy27 - (char*) && yy24),
          (int)((char*) && yy27 - (char*) && yy24), (int)((char*) && yy27 - (char*) && yy24), (int)((char*) && yy27 - (char*) && yy24),
          (int)((char*) && yy27 - (char*) && yy24), (int)((char*) && yy27 - (char*) && yy24), (int)((char*) && yy27 - (char*) && yy24),
          (int)((char*) && yy27 - (char*) && yy24), (int)((char*) && yy27 - (char*) && yy24), (int)((char*) && yy27 - (char*) && yy24),
          (int)((char*) && yy27 - (char*) && yy24), (int)((char*) && yy27 - (char*) && yy24), (int)((char*) && yy27 - (char*) && yy24),
          (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24),
          (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24),
          (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24),
          (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24),
          (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24),
          (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24),
          (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24),
          (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24),
          (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24),
          (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24),
          (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24),
          (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24),
          (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24),
          (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24),
          (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24),
          (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24),
          (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24),
          (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24),
          (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24),
          (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24),
          (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24),
          (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24),
          (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24),
          (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24),
          (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24),
          (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24),
          (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24),
          (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24),
          (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24),
          (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24),
          (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24),
          (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24),
          (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24),
          (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24),
          (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24),
          (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24),
          (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24),
          (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24),
          (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24),
          (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24),
          (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24),
          (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24),
          (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24),
          (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24), (int)((char*) && yy24 - (char*) && yy24),
          (int)((char*) && yy24 - (char*) && yy24)};
      goto*((char*) && yy24 + yytarget[yych]);
    }
  yy24: { return Token::kInvalid; }
  yy25:
    ++cursor_ptr_;
    if (limit_ptr_ <= cursor_ptr_) {
      if (limit_ptr_ == cursor_ptr_) {
        return Token::kEOF;
      }
    }
    yych = *cursor_ptr_;
    if (yybm_meta_name[0 + yych] & 64)
      goto yy25;
    {
      return Token::kWhitespace;
    }
  yy26:
    ++cursor_ptr_;
    condition_ = yycmeta_text_with_leading_spaces;
    {
      return consume_escaped_string(Token::kMetricName);
    }
  yy27:
    ++cursor_ptr_;
    if (limit_ptr_ <= cursor_ptr_) {
      if (limit_ptr_ == cursor_ptr_) {
        return Token::kEOF;
      }
    }
    yych = *cursor_ptr_;
    if (yybm_meta_name[0 + yych] & 128)
      goto yy27;
    condition_ = yycmeta_text_with_leading_spaces;
    {
      return Token::kMetricName;
    }
  /* *********************************** */
  yyc_meta_text_with_leading_spaces:
    goto yy28;
  yy29:
    ++cursor_ptr_;
  yy28:
    if (limit_ptr_ <= cursor_ptr_) {
      if (limit_ptr_ == cursor_ptr_) {
        return Token::kEOF;
      }
    }
    yych = *cursor_ptr_;
    if (yybm_meta_text_with_leading_spaces[0 + yych] & 128)
      goto yy29;
    condition_ = yycinit;
    {
      token_ptr_ = cursor_ptr_;
      return consume_comment(Token::kText);
    }
  /* *********************************** */
  yyc_labels:
    if (limit_ptr_ <= cursor_ptr_) {
      if (limit_ptr_ == cursor_ptr_) {
        return Token::kEOF;
      }
    }
    yych = *cursor_ptr_;
    {
      static const int yytarget[256] = {
          (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31),
          (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31),
          (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31),
          (int)((char*) && yy32 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31),
          (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31),
          (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31),
          (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31),
          (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31),
          (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31),
          (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31),
          (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy32 - (char*) && yy31),
          (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy33 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31),
          (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31),
          (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31),
          (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy34 - (char*) && yy31),
          (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31),
          (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31),
          (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31),
          (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31),
          (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31),
          (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy35 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31),
          (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy36 - (char*) && yy31),
          (int)((char*) && yy36 - (char*) && yy31), (int)((char*) && yy36 - (char*) && yy31), (int)((char*) && yy36 - (char*) && yy31),
          (int)((char*) && yy36 - (char*) && yy31), (int)((char*) && yy36 - (char*) && yy31), (int)((char*) && yy36 - (char*) && yy31),
          (int)((char*) && yy36 - (char*) && yy31), (int)((char*) && yy36 - (char*) && yy31), (int)((char*) && yy36 - (char*) && yy31),
          (int)((char*) && yy36 - (char*) && yy31), (int)((char*) && yy36 - (char*) && yy31), (int)((char*) && yy36 - (char*) && yy31),
          (int)((char*) && yy36 - (char*) && yy31), (int)((char*) && yy36 - (char*) && yy31), (int)((char*) && yy36 - (char*) && yy31),
          (int)((char*) && yy36 - (char*) && yy31), (int)((char*) && yy36 - (char*) && yy31), (int)((char*) && yy36 - (char*) && yy31),
          (int)((char*) && yy36 - (char*) && yy31), (int)((char*) && yy36 - (char*) && yy31), (int)((char*) && yy36 - (char*) && yy31),
          (int)((char*) && yy36 - (char*) && yy31), (int)((char*) && yy36 - (char*) && yy31), (int)((char*) && yy36 - (char*) && yy31),
          (int)((char*) && yy36 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31),
          (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy36 - (char*) && yy31),
          (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy36 - (char*) && yy31), (int)((char*) && yy36 - (char*) && yy31),
          (int)((char*) && yy36 - (char*) && yy31), (int)((char*) && yy36 - (char*) && yy31), (int)((char*) && yy36 - (char*) && yy31),
          (int)((char*) && yy36 - (char*) && yy31), (int)((char*) && yy36 - (char*) && yy31), (int)((char*) && yy36 - (char*) && yy31),
          (int)((char*) && yy36 - (char*) && yy31), (int)((char*) && yy36 - (char*) && yy31), (int)((char*) && yy36 - (char*) && yy31),
          (int)((char*) && yy36 - (char*) && yy31), (int)((char*) && yy36 - (char*) && yy31), (int)((char*) && yy36 - (char*) && yy31),
          (int)((char*) && yy36 - (char*) && yy31), (int)((char*) && yy36 - (char*) && yy31), (int)((char*) && yy36 - (char*) && yy31),
          (int)((char*) && yy36 - (char*) && yy31), (int)((char*) && yy36 - (char*) && yy31), (int)((char*) && yy36 - (char*) && yy31),
          (int)((char*) && yy36 - (char*) && yy31), (int)((char*) && yy36 - (char*) && yy31), (int)((char*) && yy36 - (char*) && yy31),
          (int)((char*) && yy36 - (char*) && yy31), (int)((char*) && yy36 - (char*) && yy31), (int)((char*) && yy36 - (char*) && yy31),
          (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy37 - (char*) && yy31),
          (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31),
          (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31),
          (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31),
          (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31),
          (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31),
          (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31),
          (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31),
          (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31),
          (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31),
          (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31),
          (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31),
          (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31),
          (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31),
          (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31),
          (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31),
          (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31),
          (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31),
          (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31),
          (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31),
          (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31),
          (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31),
          (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31),
          (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31),
          (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31),
          (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31),
          (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31),
          (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31),
          (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31),
          (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31),
          (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31),
          (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31),
          (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31),
          (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31),
          (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31),
          (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31),
          (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31),
          (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31),
          (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31),
          (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31),
          (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31),
          (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31),
          (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31),
          (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31), (int)((char*) && yy31 - (char*) && yy31),
          (int)((char*) && yy31 - (char*) && yy31)};
      goto*((char*) && yy31 + yytarget[yych]);
    }
  yy31: { return Token::kInvalid; }
  yy32:
    ++cursor_ptr_;
    if (limit_ptr_ <= cursor_ptr_) {
      if (limit_ptr_ == cursor_ptr_) {
        return Token::kEOF;
      }
    }
    yych = *cursor_ptr_;
    if (yybm_labels[0 + yych] & 64)
      goto yy32;
    {
      return Token::kWhitespace;
    }
  yy33:
    ++cursor_ptr_;
    {
      return consume_escaped_string(Token::kQuotedString);
    }
  yy34:
    ++cursor_ptr_;
    {
      return Token::kComma;
    }
  yy35:
    ++cursor_ptr_;
    condition_ = yyclabel_value;
    {
      return Token::kEqual;
    }
  yy36:
    ++cursor_ptr_;
    if (limit_ptr_ <= cursor_ptr_) {
      if (limit_ptr_ == cursor_ptr_) {
        return Token::kEOF;
      }
    }
    yych = *cursor_ptr_;
    if (yybm_labels[0 + yych] & 128)
      goto yy36;
    {
      return Token::kLabelName;
    }
  yy37:
    ++cursor_ptr_;
    condition_ = yycvalue;
    {
      return Token::kBraceClose;
    }
  /* *********************************** */
  yyc_label_value:
    if (limit_ptr_ <= cursor_ptr_) {
      if (limit_ptr_ == cursor_ptr_) {
        return Token::kEOF;
      }
    }
    yych = *cursor_ptr_;
    if (yybm_label_value[0 + yych] & 128)
      goto yy39;
    if (yych == '"')
      goto yy40;
    {
      return Token::kInvalid;
    }
  yy39:
    ++cursor_ptr_;
    if (limit_ptr_ <= cursor_ptr_) {
      if (limit_ptr_ == cursor_ptr_) {
        return Token::kEOF;
      }
    }
    yych = *cursor_ptr_;
    if (yybm_label_value[0 + yych] & 128)
      goto yy39;
    {
      return Token::kWhitespace;
    }
  yy40:
    ++cursor_ptr_;
    condition_ = yyclabels;
    {
      return consume_escaped_string(Token::kLabelValue);
    }
  /* *********************************** */
  yyc_value:
    if (limit_ptr_ <= cursor_ptr_) {
      if (limit_ptr_ == cursor_ptr_) {
        return Token::kEOF;
      }
    }
    yych = *cursor_ptr_;
    if (yybm_value[0 + yych] & 64)
      goto yy43;
    if (yych == '\n')
      goto yy42;
    if (yych <= ' ')
      goto yy44;
    goto yy45;
  yy42: { return Token::kInvalid; }
  yy43:
    ++cursor_ptr_;
    if (limit_ptr_ <= cursor_ptr_) {
      if (limit_ptr_ == cursor_ptr_) {
        return Token::kEOF;
      }
    }
    yych = *cursor_ptr_;
    if (yybm_value[0 + yych] & 64)
      goto yy43;
    condition_ = yyctimestamp;
    {
      return Token::kValue;
    }
  yy44:
    ++cursor_ptr_;
    if (limit_ptr_ <= cursor_ptr_) {
      if (limit_ptr_ == cursor_ptr_) {
        return Token::kEOF;
      }
    }
    yych = *cursor_ptr_;
    if (yybm_value[0 + yych] & 128)
      goto yy44;
    {
      return Token::kWhitespace;
    }
  yy45:
    ++cursor_ptr_;
    condition_ = yyclabels;
    {
      return Token::kBraceOpen;
    }
  /* *********************************** */
  yyc_timestamp:
    if (limit_ptr_ <= cursor_ptr_) {
      if (limit_ptr_ == cursor_ptr_) {
        return Token::kEOF;
      }
    }
    yych = *cursor_ptr_;
    if (yybm_timestamp[0 + yych] & 64)
      goto yy48;
    if (yych <= 0x08)
      goto yy47;
    if (yych <= '\n')
      goto yy49;
    if (yych <= '/')
      goto yy47;
    if (yych <= '9')
      goto yy50;
  yy47: { return Token::kInvalid; }
  yy48:
    ++cursor_ptr_;
    if (limit_ptr_ <= cursor_ptr_) {
      if (limit_ptr_ == cursor_ptr_) {
        return Token::kEOF;
      }
    }
    yych = *cursor_ptr_;
    if (yybm_timestamp[0 + yych] & 64)
      goto yy48;
    {
      return Token::kWhitespace;
    }
  yy49:
    ++cursor_ptr_;
    condition_ = yycinit;
    {
      return Token::kLinebreak;
    }
  yy50:
    ++cursor_ptr_;
    if (limit_ptr_ <= cursor_ptr_) {
      if (limit_ptr_ == cursor_ptr_) {
        return Token::kEOF;
      }
    }
    yych = *cursor_ptr_;
    if (yybm_timestamp[0 + yych] & 128)
      goto yy50;
    {
      return Token::kTimestamp;
    }
  }
}
// NOLINTEND

}  // namespace PromPP::Prometheus::textparse::Prometheus
