// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/go-kit/log"
	"github.com/prometheus/prometheus/pp-pkg/blocks/lcompactor"
	"github.com/prometheus/prometheus/storage"
	"github.com/prometheus/prometheus/tsdb"
	"github.com/prometheus/prometheus/tsdb/chunkenc"
	"sync"
)

// BlockPopulatorMock is a mock implementation of tcompactor.BlockPopulator.
//
//	func TestSomethingThatUsesBlockPopulator(t *testing.T) {
//
//		// make and configure a mocked tcompactor.BlockPopulator
//		mockedBlockPopulator := &BlockPopulatorMock{
//			PopulateBlockFunc: func(ctx context.Context, metrics *lcompactor.CompactorMetrics, logger log.Logger, chunkPool chunkenc.Pool, mergeFunc storage.VerticalChunkSeriesMergeFunc, blocks []tsdb.BlockReader, meta *tsdb.BlockMeta, indexw tsdb.IndexWriter, chunkw tsdb.ChunkWriter, postingsFunc tsdb.IndexReaderPostingsFunc) error {
//				panic("mock out the PopulateBlock method")
//			},
//		}
//
//		// use mockedBlockPopulator in code that requires tcompactor.BlockPopulator
//		// and then make assertions.
//
//	}
type BlockPopulatorMock struct {
	// PopulateBlockFunc mocks the PopulateBlock method.
	PopulateBlockFunc func(ctx context.Context, metrics *lcompactor.CompactorMetrics, logger log.Logger, chunkPool chunkenc.Pool, mergeFunc storage.VerticalChunkSeriesMergeFunc, blocks []tsdb.BlockReader, meta *tsdb.BlockMeta, indexw tsdb.IndexWriter, chunkw tsdb.ChunkWriter, postingsFunc tsdb.IndexReaderPostingsFunc) error

	// calls tracks calls to the methods.
	calls struct {
		// PopulateBlock holds details about calls to the PopulateBlock method.
		PopulateBlock []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Metrics is the metrics argument value.
			Metrics *lcompactor.CompactorMetrics
			// Logger is the logger argument value.
			Logger log.Logger
			// ChunkPool is the chunkPool argument value.
			ChunkPool chunkenc.Pool
			// MergeFunc is the mergeFunc argument value.
			MergeFunc storage.VerticalChunkSeriesMergeFunc
			// Blocks is the blocks argument value.
			Blocks []tsdb.BlockReader
			// Meta is the meta argument value.
			Meta *tsdb.BlockMeta
			// Indexw is the indexw argument value.
			Indexw tsdb.IndexWriter
			// Chunkw is the chunkw argument value.
			Chunkw tsdb.ChunkWriter
			// PostingsFunc is the postingsFunc argument value.
			PostingsFunc tsdb.IndexReaderPostingsFunc
		}
	}
	lockPopulateBlock sync.RWMutex
}

// PopulateBlock calls PopulateBlockFunc.
func (mock *BlockPopulatorMock) PopulateBlock(ctx context.Context, metrics *lcompactor.CompactorMetrics, logger log.Logger, chunkPool chunkenc.Pool, mergeFunc storage.VerticalChunkSeriesMergeFunc, blocks []tsdb.BlockReader, meta *tsdb.BlockMeta, indexw tsdb.IndexWriter, chunkw tsdb.ChunkWriter, postingsFunc tsdb.IndexReaderPostingsFunc) error {
	if mock.PopulateBlockFunc == nil {
		panic("BlockPopulatorMock.PopulateBlockFunc: method is nil but BlockPopulator.PopulateBlock was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		Metrics      *lcompactor.CompactorMetrics
		Logger       log.Logger
		ChunkPool    chunkenc.Pool
		MergeFunc    storage.VerticalChunkSeriesMergeFunc
		Blocks       []tsdb.BlockReader
		Meta         *tsdb.BlockMeta
		Indexw       tsdb.IndexWriter
		Chunkw       tsdb.ChunkWriter
		PostingsFunc tsdb.IndexReaderPostingsFunc
	}{
		Ctx:          ctx,
		Metrics:      metrics,
		Logger:       logger,
		ChunkPool:    chunkPool,
		MergeFunc:    mergeFunc,
		Blocks:       blocks,
		Meta:         meta,
		Indexw:       indexw,
		Chunkw:       chunkw,
		PostingsFunc: postingsFunc,
	}
	mock.lockPopulateBlock.Lock()
	mock.calls.PopulateBlock = append(mock.calls.PopulateBlock, callInfo)
	mock.lockPopulateBlock.Unlock()
	return mock.PopulateBlockFunc(ctx, metrics, logger, chunkPool, mergeFunc, blocks, meta, indexw, chunkw, postingsFunc)
}

// PopulateBlockCalls gets all the calls that were made to PopulateBlock.
// Check the length with:
//
//	len(mockedBlockPopulator.PopulateBlockCalls())
func (mock *BlockPopulatorMock) PopulateBlockCalls() []struct {
	Ctx          context.Context
	Metrics      *lcompactor.CompactorMetrics
	Logger       log.Logger
	ChunkPool    chunkenc.Pool
	MergeFunc    storage.VerticalChunkSeriesMergeFunc
	Blocks       []tsdb.BlockReader
	Meta         *tsdb.BlockMeta
	Indexw       tsdb.IndexWriter
	Chunkw       tsdb.ChunkWriter
	PostingsFunc tsdb.IndexReaderPostingsFunc
} {
	var calls []struct {
		Ctx          context.Context
		Metrics      *lcompactor.CompactorMetrics
		Logger       log.Logger
		ChunkPool    chunkenc.Pool
		MergeFunc    storage.VerticalChunkSeriesMergeFunc
		Blocks       []tsdb.BlockReader
		Meta         *tsdb.BlockMeta
		Indexw       tsdb.IndexWriter
		Chunkw       tsdb.ChunkWriter
		PostingsFunc tsdb.IndexReaderPostingsFunc
	}
	mock.lockPopulateBlock.RLock()
	calls = mock.calls.PopulateBlock
	mock.lockPopulateBlock.RUnlock()
	return calls
}
