// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"github.com/go-kit/log"
	"github.com/oklog/ulid"
	"github.com/prometheus/prometheus/pp-pkg/blocks/block"
	"github.com/prometheus/prometheus/pp-pkg/blocks/lcompactor"
	"github.com/prometheus/prometheus/tsdb"
	"sync"
)

// CompactorMock is a mock implementation of tcompactor.Compactor.
//
//	func TestSomethingThatUsesCompactor(t *testing.T) {
//
//		// make and configure a mocked tcompactor.Compactor
//		mockedCompactor := &CompactorMock{
//			CompactWithBlockPopulatorWithWriteMetaFileFunc: func(dest string, dirs []string, open []*block.Block, blockPopulator lcompactor.BlockPopulator, writeMetaFileFn func(logger log.Logger, dir string, meta *tsdb.BlockMeta) (int64, error)) ([]ulid.ULID, error) {
//				panic("mock out the CompactWithBlockPopulatorWithWriteMetaFile method")
//			},
//		}
//
//		// use mockedCompactor in code that requires tcompactor.Compactor
//		// and then make assertions.
//
//	}
type CompactorMock struct {
	// CompactWithBlockPopulatorWithWriteMetaFileFunc mocks the CompactWithBlockPopulatorWithWriteMetaFile method.
	CompactWithBlockPopulatorWithWriteMetaFileFunc func(dest string, dirs []string, open []*block.Block, blockPopulator lcompactor.BlockPopulator, writeMetaFileFn func(logger log.Logger, dir string, meta *tsdb.BlockMeta) (int64, error)) ([]ulid.ULID, error)

	// calls tracks calls to the methods.
	calls struct {
		// CompactWithBlockPopulatorWithWriteMetaFile holds details about calls to the CompactWithBlockPopulatorWithWriteMetaFile method.
		CompactWithBlockPopulatorWithWriteMetaFile []struct {
			// Dest is the dest argument value.
			Dest string
			// Dirs is the dirs argument value.
			Dirs []string
			// Open is the open argument value.
			Open []*block.Block
			// BlockPopulator is the blockPopulator argument value.
			BlockPopulator lcompactor.BlockPopulator
			// WriteMetaFileFn is the writeMetaFileFn argument value.
			WriteMetaFileFn func(logger log.Logger, dir string, meta *tsdb.BlockMeta) (int64, error)
		}
	}
	lockCompactWithBlockPopulatorWithWriteMetaFile sync.RWMutex
}

// CompactWithBlockPopulatorWithWriteMetaFile calls CompactWithBlockPopulatorWithWriteMetaFileFunc.
func (mock *CompactorMock) CompactWithBlockPopulatorWithWriteMetaFile(dest string, dirs []string, open []*block.Block, blockPopulator lcompactor.BlockPopulator, writeMetaFileFn func(logger log.Logger, dir string, meta *tsdb.BlockMeta) (int64, error)) ([]ulid.ULID, error) {
	if mock.CompactWithBlockPopulatorWithWriteMetaFileFunc == nil {
		panic("CompactorMock.CompactWithBlockPopulatorWithWriteMetaFileFunc: method is nil but Compactor.CompactWithBlockPopulatorWithWriteMetaFile was just called")
	}
	callInfo := struct {
		Dest            string
		Dirs            []string
		Open            []*block.Block
		BlockPopulator  lcompactor.BlockPopulator
		WriteMetaFileFn func(logger log.Logger, dir string, meta *tsdb.BlockMeta) (int64, error)
	}{
		Dest:            dest,
		Dirs:            dirs,
		Open:            open,
		BlockPopulator:  blockPopulator,
		WriteMetaFileFn: writeMetaFileFn,
	}
	mock.lockCompactWithBlockPopulatorWithWriteMetaFile.Lock()
	mock.calls.CompactWithBlockPopulatorWithWriteMetaFile = append(mock.calls.CompactWithBlockPopulatorWithWriteMetaFile, callInfo)
	mock.lockCompactWithBlockPopulatorWithWriteMetaFile.Unlock()
	return mock.CompactWithBlockPopulatorWithWriteMetaFileFunc(dest, dirs, open, blockPopulator, writeMetaFileFn)
}

// CompactWithBlockPopulatorWithWriteMetaFileCalls gets all the calls that were made to CompactWithBlockPopulatorWithWriteMetaFile.
// Check the length with:
//
//	len(mockedCompactor.CompactWithBlockPopulatorWithWriteMetaFileCalls())
func (mock *CompactorMock) CompactWithBlockPopulatorWithWriteMetaFileCalls() []struct {
	Dest            string
	Dirs            []string
	Open            []*block.Block
	BlockPopulator  lcompactor.BlockPopulator
	WriteMetaFileFn func(logger log.Logger, dir string, meta *tsdb.BlockMeta) (int64, error)
} {
	var calls []struct {
		Dest            string
		Dirs            []string
		Open            []*block.Block
		BlockPopulator  lcompactor.BlockPopulator
		WriteMetaFileFn func(logger log.Logger, dir string, meta *tsdb.BlockMeta) (int64, error)
	}
	mock.lockCompactWithBlockPopulatorWithWriteMetaFile.RLock()
	calls = mock.calls.CompactWithBlockPopulatorWithWriteMetaFile
	mock.lockCompactWithBlockPopulatorWithWriteMetaFile.RUnlock()
	return calls
}
