// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/thanos-io/thanos/pkg/block/metadata"
	"sync"
)

// PlannerMock is a mock implementation of tcompactor.Planner.
//
//	func TestSomethingThatUsesPlanner(t *testing.T) {
//
//		// make and configure a mocked tcompactor.Planner
//		mockedPlanner := &PlannerMock{
//			PlanFunc: func(ctx context.Context, metasByMinTime []*metadata.Meta) ([]*metadata.Meta, bool, error) {
//				panic("mock out the Plan method")
//			},
//		}
//
//		// use mockedPlanner in code that requires tcompactor.Planner
//		// and then make assertions.
//
//	}
type PlannerMock struct {
	// PlanFunc mocks the Plan method.
	PlanFunc func(ctx context.Context, metasByMinTime []*metadata.Meta) ([]*metadata.Meta, bool, error)

	// calls tracks calls to the methods.
	calls struct {
		// Plan holds details about calls to the Plan method.
		Plan []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// MetasByMinTime is the metasByMinTime argument value.
			MetasByMinTime []*metadata.Meta
		}
	}
	lockPlan sync.RWMutex
}

// Plan calls PlanFunc.
func (mock *PlannerMock) Plan(ctx context.Context, metasByMinTime []*metadata.Meta) ([]*metadata.Meta, bool, error) {
	if mock.PlanFunc == nil {
		panic("PlannerMock.PlanFunc: method is nil but Planner.Plan was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		MetasByMinTime []*metadata.Meta
	}{
		Ctx:            ctx,
		MetasByMinTime: metasByMinTime,
	}
	mock.lockPlan.Lock()
	mock.calls.Plan = append(mock.calls.Plan, callInfo)
	mock.lockPlan.Unlock()
	return mock.PlanFunc(ctx, metasByMinTime)
}

// PlanCalls gets all the calls that were made to Plan.
// Check the length with:
//
//	len(mockedPlanner.PlanCalls())
func (mock *PlannerMock) PlanCalls() []struct {
	Ctx            context.Context
	MetasByMinTime []*metadata.Meta
} {
	var calls []struct {
		Ctx            context.Context
		MetasByMinTime []*metadata.Meta
	}
	mock.lockPlan.RLock()
	calls = mock.calls.Plan
	mock.lockPlan.RUnlock()
	return calls
}
