// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"sync"
)

// ProtobufWriterMock is a mock implementation of remotewriter.ProtobufWriter.
//
//	func TestSomethingThatUsesProtobufWriter(t *testing.T) {
//
//		// make and configure a mocked remotewriter.ProtobufWriter
//		mockedProtobufWriter := &ProtobufWriterMock{
//			WriteFunc: func(ctx context.Context, data []byte) error {
//				panic("mock out the Write method")
//			},
//		}
//
//		// use mockedProtobufWriter in code that requires remotewriter.ProtobufWriter
//		// and then make assertions.
//
//	}
type ProtobufWriterMock struct {
	// WriteFunc mocks the Write method.
	WriteFunc func(ctx context.Context, data []byte) error

	// calls tracks calls to the methods.
	calls struct {
		// Write holds details about calls to the Write method.
		Write []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Data is the data argument value.
			Data []byte
		}
	}
	lockWrite sync.RWMutex
}

// Write calls WriteFunc.
func (mock *ProtobufWriterMock) Write(ctx context.Context, data []byte) error {
	if mock.WriteFunc == nil {
		panic("ProtobufWriterMock.WriteFunc: method is nil but ProtobufWriter.Write was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Data []byte
	}{
		Ctx:  ctx,
		Data: data,
	}
	mock.lockWrite.Lock()
	mock.calls.Write = append(mock.calls.Write, callInfo)
	mock.lockWrite.Unlock()
	return mock.WriteFunc(ctx, data)
}

// WriteCalls gets all the calls that were made to Write.
// Check the length with:
//
//	len(mockedProtobufWriter.WriteCalls())
func (mock *ProtobufWriterMock) WriteCalls() []struct {
	Ctx  context.Context
	Data []byte
} {
	var calls []struct {
		Ctx  context.Context
		Data []byte
	}
	mock.lockWrite.RLock()
	calls = mock.calls.Write
	mock.lockWrite.RUnlock()
	return calls
}
