// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"sync"
)

// TargetSegmentIDSetCloserMock is a mock implementation of remotewriter.TargetSegmentIDSetCloser.
//
//	func TestSomethingThatUsesTargetSegmentIDSetCloser(t *testing.T) {
//
//		// make and configure a mocked remotewriter.TargetSegmentIDSetCloser
//		mockedTargetSegmentIDSetCloser := &TargetSegmentIDSetCloserMock{
//			CloseFunc: func() error {
//				panic("mock out the Close method")
//			},
//			SetTargetSegmentIDFunc: func(segmentID uint32) error {
//				panic("mock out the SetTargetSegmentID method")
//			},
//		}
//
//		// use mockedTargetSegmentIDSetCloser in code that requires remotewriter.TargetSegmentIDSetCloser
//		// and then make assertions.
//
//	}
type TargetSegmentIDSetCloserMock struct {
	// CloseFunc mocks the Close method.
	CloseFunc func() error

	// SetTargetSegmentIDFunc mocks the SetTargetSegmentID method.
	SetTargetSegmentIDFunc func(segmentID uint32) error

	// calls tracks calls to the methods.
	calls struct {
		// Close holds details about calls to the Close method.
		Close []struct {
		}
		// SetTargetSegmentID holds details about calls to the SetTargetSegmentID method.
		SetTargetSegmentID []struct {
			// SegmentID is the segmentID argument value.
			SegmentID uint32
		}
	}
	lockClose              sync.RWMutex
	lockSetTargetSegmentID sync.RWMutex
}

// Close calls CloseFunc.
func (mock *TargetSegmentIDSetCloserMock) Close() error {
	if mock.CloseFunc == nil {
		panic("TargetSegmentIDSetCloserMock.CloseFunc: method is nil but TargetSegmentIDSetCloser.Close was just called")
	}
	callInfo := struct {
	}{}
	mock.lockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	mock.lockClose.Unlock()
	return mock.CloseFunc()
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//
//	len(mockedTargetSegmentIDSetCloser.CloseCalls())
func (mock *TargetSegmentIDSetCloserMock) CloseCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockClose.RLock()
	calls = mock.calls.Close
	mock.lockClose.RUnlock()
	return calls
}

// SetTargetSegmentID calls SetTargetSegmentIDFunc.
func (mock *TargetSegmentIDSetCloserMock) SetTargetSegmentID(segmentID uint32) error {
	if mock.SetTargetSegmentIDFunc == nil {
		panic("TargetSegmentIDSetCloserMock.SetTargetSegmentIDFunc: method is nil but TargetSegmentIDSetCloser.SetTargetSegmentID was just called")
	}
	callInfo := struct {
		SegmentID uint32
	}{
		SegmentID: segmentID,
	}
	mock.lockSetTargetSegmentID.Lock()
	mock.calls.SetTargetSegmentID = append(mock.calls.SetTargetSegmentID, callInfo)
	mock.lockSetTargetSegmentID.Unlock()
	return mock.SetTargetSegmentIDFunc(segmentID)
}

// SetTargetSegmentIDCalls gets all the calls that were made to SetTargetSegmentID.
// Check the length with:
//
//	len(mockedTargetSegmentIDSetCloser.SetTargetSegmentIDCalls())
func (mock *TargetSegmentIDSetCloserMock) SetTargetSegmentIDCalls() []struct {
	SegmentID uint32
} {
	var calls []struct {
		SegmentID uint32
	}
	mock.lockSetTargetSegmentID.RLock()
	calls = mock.calls.SetTargetSegmentID
	mock.lockSetTargetSegmentID.RUnlock()
	return calls
}
