version: "3"

networks:
  op-prometheus:
    driver: bridge

services:
  grafana:
    image: grafana/grafana-oss:10.0.3-ubuntu
    restart: on-failure
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    networks:
      - op-prometheus
    ports:
      - "3000:3000"
  prometheus:
    image: ${PROMETHEUS_IMAGE}
    restart: on-failure
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - op-prometheus
    ports:
      - "9090:9090"
