// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mediator_test

import (
	"github.com/prometheus/prometheus/pp/go/storage/mediator"
	"sync"
	"time"
)

// Ensure, that TimerMock does implement mediator.Timer.
// If this is not the case, regenerate this file with moq.
var _ mediator.Timer = &TimerMock{}

// TimerMock is a mock implementation of mediator.Timer.
//
//	func TestSomethingThatUsesTimer(t *testing.T) {
//
//		// make and configure a mocked mediator.Timer
//		mockedTimer := &TimerMock{
//			ChanFunc: func() <-chan time.Time {
//				panic("mock out the Chan method")
//			},
//			StopFunc: func()  {
//				panic("mock out the Stop method")
//			},
//		}
//
//		// use mockedTimer in code that requires mediator.Timer
//		// and then make assertions.
//
//	}
type TimerMock struct {
	// ChanFunc mocks the Chan method.
	ChanFunc func() <-chan time.Time

	// StopFunc mocks the Stop method.
	StopFunc func()

	// calls tracks calls to the methods.
	calls struct {
		// Chan holds details about calls to the Chan method.
		Chan []struct {
		}
		// Stop holds details about calls to the Stop method.
		Stop []struct {
		}
	}
	lockChan sync.RWMutex
	lockStop sync.RWMutex
}

// Chan calls ChanFunc.
func (mock *TimerMock) Chan() <-chan time.Time {
	if mock.ChanFunc == nil {
		panic("TimerMock.ChanFunc: method is nil but Timer.Chan was just called")
	}
	callInfo := struct {
	}{}
	mock.lockChan.Lock()
	mock.calls.Chan = append(mock.calls.Chan, callInfo)
	mock.lockChan.Unlock()
	return mock.ChanFunc()
}

// ChanCalls gets all the calls that were made to Chan.
// Check the length with:
//
//	len(mockedTimer.ChanCalls())
func (mock *TimerMock) ChanCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockChan.RLock()
	calls = mock.calls.Chan
	mock.lockChan.RUnlock()
	return calls
}

// Stop calls StopFunc.
func (mock *TimerMock) Stop() {
	if mock.StopFunc == nil {
		panic("TimerMock.StopFunc: method is nil but Timer.Stop was just called")
	}
	callInfo := struct {
	}{}
	mock.lockStop.Lock()
	mock.calls.Stop = append(mock.calls.Stop, callInfo)
	mock.lockStop.Unlock()
	mock.StopFunc()
}

// StopCalls gets all the calls that were made to Stop.
// Check the length with:
//
//	len(mockedTimer.StopCalls())
func (mock *TimerMock) StopCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockStop.RLock()
	calls = mock.calls.Stop
	mock.lockStop.RUnlock()
	return calls
}
