// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mediator_test

import (
	"sync"
	"time"
)

// TimerMock is a mock implementation of mediator.Timer.
//
//	func TestSomethingThatUsesTimer(t *testing.T) {
//
//		// make and configure a mocked mediator.Timer
//		mockedTimer := &TimerMock{
//			ChanFunc: func() <-chan time.Time {
//				panic("mock out the Chan method")
//			},
//			ResetFunc: func()  {
//				panic("mock out the Reset method")
//			},
//			StopFunc: func()  {
//				panic("mock out the Stop method")
//			},
//		}
//
//		// use mockedTimer in code that requires mediator.Timer
//		// and then make assertions.
//
//	}
type TimerMock struct {
	// ChanFunc mocks the Chan method.
	ChanFunc func() <-chan time.Time

	// ResetFunc mocks the Reset method.
	ResetFunc func()

	// StopFunc mocks the Stop method.
	StopFunc func()

	// calls tracks calls to the methods.
	calls struct {
		// Chan holds details about calls to the Chan method.
		Chan []struct {
		}
		// Reset holds details about calls to the Reset method.
		Reset []struct {
		}
		// Stop holds details about calls to the Stop method.
		Stop []struct {
		}
	}
	lockChan  sync.RWMutex
	lockReset sync.RWMutex
	lockStop  sync.RWMutex
}

// Chan calls ChanFunc.
func (mock *TimerMock) Chan() <-chan time.Time {
	if mock.ChanFunc == nil {
		panic("TimerMock.ChanFunc: method is nil but Timer.Chan was just called")
	}
	callInfo := struct {
	}{}
	mock.lockChan.Lock()
	mock.calls.Chan = append(mock.calls.Chan, callInfo)
	mock.lockChan.Unlock()
	return mock.ChanFunc()
}

// ChanCalls gets all the calls that were made to Chan.
// Check the length with:
//
//	len(mockedTimer.ChanCalls())
func (mock *TimerMock) ChanCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockChan.RLock()
	calls = mock.calls.Chan
	mock.lockChan.RUnlock()
	return calls
}

// Reset calls ResetFunc.
func (mock *TimerMock) Reset() {
	if mock.ResetFunc == nil {
		panic("TimerMock.ResetFunc: method is nil but Timer.Reset was just called")
	}
	callInfo := struct {
	}{}
	mock.lockReset.Lock()
	mock.calls.Reset = append(mock.calls.Reset, callInfo)
	mock.lockReset.Unlock()
	mock.ResetFunc()
}

// ResetCalls gets all the calls that were made to Reset.
// Check the length with:
//
//	len(mockedTimer.ResetCalls())
func (mock *TimerMock) ResetCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockReset.RLock()
	calls = mock.calls.Reset
	mock.lockReset.RUnlock()
	return calls
}

// Stop calls StopFunc.
func (mock *TimerMock) Stop() {
	if mock.StopFunc == nil {
		panic("TimerMock.StopFunc: method is nil but Timer.Stop was just called")
	}
	callInfo := struct {
	}{}
	mock.lockStop.Lock()
	mock.calls.Stop = append(mock.calls.Stop, callInfo)
	mock.lockStop.Unlock()
	mock.StopFunc()
}

// StopCalls gets all the calls that were made to Stop.
// Check the length with:
//
//	len(mockedTimer.StopCalls())
func (mock *TimerMock) StopCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockStop.RLock()
	calls = mock.calls.Stop
	mock.lockStop.RUnlock()
	return calls
}
