{{- $secret := dict "auths" dict -}}
{{- range $registry, $auth := .Values.registrysecret -}}
{{- $_ := set $secret.auths $registry (dict "auth" ($auth | b64enc)) -}}
{{- end -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: registrysecret-prometheus-pp
  annotations:
    helm.sh/hook: pre-install
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ $secret | toJson | b64enc }}
