// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"github.com/prometheus/prometheus/pp/go/storage/head/shard"
	"sync"
)

// AppendFileMock is a mock implementation of AppendFile.
//
//	func TestSomethingThatUsesAppendFile(t *testing.T) {
//
//		// make and configure a mocked AppendFile
//		mockedAppendFile := &AppendFileMock{
//			CloseFunc: func() error {
//				panic("mock out the Close method")
//			},
//			IsEmptyFunc: func() bool {
//				panic("mock out the IsEmpty method")
//			},
//			OpenFunc: func() error {
//				panic("mock out the Open method")
//			},
//			ReaderFunc: func() (shard.StorageReader, error) {
//				panic("mock out the Reader method")
//			},
//			SyncFunc: func() error {
//				panic("mock out the Sync method")
//			},
//			WriteFunc: func(p []byte) (int, error) {
//				panic("mock out the Write method")
//			},
//		}
//
//		// use mockedAppendFile in code that requires AppendFile
//		// and then make assertions.
//
//	}
type AppendFileMock struct {
	// CloseFunc mocks the Close method.
	CloseFunc func() error

	// IsEmptyFunc mocks the IsEmpty method.
	IsEmptyFunc func() bool

	// OpenFunc mocks the Open method.
	OpenFunc func() error

	// ReaderFunc mocks the Reader method.
	ReaderFunc func() (shard.StorageReader, error)

	// SyncFunc mocks the Sync method.
	SyncFunc func() error

	// WriteFunc mocks the Write method.
	WriteFunc func(p []byte) (int, error)

	// calls tracks calls to the methods.
	calls struct {
		// Close holds details about calls to the Close method.
		Close []struct {
		}
		// IsEmpty holds details about calls to the IsEmpty method.
		IsEmpty []struct {
		}
		// Open holds details about calls to the Open method.
		Open []struct {
		}
		// Reader holds details about calls to the Reader method.
		Reader []struct {
		}
		// Sync holds details about calls to the Sync method.
		Sync []struct {
		}
		// Write holds details about calls to the Write method.
		Write []struct {
			// P is the p argument value.
			P []byte
		}
	}
	lockClose   sync.RWMutex
	lockIsEmpty sync.RWMutex
	lockOpen    sync.RWMutex
	lockReader  sync.RWMutex
	lockSync    sync.RWMutex
	lockWrite   sync.RWMutex
}

// Close calls CloseFunc.
func (mock *AppendFileMock) Close() error {
	if mock.CloseFunc == nil {
		panic("AppendFileMock.CloseFunc: method is nil but AppendFile.Close was just called")
	}
	callInfo := struct {
	}{}
	mock.lockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	mock.lockClose.Unlock()
	return mock.CloseFunc()
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//
//	len(mockedAppendFile.CloseCalls())
func (mock *AppendFileMock) CloseCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockClose.RLock()
	calls = mock.calls.Close
	mock.lockClose.RUnlock()
	return calls
}

// IsEmpty calls IsEmptyFunc.
func (mock *AppendFileMock) IsEmpty() bool {
	if mock.IsEmptyFunc == nil {
		panic("AppendFileMock.IsEmptyFunc: method is nil but AppendFile.IsEmpty was just called")
	}
	callInfo := struct {
	}{}
	mock.lockIsEmpty.Lock()
	mock.calls.IsEmpty = append(mock.calls.IsEmpty, callInfo)
	mock.lockIsEmpty.Unlock()
	return mock.IsEmptyFunc()
}

// IsEmptyCalls gets all the calls that were made to IsEmpty.
// Check the length with:
//
//	len(mockedAppendFile.IsEmptyCalls())
func (mock *AppendFileMock) IsEmptyCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockIsEmpty.RLock()
	calls = mock.calls.IsEmpty
	mock.lockIsEmpty.RUnlock()
	return calls
}

// Open calls OpenFunc.
func (mock *AppendFileMock) Open() error {
	if mock.OpenFunc == nil {
		panic("AppendFileMock.OpenFunc: method is nil but AppendFile.Open was just called")
	}
	callInfo := struct {
	}{}
	mock.lockOpen.Lock()
	mock.calls.Open = append(mock.calls.Open, callInfo)
	mock.lockOpen.Unlock()
	return mock.OpenFunc()
}

// OpenCalls gets all the calls that were made to Open.
// Check the length with:
//
//	len(mockedAppendFile.OpenCalls())
func (mock *AppendFileMock) OpenCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockOpen.RLock()
	calls = mock.calls.Open
	mock.lockOpen.RUnlock()
	return calls
}

// Reader calls ReaderFunc.
func (mock *AppendFileMock) Reader() (shard.StorageReader, error) {
	if mock.ReaderFunc == nil {
		panic("AppendFileMock.ReaderFunc: method is nil but AppendFile.Reader was just called")
	}
	callInfo := struct {
	}{}
	mock.lockReader.Lock()
	mock.calls.Reader = append(mock.calls.Reader, callInfo)
	mock.lockReader.Unlock()
	return mock.ReaderFunc()
}

// ReaderCalls gets all the calls that were made to Reader.
// Check the length with:
//
//	len(mockedAppendFile.ReaderCalls())
func (mock *AppendFileMock) ReaderCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockReader.RLock()
	calls = mock.calls.Reader
	mock.lockReader.RUnlock()
	return calls
}

// Sync calls SyncFunc.
func (mock *AppendFileMock) Sync() error {
	if mock.SyncFunc == nil {
		panic("AppendFileMock.SyncFunc: method is nil but AppendFile.Sync was just called")
	}
	callInfo := struct {
	}{}
	mock.lockSync.Lock()
	mock.calls.Sync = append(mock.calls.Sync, callInfo)
	mock.lockSync.Unlock()
	return mock.SyncFunc()
}

// SyncCalls gets all the calls that were made to Sync.
// Check the length with:
//
//	len(mockedAppendFile.SyncCalls())
func (mock *AppendFileMock) SyncCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockSync.RLock()
	calls = mock.calls.Sync
	mock.lockSync.RUnlock()
	return calls
}

// Write calls WriteFunc.
func (mock *AppendFileMock) Write(p []byte) (int, error) {
	if mock.WriteFunc == nil {
		panic("AppendFileMock.WriteFunc: method is nil but AppendFile.Write was just called")
	}
	callInfo := struct {
		P []byte
	}{
		P: p,
	}
	mock.lockWrite.Lock()
	mock.calls.Write = append(mock.calls.Write, callInfo)
	mock.lockWrite.Unlock()
	return mock.WriteFunc(p)
}

// WriteCalls gets all the calls that were made to Write.
// Check the length with:
//
//	len(mockedAppendFile.WriteCalls())
func (mock *AppendFileMock) WriteCalls() []struct {
	P []byte
} {
	var calls []struct {
		P []byte
	}
	mock.lockWrite.RLock()
	calls = mock.calls.Write
	mock.lockWrite.RUnlock()
	return calls
}
