// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"sync"
)

// StorageFileMock is a mock implementation of StorageFile.
//
//	func TestSomethingThatUsesStorageFile(t *testing.T) {
//
//		// make and configure a mocked StorageFile
//		mockedStorageFile := &StorageFileMock{
//			CloseFunc: func() error {
//				panic("mock out the Close method")
//			},
//			IsEmptyFunc: func() bool {
//				panic("mock out the IsEmpty method")
//			},
//			OpenFunc: func(flags int) error {
//				panic("mock out the Open method")
//			},
//			ReadFunc: func(p []byte) (int, error) {
//				panic("mock out the Read method")
//			},
//			ReadAtFunc: func(p []byte, off int64) (int, error) {
//				panic("mock out the ReadAt method")
//			},
//			SeekFunc: func(offset int64, whence int) (int64, error) {
//				panic("mock out the Seek method")
//			},
//			SyncFunc: func() error {
//				panic("mock out the Sync method")
//			},
//			TruncateFunc: func(size int64) error {
//				panic("mock out the Truncate method")
//			},
//			WriteFunc: func(p []byte) (int, error) {
//				panic("mock out the Write method")
//			},
//		}
//
//		// use mockedStorageFile in code that requires StorageFile
//		// and then make assertions.
//
//	}
type StorageFileMock struct {
	// CloseFunc mocks the Close method.
	CloseFunc func() error

	// IsEmptyFunc mocks the IsEmpty method.
	IsEmptyFunc func() bool

	// OpenFunc mocks the Open method.
	OpenFunc func(flags int) error

	// ReadFunc mocks the Read method.
	ReadFunc func(p []byte) (int, error)

	// ReadAtFunc mocks the ReadAt method.
	ReadAtFunc func(p []byte, off int64) (int, error)

	// SeekFunc mocks the Seek method.
	SeekFunc func(offset int64, whence int) (int64, error)

	// SyncFunc mocks the Sync method.
	SyncFunc func() error

	// TruncateFunc mocks the Truncate method.
	TruncateFunc func(size int64) error

	// WriteFunc mocks the Write method.
	WriteFunc func(p []byte) (int, error)

	// calls tracks calls to the methods.
	calls struct {
		// Close holds details about calls to the Close method.
		Close []struct {
		}
		// IsEmpty holds details about calls to the IsEmpty method.
		IsEmpty []struct {
		}
		// Open holds details about calls to the Open method.
		Open []struct {
			// Flags is the flags argument value.
			Flags int
		}
		// Read holds details about calls to the Read method.
		Read []struct {
			// P is the p argument value.
			P []byte
		}
		// ReadAt holds details about calls to the ReadAt method.
		ReadAt []struct {
			// P is the p argument value.
			P []byte
			// Off is the off argument value.
			Off int64
		}
		// Seek holds details about calls to the Seek method.
		Seek []struct {
			// Offset is the offset argument value.
			Offset int64
			// Whence is the whence argument value.
			Whence int
		}
		// Sync holds details about calls to the Sync method.
		Sync []struct {
		}
		// Truncate holds details about calls to the Truncate method.
		Truncate []struct {
			// Size is the size argument value.
			Size int64
		}
		// Write holds details about calls to the Write method.
		Write []struct {
			// P is the p argument value.
			P []byte
		}
	}
	lockClose    sync.RWMutex
	lockIsEmpty  sync.RWMutex
	lockOpen     sync.RWMutex
	lockRead     sync.RWMutex
	lockReadAt   sync.RWMutex
	lockSeek     sync.RWMutex
	lockSync     sync.RWMutex
	lockTruncate sync.RWMutex
	lockWrite    sync.RWMutex
}

// Close calls CloseFunc.
func (mock *StorageFileMock) Close() error {
	if mock.CloseFunc == nil {
		panic("StorageFileMock.CloseFunc: method is nil but StorageFile.Close was just called")
	}
	callInfo := struct {
	}{}
	mock.lockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	mock.lockClose.Unlock()
	return mock.CloseFunc()
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//
//	len(mockedStorageFile.CloseCalls())
func (mock *StorageFileMock) CloseCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockClose.RLock()
	calls = mock.calls.Close
	mock.lockClose.RUnlock()
	return calls
}

// IsEmpty calls IsEmptyFunc.
func (mock *StorageFileMock) IsEmpty() bool {
	if mock.IsEmptyFunc == nil {
		panic("StorageFileMock.IsEmptyFunc: method is nil but StorageFile.IsEmpty was just called")
	}
	callInfo := struct {
	}{}
	mock.lockIsEmpty.Lock()
	mock.calls.IsEmpty = append(mock.calls.IsEmpty, callInfo)
	mock.lockIsEmpty.Unlock()
	return mock.IsEmptyFunc()
}

// IsEmptyCalls gets all the calls that were made to IsEmpty.
// Check the length with:
//
//	len(mockedStorageFile.IsEmptyCalls())
func (mock *StorageFileMock) IsEmptyCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockIsEmpty.RLock()
	calls = mock.calls.IsEmpty
	mock.lockIsEmpty.RUnlock()
	return calls
}

// Open calls OpenFunc.
func (mock *StorageFileMock) Open(flags int) error {
	if mock.OpenFunc == nil {
		panic("StorageFileMock.OpenFunc: method is nil but StorageFile.Open was just called")
	}
	callInfo := struct {
		Flags int
	}{
		Flags: flags,
	}
	mock.lockOpen.Lock()
	mock.calls.Open = append(mock.calls.Open, callInfo)
	mock.lockOpen.Unlock()
	return mock.OpenFunc(flags)
}

// OpenCalls gets all the calls that were made to Open.
// Check the length with:
//
//	len(mockedStorageFile.OpenCalls())
func (mock *StorageFileMock) OpenCalls() []struct {
	Flags int
} {
	var calls []struct {
		Flags int
	}
	mock.lockOpen.RLock()
	calls = mock.calls.Open
	mock.lockOpen.RUnlock()
	return calls
}

// Read calls ReadFunc.
func (mock *StorageFileMock) Read(p []byte) (int, error) {
	if mock.ReadFunc == nil {
		panic("StorageFileMock.ReadFunc: method is nil but StorageFile.Read was just called")
	}
	callInfo := struct {
		P []byte
	}{
		P: p,
	}
	mock.lockRead.Lock()
	mock.calls.Read = append(mock.calls.Read, callInfo)
	mock.lockRead.Unlock()
	return mock.ReadFunc(p)
}

// ReadCalls gets all the calls that were made to Read.
// Check the length with:
//
//	len(mockedStorageFile.ReadCalls())
func (mock *StorageFileMock) ReadCalls() []struct {
	P []byte
} {
	var calls []struct {
		P []byte
	}
	mock.lockRead.RLock()
	calls = mock.calls.Read
	mock.lockRead.RUnlock()
	return calls
}

// ReadAt calls ReadAtFunc.
func (mock *StorageFileMock) ReadAt(p []byte, off int64) (int, error) {
	if mock.ReadAtFunc == nil {
		panic("StorageFileMock.ReadAtFunc: method is nil but StorageFile.ReadAt was just called")
	}
	callInfo := struct {
		P   []byte
		Off int64
	}{
		P:   p,
		Off: off,
	}
	mock.lockReadAt.Lock()
	mock.calls.ReadAt = append(mock.calls.ReadAt, callInfo)
	mock.lockReadAt.Unlock()
	return mock.ReadAtFunc(p, off)
}

// ReadAtCalls gets all the calls that were made to ReadAt.
// Check the length with:
//
//	len(mockedStorageFile.ReadAtCalls())
func (mock *StorageFileMock) ReadAtCalls() []struct {
	P   []byte
	Off int64
} {
	var calls []struct {
		P   []byte
		Off int64
	}
	mock.lockReadAt.RLock()
	calls = mock.calls.ReadAt
	mock.lockReadAt.RUnlock()
	return calls
}

// Seek calls SeekFunc.
func (mock *StorageFileMock) Seek(offset int64, whence int) (int64, error) {
	if mock.SeekFunc == nil {
		panic("StorageFileMock.SeekFunc: method is nil but StorageFile.Seek was just called")
	}
	callInfo := struct {
		Offset int64
		Whence int
	}{
		Offset: offset,
		Whence: whence,
	}
	mock.lockSeek.Lock()
	mock.calls.Seek = append(mock.calls.Seek, callInfo)
	mock.lockSeek.Unlock()
	return mock.SeekFunc(offset, whence)
}

// SeekCalls gets all the calls that were made to Seek.
// Check the length with:
//
//	len(mockedStorageFile.SeekCalls())
func (mock *StorageFileMock) SeekCalls() []struct {
	Offset int64
	Whence int
} {
	var calls []struct {
		Offset int64
		Whence int
	}
	mock.lockSeek.RLock()
	calls = mock.calls.Seek
	mock.lockSeek.RUnlock()
	return calls
}

// Sync calls SyncFunc.
func (mock *StorageFileMock) Sync() error {
	if mock.SyncFunc == nil {
		panic("StorageFileMock.SyncFunc: method is nil but StorageFile.Sync was just called")
	}
	callInfo := struct {
	}{}
	mock.lockSync.Lock()
	mock.calls.Sync = append(mock.calls.Sync, callInfo)
	mock.lockSync.Unlock()
	return mock.SyncFunc()
}

// SyncCalls gets all the calls that were made to Sync.
// Check the length with:
//
//	len(mockedStorageFile.SyncCalls())
func (mock *StorageFileMock) SyncCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockSync.RLock()
	calls = mock.calls.Sync
	mock.lockSync.RUnlock()
	return calls
}

// Truncate calls TruncateFunc.
func (mock *StorageFileMock) Truncate(size int64) error {
	if mock.TruncateFunc == nil {
		panic("StorageFileMock.TruncateFunc: method is nil but StorageFile.Truncate was just called")
	}
	callInfo := struct {
		Size int64
	}{
		Size: size,
	}
	mock.lockTruncate.Lock()
	mock.calls.Truncate = append(mock.calls.Truncate, callInfo)
	mock.lockTruncate.Unlock()
	return mock.TruncateFunc(size)
}

// TruncateCalls gets all the calls that were made to Truncate.
// Check the length with:
//
//	len(mockedStorageFile.TruncateCalls())
func (mock *StorageFileMock) TruncateCalls() []struct {
	Size int64
} {
	var calls []struct {
		Size int64
	}
	mock.lockTruncate.RLock()
	calls = mock.calls.Truncate
	mock.lockTruncate.RUnlock()
	return calls
}

// Write calls WriteFunc.
func (mock *StorageFileMock) Write(p []byte) (int, error) {
	if mock.WriteFunc == nil {
		panic("StorageFileMock.WriteFunc: method is nil but StorageFile.Write was just called")
	}
	callInfo := struct {
		P []byte
	}{
		P: p,
	}
	mock.lockWrite.Lock()
	mock.calls.Write = append(mock.calls.Write, callInfo)
	mock.lockWrite.Unlock()
	return mock.WriteFunc(p)
}

// WriteCalls gets all the calls that were made to Write.
// Check the length with:
//
//	len(mockedStorageFile.WriteCalls())
func (mock *StorageFileMock) WriteCalls() []struct {
	P []byte
} {
	var calls []struct {
		P []byte
	}
	mock.lockWrite.RLock()
	calls = mock.calls.Write
	mock.lockWrite.RUnlock()
	return calls
}
