// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"sync"
	"time"
)

// HeadInformerMock is a mock implementation of services.HeadInformer.
//
//	func TestSomethingThatUsesHeadInformer(t *testing.T) {
//
//		// make and configure a mocked services.HeadInformer
//		mockedHeadInformer := &HeadInformerMock{
//			CreatedAtFunc: func(headID string) time.Duration {
//				panic("mock out the CreatedAt method")
//			},
//			SetActiveStatusFunc: func(headID string) error {
//				panic("mock out the SetActiveStatus method")
//			},
//			SetRotatedStatusFunc: func(headID string) error {
//				panic("mock out the SetRotatedStatus method")
//			},
//		}
//
//		// use mockedHeadInformer in code that requires services.HeadInformer
//		// and then make assertions.
//
//	}
type HeadInformerMock struct {
	// CreatedAtFunc mocks the CreatedAt method.
	CreatedAtFunc func(headID string) time.Duration

	// SetActiveStatusFunc mocks the SetActiveStatus method.
	SetActiveStatusFunc func(headID string) error

	// SetRotatedStatusFunc mocks the SetRotatedStatus method.
	SetRotatedStatusFunc func(headID string) error

	// calls tracks calls to the methods.
	calls struct {
		// CreatedAt holds details about calls to the CreatedAt method.
		CreatedAt []struct {
			// HeadID is the headID argument value.
			HeadID string
		}
		// SetActiveStatus holds details about calls to the SetActiveStatus method.
		SetActiveStatus []struct {
			// HeadID is the headID argument value.
			HeadID string
		}
		// SetRotatedStatus holds details about calls to the SetRotatedStatus method.
		SetRotatedStatus []struct {
			// HeadID is the headID argument value.
			HeadID string
		}
	}
	lockCreatedAt        sync.RWMutex
	lockSetActiveStatus  sync.RWMutex
	lockSetRotatedStatus sync.RWMutex
}

// CreatedAt calls CreatedAtFunc.
func (mock *HeadInformerMock) CreatedAt(headID string) time.Duration {
	if mock.CreatedAtFunc == nil {
		panic("HeadInformerMock.CreatedAtFunc: method is nil but HeadInformer.CreatedAt was just called")
	}
	callInfo := struct {
		HeadID string
	}{
		HeadID: headID,
	}
	mock.lockCreatedAt.Lock()
	mock.calls.CreatedAt = append(mock.calls.CreatedAt, callInfo)
	mock.lockCreatedAt.Unlock()
	return mock.CreatedAtFunc(headID)
}

// CreatedAtCalls gets all the calls that were made to CreatedAt.
// Check the length with:
//
//	len(mockedHeadInformer.CreatedAtCalls())
func (mock *HeadInformerMock) CreatedAtCalls() []struct {
	HeadID string
} {
	var calls []struct {
		HeadID string
	}
	mock.lockCreatedAt.RLock()
	calls = mock.calls.CreatedAt
	mock.lockCreatedAt.RUnlock()
	return calls
}

// SetActiveStatus calls SetActiveStatusFunc.
func (mock *HeadInformerMock) SetActiveStatus(headID string) error {
	if mock.SetActiveStatusFunc == nil {
		panic("HeadInformerMock.SetActiveStatusFunc: method is nil but HeadInformer.SetActiveStatus was just called")
	}
	callInfo := struct {
		HeadID string
	}{
		HeadID: headID,
	}
	mock.lockSetActiveStatus.Lock()
	mock.calls.SetActiveStatus = append(mock.calls.SetActiveStatus, callInfo)
	mock.lockSetActiveStatus.Unlock()
	return mock.SetActiveStatusFunc(headID)
}

// SetActiveStatusCalls gets all the calls that were made to SetActiveStatus.
// Check the length with:
//
//	len(mockedHeadInformer.SetActiveStatusCalls())
func (mock *HeadInformerMock) SetActiveStatusCalls() []struct {
	HeadID string
} {
	var calls []struct {
		HeadID string
	}
	mock.lockSetActiveStatus.RLock()
	calls = mock.calls.SetActiveStatus
	mock.lockSetActiveStatus.RUnlock()
	return calls
}

// SetRotatedStatus calls SetRotatedStatusFunc.
func (mock *HeadInformerMock) SetRotatedStatus(headID string) error {
	if mock.SetRotatedStatusFunc == nil {
		panic("HeadInformerMock.SetRotatedStatusFunc: method is nil but HeadInformer.SetRotatedStatus was just called")
	}
	callInfo := struct {
		HeadID string
	}{
		HeadID: headID,
	}
	mock.lockSetRotatedStatus.Lock()
	mock.calls.SetRotatedStatus = append(mock.calls.SetRotatedStatus, callInfo)
	mock.lockSetRotatedStatus.Unlock()
	return mock.SetRotatedStatusFunc(headID)
}

// SetRotatedStatusCalls gets all the calls that were made to SetRotatedStatus.
// Check the length with:
//
//	len(mockedHeadInformer.SetRotatedStatusCalls())
func (mock *HeadInformerMock) SetRotatedStatusCalls() []struct {
	HeadID string
} {
	var calls []struct {
		HeadID string
	}
	mock.lockSetRotatedStatus.RLock()
	calls = mock.calls.SetRotatedStatus
	mock.lockSetRotatedStatus.RUnlock()
	return calls
}
