// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"github.com/prometheus/prometheus/pp/go/storage/head/services"
	"sync"
)

// HeadBuilderMock is a mock implementation of services.HeadBuilder.
//
//	func TestSomethingThatUsesHeadBuilder(t *testing.T) {
//
//		// make and configure a mocked services.HeadBuilder
//		mockedHeadBuilder := &HeadBuilderMock{
//			BuildFunc: func(generation uint64, numberOfShards uint16) (THead, error) {
//				panic("mock out the Build method")
//			},
//		}
//
//		// use mockedHeadBuilder in code that requires services.HeadBuilder
//		// and then make assertions.
//
//	}
type HeadBuilderMock[TTask services.Task, TShard services.Shard, TGoShard services.Shard, THead services.Head[TTask, TShard, TGoShard]] struct {
	// BuildFunc mocks the Build method.
	BuildFunc func(generation uint64, numberOfShards uint16) (THead, error)

	// calls tracks calls to the methods.
	calls struct {
		// Build holds details about calls to the Build method.
		Build []struct {
			// Generation is the generation argument value.
			Generation uint64
			// NumberOfShards is the numberOfShards argument value.
			NumberOfShards uint16
		}
	}
	lockBuild sync.RWMutex
}

// Build calls BuildFunc.
func (mock *HeadBuilderMock[TTask, TShard, TGoShard, THead]) Build(generation uint64, numberOfShards uint16) (THead, error) {
	if mock.BuildFunc == nil {
		panic("HeadBuilderMock.BuildFunc: method is nil but HeadBuilder.Build was just called")
	}
	callInfo := struct {
		Generation     uint64
		NumberOfShards uint16
	}{
		Generation:     generation,
		NumberOfShards: numberOfShards,
	}
	mock.lockBuild.Lock()
	mock.calls.Build = append(mock.calls.Build, callInfo)
	mock.lockBuild.Unlock()
	return mock.BuildFunc(generation, numberOfShards)
}

// BuildCalls gets all the calls that were made to Build.
// Check the length with:
//
//	len(mockedHeadBuilder.BuildCalls())
func (mock *HeadBuilderMock[TTask, TShard, TGoShard, THead]) BuildCalls() []struct {
	Generation     uint64
	NumberOfShards uint16
} {
	var calls []struct {
		Generation     uint64
		NumberOfShards uint16
	}
	mock.lockBuild.RLock()
	calls = mock.calls.Build
	mock.lockBuild.RUnlock()
	return calls
}
