// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"sync"
)

// MediatorMock is a mock implementation of services.Mediator.
//
//	func TestSomethingThatUsesMediator(t *testing.T) {
//
//		// make and configure a mocked services.Mediator
//		mockedMediator := &MediatorMock{
//			CFunc: func() <-chan struct{} {
//				panic("mock out the C method")
//			},
//		}
//
//		// use mockedMediator in code that requires services.Mediator
//		// and then make assertions.
//
//	}
type MediatorMock struct {
	// CFunc mocks the C method.
	CFunc func() <-chan struct{}

	// calls tracks calls to the methods.
	calls struct {
		// C holds details about calls to the C method.
		C []struct {
		}
	}
	lockC sync.RWMutex
}

// C calls CFunc.
func (mock *MediatorMock) C() <-chan struct{} {
	if mock.CFunc == nil {
		panic("MediatorMock.CFunc: method is nil but Mediator.C was just called")
	}
	callInfo := struct {
	}{}
	mock.lockC.Lock()
	mock.calls.C = append(mock.calls.C, callInfo)
	mock.lockC.Unlock()
	return mock.CFunc()
}

// CCalls gets all the calls that were made to C.
// Check the length with:
//
//	len(mockedMediator.CCalls())
func (mock *MediatorMock) CCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockC.RLock()
	calls = mock.calls.C
	mock.lockC.RUnlock()
	return calls
}
