// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"github.com/prometheus/prometheus/pp/go/storage/block"
	"github.com/prometheus/prometheus/pp/go/storage/head/services"
	"sync"
)

// HeadBlockWriterMock is a mock implementation of services.HeadBlockWriter.
//
//	func TestSomethingThatUsesHeadBlockWriter(t *testing.T) {
//
//		// make and configure a mocked services.HeadBlockWriter
//		mockedHeadBlockWriter := &HeadBlockWriterMock{
//			WriteFunc: func(shard TShard) ([]block.WrittenBlock, error) {
//				panic("mock out the Write method")
//			},
//		}
//
//		// use mockedHeadBlockWriter in code that requires services.HeadBlockWriter
//		// and then make assertions.
//
//	}
type HeadBlockWriterMock[TShard services.Shard] struct {
	// WriteFunc mocks the Write method.
	WriteFunc func(shard TShard) ([]block.WrittenBlock, error)

	// calls tracks calls to the methods.
	calls struct {
		// Write holds details about calls to the Write method.
		Write []struct {
			// Shard is the shard argument value.
			Shard TShard
		}
	}
	lockWrite sync.RWMutex
}

// Write calls WriteFunc.
func (mock *HeadBlockWriterMock[TShard]) Write(shard TShard) ([]block.WrittenBlock, error) {
	if mock.WriteFunc == nil {
		panic("HeadBlockWriterMock.WriteFunc: method is nil but HeadBlockWriter.Write was just called")
	}
	callInfo := struct {
		Shard TShard
	}{
		Shard: shard,
	}
	mock.lockWrite.Lock()
	mock.calls.Write = append(mock.calls.Write, callInfo)
	mock.lockWrite.Unlock()
	return mock.WriteFunc(shard)
}

// WriteCalls gets all the calls that were made to Write.
// Check the length with:
//
//	len(mockedHeadBlockWriter.WriteCalls())
func (mock *HeadBlockWriterMock[TShard]) WriteCalls() []struct {
	Shard TShard
} {
	var calls []struct {
		Shard TShard
	}
	mock.lockWrite.RLock()
	calls = mock.calls.Write
	mock.lockWrite.RUnlock()
	return calls
}
