// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"github.com/prometheus/prometheus/pp/go/storage/block"
	"github.com/prometheus/prometheus/pp/go/storage/head/services"
	"sync"
)

// HeadBlockWriterMock is a mock implementation of services.HeadBlockWriter.
//
//	func TestSomethingThatUsesHeadBlockWriter(t *testing.T) {
//
//		// make and configure a mocked services.HeadBlockWriter
//		mockedHeadBlockWriter := &HeadBlockWriterMock{
//			WriteFunc: func(shard TShard) ([]block.WrittenBlock, error) {
//				panic("mock out the Write method")
//			},
//		}
//
//		// use mockedHeadBlockWriter in code that requires services.HeadBlockWriter
//		// and then make assertions.
//
//	}
type HeadBlockWriterMock[TShard services.Shard] struct {
	// WriteFunc mocks the Write method.
	WriteFunc func(shard TShard) ([]block.WrittenBlock, error)

	// calls tracks calls to the methods.
	calls struct {
		// Write holds details about calls to the Write method.
		Write []struct {
			// Shard is the shard argument value.
			Shard TShard
		}
	}
	lockWrite sync.RWMutex
}

// Write calls WriteFunc.
func (mock *HeadBlockWriterMock[TShard]) Write(shard TShard) ([]block.WrittenBlock, error) {
	if mock.WriteFunc == nil {
		panic("HeadBlockWriterMock.WriteFunc: method is nil but HeadBlockWriter.Write was just called")
	}
	callInfo := struct {
		Shard TShard
	}{
		Shard: shard,
	}
	mock.lockWrite.Lock()
	mock.calls.Write = append(mock.calls.Write, callInfo)
	mock.lockWrite.Unlock()
	return mock.WriteFunc(shard)
}

// WriteCalls gets all the calls that were made to Write.
// Check the length with:
//
//	len(mockedHeadBlockWriter.WriteCalls())
func (mock *HeadBlockWriterMock[TShard]) WriteCalls() []struct {
	Shard TShard
} {
	var calls []struct {
		Shard TShard
	}
	mock.lockWrite.RLock()
	calls = mock.calls.Write
	mock.lockWrite.RUnlock()
	return calls
}

// WriteNotifierMock is a mock implementation of services.WriteNotifier.
//
//	func TestSomethingThatUsesWriteNotifier(t *testing.T) {
//
//		// make and configure a mocked services.WriteNotifier
//		mockedWriteNotifier := &WriteNotifierMock{
//			NotifyFunc: func()  {
//				panic("mock out the Notify method")
//			},
//		}
//
//		// use mockedWriteNotifier in code that requires services.WriteNotifier
//		// and then make assertions.
//
//	}
type WriteNotifierMock struct {
	// NotifyFunc mocks the Notify method.
	NotifyFunc func()

	// calls tracks calls to the methods.
	calls struct {
		// Notify holds details about calls to the Notify method.
		Notify []struct {
		}
	}
	lockNotify sync.RWMutex
}

// Notify calls NotifyFunc.
func (mock *WriteNotifierMock) Notify() {
	if mock.NotifyFunc == nil {
		panic("WriteNotifierMock.NotifyFunc: method is nil but WriteNotifier.Notify was just called")
	}
	callInfo := struct {
	}{}
	mock.lockNotify.Lock()
	mock.calls.Notify = append(mock.calls.Notify, callInfo)
	mock.lockNotify.Unlock()
	mock.NotifyFunc()
}

// NotifyCalls gets all the calls that were made to Notify.
// Check the length with:
//
//	len(mockedWriteNotifier.NotifyCalls())
func (mock *WriteNotifierMock) NotifyCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockNotify.RLock()
	calls = mock.calls.Notify
	mock.lockNotify.RUnlock()
	return calls
}
