// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"sync"
)

// RemovedHeadNotifierMock is a mock implementation of RemovedHeadNotifier.
//
//	func TestSomethingThatUsesRemovedHeadNotifier(t *testing.T) {
//
//		// make and configure a mocked RemovedHeadNotifier
//		mockedRemovedHeadNotifier := &RemovedHeadNotifierMock{
//			NotifyFunc: func()  {
//				panic("mock out the Notify method")
//			},
//		}
//
//		// use mockedRemovedHeadNotifier in code that requires RemovedHeadNotifier
//		// and then make assertions.
//
//	}
type RemovedHeadNotifierMock struct {
	// NotifyFunc mocks the Notify method.
	NotifyFunc func()

	// calls tracks calls to the methods.
	calls struct {
		// Notify holds details about calls to the Notify method.
		Notify []struct {
		}
	}
	lockNotify sync.RWMutex
}

// Notify calls NotifyFunc.
func (mock *RemovedHeadNotifierMock) Notify() {
	if mock.NotifyFunc == nil {
		panic("RemovedHeadNotifierMock.NotifyFunc: method is nil but RemovedHeadNotifier.Notify was just called")
	}
	callInfo := struct {
	}{}
	mock.lockNotify.Lock()
	mock.calls.Notify = append(mock.calls.Notify, callInfo)
	mock.lockNotify.Unlock()
	mock.NotifyFunc()
}

// NotifyCalls gets all the calls that were made to Notify.
// Check the length with:
//
//	len(mockedRemovedHeadNotifier.NotifyCalls())
func (mock *RemovedHeadNotifierMock) NotifyCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockNotify.RLock()
	calls = mock.calls.Notify
	mock.lockNotify.RUnlock()
	return calls
}
