// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"sync"
)

// RotatorConfigMock is a mock implementation of services.RotatorConfig.
//
//	func TestSomethingThatUsesRotatorConfig(t *testing.T) {
//
//		// make and configure a mocked services.RotatorConfig
//		mockedRotatorConfig := &RotatorConfigMock{
//			NumberOfShardsFunc: func() uint16 {
//				panic("mock out the NumberOfShards method")
//			},
//		}
//
//		// use mockedRotatorConfig in code that requires services.RotatorConfig
//		// and then make assertions.
//
//	}
type RotatorConfigMock struct {
	// NumberOfShardsFunc mocks the NumberOfShards method.
	NumberOfShardsFunc func() uint16

	// calls tracks calls to the methods.
	calls struct {
		// NumberOfShards holds details about calls to the NumberOfShards method.
		NumberOfShards []struct {
		}
	}
	lockNumberOfShards sync.RWMutex
}

// NumberOfShards calls NumberOfShardsFunc.
func (mock *RotatorConfigMock) NumberOfShards() uint16 {
	if mock.NumberOfShardsFunc == nil {
		panic("RotatorConfigMock.NumberOfShardsFunc: method is nil but RotatorConfig.NumberOfShards was just called")
	}
	callInfo := struct {
	}{}
	mock.lockNumberOfShards.Lock()
	mock.calls.NumberOfShards = append(mock.calls.NumberOfShards, callInfo)
	mock.lockNumberOfShards.Unlock()
	return mock.NumberOfShardsFunc()
}

// NumberOfShardsCalls gets all the calls that were made to NumberOfShards.
// Check the length with:
//
//	len(mockedRotatorConfig.NumberOfShardsCalls())
func (mock *RotatorConfigMock) NumberOfShardsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockNumberOfShards.RLock()
	calls = mock.calls.NumberOfShards
	mock.lockNumberOfShards.RUnlock()
	return calls
}
