// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"github.com/prometheus/prometheus/pp/go/cppbridge"
	"sync"
)

// SegmentWriterMock is a mock implementation of SegmentWriter.
//
//	func TestSomethingThatUsesSegmentWriter(t *testing.T) {
//
//		// make and configure a mocked SegmentWriter
//		mockedSegmentWriter := &SegmentWriterMock{
//			CloseFunc: func() error {
//				panic("mock out the Close method")
//			},
//			CurrentSizeFunc: func() int64 {
//				panic("mock out the CurrentSize method")
//			},
//			FlushFunc: func() error {
//				panic("mock out the Flush method")
//			},
//			SyncFunc: func() error {
//				panic("mock out the Sync method")
//			},
//			WriteFunc: func(segment *cppbridge.HeadEncodedSegment) error {
//				panic("mock out the Write method")
//			},
//		}
//
//		// use mockedSegmentWriter in code that requires SegmentWriter
//		// and then make assertions.
//
//	}
type SegmentWriterMock struct {
	// CloseFunc mocks the Close method.
	CloseFunc func() error

	// CurrentSizeFunc mocks the CurrentSize method.
	CurrentSizeFunc func() int64

	// FlushFunc mocks the Flush method.
	FlushFunc func() error

	// SyncFunc mocks the Sync method.
	SyncFunc func() error

	// WriteFunc mocks the Write method.
	WriteFunc func(segment *cppbridge.HeadEncodedSegment) error

	// calls tracks calls to the methods.
	calls struct {
		// Close holds details about calls to the Close method.
		Close []struct {
		}
		// CurrentSize holds details about calls to the CurrentSize method.
		CurrentSize []struct {
		}
		// Flush holds details about calls to the Flush method.
		Flush []struct {
		}
		// Sync holds details about calls to the Sync method.
		Sync []struct {
		}
		// Write holds details about calls to the Write method.
		Write []struct {
			// Segment is the segment argument value.
			Segment *cppbridge.HeadEncodedSegment
		}
	}
	lockClose       sync.RWMutex
	lockCurrentSize sync.RWMutex
	lockFlush       sync.RWMutex
	lockSync        sync.RWMutex
	lockWrite       sync.RWMutex
}

// Close calls CloseFunc.
func (mock *SegmentWriterMock) Close() error {
	if mock.CloseFunc == nil {
		panic("SegmentWriterMock.CloseFunc: method is nil but SegmentWriter.Close was just called")
	}
	callInfo := struct {
	}{}
	mock.lockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	mock.lockClose.Unlock()
	return mock.CloseFunc()
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//
//	len(mockedSegmentWriter.CloseCalls())
func (mock *SegmentWriterMock) CloseCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockClose.RLock()
	calls = mock.calls.Close
	mock.lockClose.RUnlock()
	return calls
}

// CurrentSize calls CurrentSizeFunc.
func (mock *SegmentWriterMock) CurrentSize() int64 {
	if mock.CurrentSizeFunc == nil {
		panic("SegmentWriterMock.CurrentSizeFunc: method is nil but SegmentWriter.CurrentSize was just called")
	}
	callInfo := struct {
	}{}
	mock.lockCurrentSize.Lock()
	mock.calls.CurrentSize = append(mock.calls.CurrentSize, callInfo)
	mock.lockCurrentSize.Unlock()
	return mock.CurrentSizeFunc()
}

// CurrentSizeCalls gets all the calls that were made to CurrentSize.
// Check the length with:
//
//	len(mockedSegmentWriter.CurrentSizeCalls())
func (mock *SegmentWriterMock) CurrentSizeCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockCurrentSize.RLock()
	calls = mock.calls.CurrentSize
	mock.lockCurrentSize.RUnlock()
	return calls
}

// Flush calls FlushFunc.
func (mock *SegmentWriterMock) Flush() error {
	if mock.FlushFunc == nil {
		panic("SegmentWriterMock.FlushFunc: method is nil but SegmentWriter.Flush was just called")
	}
	callInfo := struct {
	}{}
	mock.lockFlush.Lock()
	mock.calls.Flush = append(mock.calls.Flush, callInfo)
	mock.lockFlush.Unlock()
	return mock.FlushFunc()
}

// FlushCalls gets all the calls that were made to Flush.
// Check the length with:
//
//	len(mockedSegmentWriter.FlushCalls())
func (mock *SegmentWriterMock) FlushCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockFlush.RLock()
	calls = mock.calls.Flush
	mock.lockFlush.RUnlock()
	return calls
}

// Sync calls SyncFunc.
func (mock *SegmentWriterMock) Sync() error {
	if mock.SyncFunc == nil {
		panic("SegmentWriterMock.SyncFunc: method is nil but SegmentWriter.Sync was just called")
	}
	callInfo := struct {
	}{}
	mock.lockSync.Lock()
	mock.calls.Sync = append(mock.calls.Sync, callInfo)
	mock.lockSync.Unlock()
	return mock.SyncFunc()
}

// SyncCalls gets all the calls that were made to Sync.
// Check the length with:
//
//	len(mockedSegmentWriter.SyncCalls())
func (mock *SegmentWriterMock) SyncCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockSync.RLock()
	calls = mock.calls.Sync
	mock.lockSync.RUnlock()
	return calls
}

// Write calls WriteFunc.
func (mock *SegmentWriterMock) Write(segment *cppbridge.HeadEncodedSegment) error {
	if mock.WriteFunc == nil {
		panic("SegmentWriterMock.WriteFunc: method is nil but SegmentWriter.Write was just called")
	}
	callInfo := struct {
		Segment *cppbridge.HeadEncodedSegment
	}{
		Segment: segment,
	}
	mock.lockWrite.Lock()
	mock.calls.Write = append(mock.calls.Write, callInfo)
	mock.lockWrite.Unlock()
	return mock.WriteFunc(segment)
}

// WriteCalls gets all the calls that were made to Write.
// Check the length with:
//
//	len(mockedSegmentWriter.WriteCalls())
func (mock *SegmentWriterMock) WriteCalls() []struct {
	Segment *cppbridge.HeadEncodedSegment
} {
	var calls []struct {
		Segment *cppbridge.HeadEncodedSegment
	}
	mock.lockWrite.RLock()
	calls = mock.calls.Write
	mock.lockWrite.RUnlock()
	return calls
}
