// Code generated by goyacc -l -o promql/parser/generated_parser.y.go promql/parser/generated_parser.y. DO NOT EDIT.
package parser

import __yyfmt__ "fmt"

import (
	"math"
	"strconv"
	"time"

	"github.com/prometheus/prometheus/model/histogram"
	"github.com/prometheus/prometheus/model/labels"
	"github.com/prometheus/prometheus/model/value"
	"github.com/prometheus/prometheus/promql/parser/posrange"

	"github.com/prometheus/common/model"
)

type yySymType struct {
	yys         int
	node        Node
	item        Item
	matchers    []*labels.Matcher
	matcher     *labels.Matcher
	label       labels.Label
	labels      labels.Labels
	lblList     []labels.Label
	strings     []string
	series      []SequenceValue
	histogram   *histogram.FloatHistogram
	descriptors map[string]interface{}
	bucket_set  []float64
	int         int64
	uint        uint64
	float       float64
}

const EQL = 57346
const BLANK = 57347
const COLON = 57348
const COMMA = 57349
const COMMENT = 57350
const DURATION = 57351
const EOF = 57352
const ERROR = 57353
const IDENTIFIER = 57354
const LEFT_BRACE = 57355
const LEFT_BRACKET = 57356
const LEFT_PAREN = 57357
const OPEN_HIST = 57358
const CLOSE_HIST = 57359
const METRIC_IDENTIFIER = 57360
const NUMBER = 57361
const RIGHT_BRACE = 57362
const RIGHT_BRACKET = 57363
const RIGHT_PAREN = 57364
const SEMICOLON = 57365
const SPACE = 57366
const STRING = 57367
const TIMES = 57368
const histogramDescStart = 57369
const SUM_DESC = 57370
const COUNT_DESC = 57371
const SCHEMA_DESC = 57372
const OFFSET_DESC = 57373
const NEGATIVE_OFFSET_DESC = 57374
const BUCKETS_DESC = 57375
const NEGATIVE_BUCKETS_DESC = 57376
const ZERO_BUCKET_DESC = 57377
const ZERO_BUCKET_WIDTH_DESC = 57378
const CUSTOM_VALUES_DESC = 57379
const COUNTER_RESET_HINT_DESC = 57380
const histogramDescEnd = 57381
const operatorsStart = 57382
const ADD = 57383
const DIV = 57384
const EQLC = 57385
const EQL_REGEX = 57386
const GTE = 57387
const GTR = 57388
const LAND = 57389
const LOR = 57390
const LSS = 57391
const LTE = 57392
const LUNLESS = 57393
const MOD = 57394
const MUL = 57395
const NEQ = 57396
const NEQ_REGEX = 57397
const POW = 57398
const SUB = 57399
const AT = 57400
const ATAN2 = 57401
const operatorsEnd = 57402
const aggregatorsStart = 57403
const AVG = 57404
const BOTTOMK = 57405
const COUNT = 57406
const COUNT_VALUES = 57407
const GROUP = 57408
const MAX = 57409
const MIN = 57410
const QUANTILE = 57411
const STDDEV = 57412
const STDVAR = 57413
const SUM = 57414
const TOPK = 57415
const OP_TOP = 57416
const LIMITK = 57417
const LIMIT_RATIO = 57418
const aggregatorsEnd = 57419
const keywordsStart = 57420
const BOOL = 57421
const BY = 57422
const GROUP_LEFT = 57423
const GROUP_RIGHT = 57424
const IGNORING = 57425
const OFFSET = 57426
const ON = 57427
const WITHOUT = 57428
const keywordsEnd = 57429
const preprocessorStart = 57430
const START = 57431
const END = 57432
const preprocessorEnd = 57433
const counterResetHintsStart = 57434
const UNKNOWN_COUNTER_RESET = 57435
const COUNTER_RESET = 57436
const NOT_COUNTER_RESET = 57437
const GAUGE_TYPE = 57438
const counterResetHintsEnd = 57439
const startSymbolsStart = 57440
const START_METRIC = 57441
const START_SERIES_DESCRIPTION = 57442
const START_EXPRESSION = 57443
const START_METRIC_SELECTOR = 57444
const startSymbolsEnd = 57445

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"EQL",
	"BLANK",
	"COLON",
	"COMMA",
	"COMMENT",
	"DURATION",
	"EOF",
	"ERROR",
	"IDENTIFIER",
	"LEFT_BRACE",
	"LEFT_BRACKET",
	"LEFT_PAREN",
	"OPEN_HIST",
	"CLOSE_HIST",
	"METRIC_IDENTIFIER",
	"NUMBER",
	"RIGHT_BRACE",
	"RIGHT_BRACKET",
	"RIGHT_PAREN",
	"SEMICOLON",
	"SPACE",
	"STRING",
	"TIMES",
	"histogramDescStart",
	"SUM_DESC",
	"COUNT_DESC",
	"SCHEMA_DESC",
	"OFFSET_DESC",
	"NEGATIVE_OFFSET_DESC",
	"BUCKETS_DESC",
	"NEGATIVE_BUCKETS_DESC",
	"ZERO_BUCKET_DESC",
	"ZERO_BUCKET_WIDTH_DESC",
	"CUSTOM_VALUES_DESC",
	"COUNTER_RESET_HINT_DESC",
	"histogramDescEnd",
	"operatorsStart",
	"ADD",
	"DIV",
	"EQLC",
	"EQL_REGEX",
	"GTE",
	"GTR",
	"LAND",
	"LOR",
	"LSS",
	"LTE",
	"LUNLESS",
	"MOD",
	"MUL",
	"NEQ",
	"NEQ_REGEX",
	"POW",
	"SUB",
	"AT",
	"ATAN2",
	"operatorsEnd",
	"aggregatorsStart",
	"AVG",
	"BOTTOMK",
	"COUNT",
	"COUNT_VALUES",
	"GROUP",
	"MAX",
	"MIN",
	"QUANTILE",
	"STDDEV",
	"STDVAR",
	"SUM",
	"TOPK",
	"OP_TOP",
	"LIMITK",
	"LIMIT_RATIO",
	"aggregatorsEnd",
	"keywordsStart",
	"BOOL",
	"BY",
	"GROUP_LEFT",
	"GROUP_RIGHT",
	"IGNORING",
	"OFFSET",
	"ON",
	"WITHOUT",
	"keywordsEnd",
	"preprocessorStart",
	"START",
	"END",
	"preprocessorEnd",
	"counterResetHintsStart",
	"UNKNOWN_COUNTER_RESET",
	"COUNTER_RESET",
	"NOT_COUNTER_RESET",
	"GAUGE_TYPE",
	"counterResetHintsEnd",
	"startSymbolsStart",
	"START_METRIC",
	"START_SERIES_DESCRIPTION",
	"START_EXPRESSION",
	"START_METRIC_SELECTOR",
	"startSymbolsEnd",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

var yyExca = [...]int16{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 38,
	1, 139,
	10, 139,
	24, 139,
	-2, 0,
	-1, 62,
	2, 182,
	15, 182,
	80, 182,
	86, 182,
	-2, 102,
	-1, 63,
	2, 183,
	15, 183,
	80, 183,
	86, 183,
	-2, 103,
	-1, 64,
	2, 184,
	15, 184,
	80, 184,
	86, 184,
	-2, 105,
	-1, 65,
	2, 185,
	15, 185,
	80, 185,
	86, 185,
	-2, 106,
	-1, 66,
	2, 186,
	15, 186,
	80, 186,
	86, 186,
	-2, 107,
	-1, 67,
	2, 187,
	15, 187,
	80, 187,
	86, 187,
	-2, 112,
	-1, 68,
	2, 188,
	15, 188,
	80, 188,
	86, 188,
	-2, 114,
	-1, 69,
	2, 189,
	15, 189,
	80, 189,
	86, 189,
	-2, 116,
	-1, 70,
	2, 190,
	15, 190,
	80, 190,
	86, 190,
	-2, 117,
	-1, 71,
	2, 191,
	15, 191,
	80, 191,
	86, 191,
	-2, 118,
	-1, 72,
	2, 192,
	15, 192,
	80, 192,
	86, 192,
	-2, 119,
	-1, 73,
	2, 193,
	15, 193,
	80, 193,
	86, 193,
	-2, 120,
	-1, 74,
	2, 194,
	15, 194,
	80, 194,
	86, 194,
	-2, 121,
	-1, 75,
	2, 195,
	15, 195,
	80, 195,
	86, 195,
	-2, 125,
	-1, 76,
	2, 196,
	15, 196,
	80, 196,
	86, 196,
	-2, 126,
	-1, 202,
	9, 246,
	12, 246,
	13, 246,
	18, 246,
	19, 246,
	25, 246,
	41, 246,
	47, 246,
	48, 246,
	51, 246,
	57, 246,
	62, 246,
	63, 246,
	64, 246,
	65, 246,
	66, 246,
	67, 246,
	68, 246,
	69, 246,
	70, 246,
	71, 246,
	72, 246,
	73, 246,
	74, 246,
	75, 246,
	76, 246,
	80, 246,
	84, 246,
	86, 246,
	89, 246,
	90, 246,
	-2, 0,
	-1, 203,
	9, 246,
	12, 246,
	13, 246,
	18, 246,
	19, 246,
	25, 246,
	41, 246,
	47, 246,
	48, 246,
	51, 246,
	57, 246,
	62, 246,
	63, 246,
	64, 246,
	65, 246,
	66, 246,
	67, 246,
	68, 246,
	69, 246,
	70, 246,
	71, 246,
	72, 246,
	73, 246,
	74, 246,
	75, 246,
	76, 246,
	80, 246,
	84, 246,
	86, 246,
	89, 246,
	90, 246,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 816

var yyAct = [...]int16{
	154, 337, 335, 157, 342, 228, 40, 194, 279, 45,
	294, 293, 120, 84, 180, 109, 231, 108, 349, 350,
	351, 352, 111, 200, 110, 201, 241, 158, 112, 135,
	107, 6, 247, 202, 203, 360, 328, 113, 332, 230,
	61, 331, 296, 307, 270, 313, 162, 130, 269, 56,
	305, 220, 314, 305, 359, 198, 161, 358, 91, 55,
	312, 243, 244, 107, 115, 245, 116, 311, 100, 101,
	114, 268, 103, 259, 106, 90, 232, 234, 236, 237,
	238, 246, 248, 251, 252, 253, 254, 255, 256, 260,
	261, 336, 327, 233, 235, 239, 240, 242, 249, 250,
	105, 117, 111, 257, 258, 103, 263, 106, 112, 153,
	273, 326, 267, 113, 343, 151, 56, 165, 79, 190,
	175, 262, 169, 172, 167, 274, 55, 168, 2, 3,
	4, 5, 36, 105, 196, 266, 182, 186, 199, 7,
	188, 275, 189, 204, 205, 206, 207, 208, 209, 210,
	211, 212, 213, 214, 215, 216, 217, 218, 197, 171,
	325, 324, 219, 37, 152, 1, 192, 221, 222, 323,
	162, 162, 170, 195, 162, 156, 184, 198, 231, 86,
	161, 161, 162, 361, 161, 271, 183, 185, 241, 85,
	302, 265, 161, 131, 247, 301, 322, 187, 227, 10,
	163, 230, 163, 163, 321, 320, 163, 319, 318, 81,
	300, 291, 292, 225, 163, 295, 164, 224, 164, 164,
	317, 272, 164, 243, 244, 316, 181, 245, 182, 315,
	164, 51, 223, 88, 297, 259, 50, 80, 232, 234,
	236, 237, 238, 246, 248, 251, 252, 253, 254, 255,
	256, 260, 261, 49, 48, 233, 235, 239, 240, 242,
	249, 250, 159, 160, 166, 257, 258, 129, 184, 128,
	303, 56, 304, 306, 47, 308, 8, 134, 183, 185,
	38, 55, 309, 310, 136, 137, 138, 139, 140, 141,
	142, 143, 144, 145, 146, 147, 148, 149, 150, 46,
	44, 60, 132, 179, 9, 9, 123, 329, 178, 330,
	173, 43, 123, 133, 42, 41, 121, 338, 339, 340,
	334, 177, 121, 341, 264, 345, 344, 347, 346, 124,
	119, 52, 127, 353, 354, 124, 56, 126, 355, 54,
	79, 299, 57, 86, 357, 22, 55, 193, 56, 174,
	125, 356, 58, 85, 276, 87, 191, 226, 55, 362,
	298, 83, 82, 348, 122, 155, 59, 229, 77, 53,
	118, 0, 0, 0, 18, 19, 0, 0, 20, 0,
	0, 0, 0, 0, 78, 0, 0, 0, 0, 62,
	63, 64, 65, 66, 67, 68, 69, 70, 71, 72,
	73, 74, 75, 76, 0, 0, 0, 13, 0, 0,
	0, 24, 0, 31, 0, 0, 32, 33, 56, 39,
	107, 54, 79, 0, 57, 278, 0, 22, 55, 0,
	0, 0, 277, 0, 58, 0, 281, 282, 280, 287,
	289, 286, 288, 283, 284, 285, 290, 89, 91, 0,
	77, 0, 0, 0, 0, 0, 18, 19, 100, 101,
	20, 0, 103, 104, 106, 90, 78, 0, 0, 0,
	0, 62, 63, 64, 65, 66, 67, 68, 69, 70,
	71, 72, 73, 74, 75, 76, 0, 0, 0, 13,
	105, 0, 0, 24, 0, 31, 0, 56, 32, 33,
	54, 79, 0, 57, 333, 0, 22, 55, 0, 0,
	0, 0, 0, 58, 0, 281, 282, 280, 287, 289,
	286, 288, 283, 284, 285, 290, 0, 0, 0, 77,
	0, 17, 79, 0, 0, 18, 19, 22, 0, 20,
	0, 0, 0, 0, 0, 78, 0, 0, 0, 0,
	62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
	72, 73, 74, 75, 76, 0, 18, 19, 13, 0,
	20, 0, 24, 0, 31, 0, 0, 32, 33, 0,
	0, 11, 12, 14, 15, 16, 21, 23, 25, 26,
	27, 28, 29, 30, 34, 35, 17, 36, 0, 13,
	0, 0, 22, 24, 0, 31, 0, 0, 32, 33,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 18, 19, 0, 0, 20, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 11, 12, 14, 15,
	16, 21, 23, 25, 26, 27, 28, 29, 30, 34,
	35, 107, 0, 0, 13, 0, 0, 0, 24, 176,
	31, 0, 0, 32, 33, 0, 0, 0, 0, 0,
	107, 0, 0, 0, 0, 0, 0, 0, 89, 91,
	92, 0, 93, 94, 95, 96, 97, 98, 99, 100,
	101, 102, 0, 103, 104, 106, 90, 89, 91, 92,
	0, 93, 94, 95, 96, 97, 98, 99, 100, 101,
	102, 0, 103, 104, 106, 90, 107, 0, 0, 0,
	0, 105, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 107, 0, 0, 0, 0,
	105, 0, 0, 89, 91, 92, 0, 93, 94, 95,
	0, 97, 98, 99, 100, 101, 102, 0, 103, 104,
	106, 90, 89, 91, 92, 0, 93, 94, 0, 0,
	97, 98, 0, 100, 101, 102, 0, 103, 104, 106,
	90, 0, 0, 0, 0, 0, 105, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 105,
}

var yyPact = [...]int16{
	29, 129, 584, 584, 409, 519, -1000, -1000, -1000, 119,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, 341, -1000, 231, -1000,
	666, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, 22, 98, -1000, -1000, 488, -1000, 488,
	105, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, 310,
	-1000, -1000, 330, -1000, -1000, 265, -1000, 23, -1000, -50,
	-50, -50, -50, -50, -50, -50, -50, -50, -50, -50,
	-50, -50, -50, -50, -50, 107, 173, 262, 98, -58,
	-1000, 157, 157, 327, -1000, 647, 49, -1000, 301, -1000,
	-1000, 224, 132, -1000, -1000, -1000, 177, -1000, 117, -1000,
	161, 488, -1000, -60, -48, -1000, 488, 488, 488, 488,
	488, 488, 488, 488, 488, 488, 488, 488, 488, 488,
	488, -1000, 40, -1000, -1000, 36, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, 37, 37, 211, -1000, -1000, -1000, -1000,
	176, -1000, -1000, 99, -1000, 666, -1000, -1000, 304, -1000,
	110, -1000, -1000, -1000, -1000, -1000, 46, -1000, -1000, -1000,
	-1000, -1000, 18, 159, 84, -1000, -1000, -1000, 408, 16,
	157, 157, 157, 157, 49, 49, 406, 406, 406, 731,
	712, 406, 406, 731, 49, 49, 406, 49, 16, -1000,
	20, -1000, -1000, -1000, 339, -1000, 188, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, 488, -1000, -1000, -1000, -1000, -1000, -1000,
	31, 31, 17, 31, 39, 39, 43, 35, -1000, -1000,
	223, 219, 214, 202, 201, 199, 198, 190, 163, 155,
	154, -1000, -1000, -1000, -1000, -1000, -1000, 90, -1000, -1000,
	-1000, 14, -1000, 666, -1000, -1000, -1000, 31, -1000, 15,
	12, 487, -1000, -1000, -1000, 34, 165, 165, 165, 37,
	100, 100, 34, 100, 34, -75, -1000, -1000, -1000, -1000,
	-1000, 31, 31, -1000, -1000, -1000, 31, -1000, -1000, -1000,
	-1000, -1000, -1000, 165, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, 33, -1000, 162, -1000,
	-1000, -1000, -1000,
}

var yyPgo = [...]int16{
	0, 370, 12, 369, 5, 14, 367, 301, 366, 365,
	364, 363, 199, 276, 362, 13, 357, 10, 11, 356,
	355, 7, 354, 8, 4, 351, 2, 1, 3, 347,
	27, 0, 331, 315, 17, 193, 314, 313, 6, 311,
	310, 15, 302, 40, 300, 9, 299, 277, 274, 254,
	253, 236, 231, 165, 163,
}

var yyR1 = [...]int8{
	0, 53, 53, 53, 53, 53, 53, 53, 38, 38,
	38, 38, 38, 38, 38, 38, 38, 38, 38, 38,
	33, 33, 33, 33, 34, 34, 36, 36, 36, 36,
	36, 36, 36, 36, 36, 36, 36, 36, 36, 36,
	36, 36, 35, 37, 37, 47, 47, 42, 42, 42,
	42, 17, 17, 17, 17, 16, 16, 16, 4, 4,
	4, 39, 41, 41, 40, 40, 40, 48, 46, 46,
	46, 32, 32, 32, 9, 9, 44, 50, 50, 50,
	50, 50, 50, 51, 52, 52, 52, 43, 43, 43,
	1, 1, 1, 2, 2, 2, 2, 2, 2, 2,
	13, 13, 7, 7, 7, 7, 7, 7, 7, 7,
	7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
	7, 7, 7, 7, 7, 7, 7, 12, 12, 12,
	12, 14, 14, 14, 15, 15, 15, 15, 54, 20,
	20, 20, 20, 19, 19, 19, 19, 19, 19, 19,
	19, 19, 29, 29, 29, 21, 21, 21, 21, 22,
	22, 22, 23, 23, 23, 23, 23, 23, 23, 23,
	23, 23, 23, 24, 24, 25, 25, 25, 11, 11,
	11, 11, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 6, 6, 6,
	6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
	6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
	6, 6, 6, 6, 6, 6, 6, 8, 8, 5,
	5, 5, 5, 45, 45, 28, 28, 30, 30, 31,
	31, 27, 26, 26, 49, 10, 18, 18,
}

var yyR2 = [...]int8{
	0, 2, 2, 2, 2, 2, 2, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	3, 3, 2, 2, 2, 2, 4, 4, 4, 4,
	4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
	4, 4, 1, 0, 1, 3, 3, 1, 1, 3,
	3, 3, 4, 2, 1, 3, 1, 2, 1, 1,
	1, 2, 3, 2, 3, 1, 2, 3, 3, 4,
	3, 3, 5, 3, 1, 1, 4, 6, 5, 6,
	5, 4, 3, 2, 2, 1, 1, 3, 4, 2,
	3, 1, 2, 3, 3, 1, 3, 3, 2, 1,
	2, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 3, 4, 2,
	0, 3, 1, 2, 3, 3, 2, 1, 2, 0,
	3, 2, 1, 1, 3, 1, 3, 4, 1, 3,
	5, 5, 1, 1, 1, 4, 3, 3, 2, 3,
	1, 2, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 4, 3, 3, 1, 2, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 2, 2, 1,
	1, 1, 2, 1, 1, 1, 0, 1,
}

var yyChk = [...]int16{
	-1000, -53, 99, 100, 101, 102, 2, 10, -13, -7,
	-12, 62, 63, 80, 64, 65, 66, 12, 47, 48,
	51, 67, 18, 68, 84, 69, 70, 71, 72, 73,
	74, 86, 89, 90, 75, 76, 13, -54, -13, 10,
	-38, -33, -36, -39, -44, -45, -46, -48, -49, -50,
	-51, -52, -32, -3, 12, 19, 9, 15, 25, -8,
	-7, -43, 62, 63, 64, 65, 66, 67, 68, 69,
	70, 71, 72, 73, 74, 75, 76, 41, 57, 13,
	-52, -12, -14, 20, -15, 12, 2, -20, 2, 41,
	59, 42, 43, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 56, 57, 84, 58, 14, -34, -41,
	2, 80, 86, 15, -41, -38, -38, -43, -1, 20,
	-2, 12, -10, 2, 25, 20, 7, 2, 4, 2,
	24, -35, -42, -37, -47, 79, -35, -35, -35, -35,
	-35, -35, -35, -35, -35, -35, -35, -35, -35, -35,
	-35, -45, 57, 2, -31, -9, 2, -28, -30, 89,
	90, 19, 9, 41, 57, -45, 2, -41, -34, -17,
	15, 2, -17, -40, 22, -38, 22, 20, 7, 2,
	-5, 2, 4, 54, 44, 55, -5, 20, -15, 25,
	2, -19, 5, -29, -21, 12, -28, -30, 16, -38,
	83, 85, 81, 82, -38, -38, -38, -38, -38, -38,
	-38, -38, -38, -38, -38, -38, -38, -38, -38, -45,
	15, -28, -28, 21, 6, 2, -16, 22, -4, -6,
	25, 2, 62, 79, 63, 80, 64, 65, 66, 81,
	82, 12, 83, 47, 48, 51, 67, 18, 68, 84,
	85, 69, 70, 71, 72, 73, 74, 89, 90, 59,
	75, 76, 22, 7, 20, -2, 25, 2, 25, 2,
	26, 26, -30, 26, 41, 57, -22, 24, 17, -23,
	30, 28, 29, 35, 36, 37, 33, 31, 34, 32,
	38, -17, -17, -18, -17, -18, 22, -45, 21, 2,
	22, 7, 2, -38, -27, 19, -27, 26, -27, -21,
	-21, 24, 17, 2, 17, 6, 6, 6, 6, 6,
	6, 6, 6, 6, 6, 6, 21, 2, 22, -4,
	-27, 26, 26, 17, -23, -26, 57, -27, -31, -31,
	-31, -28, -24, 14, -24, -26, -24, -26, -11, 93,
	94, 95, 96, -27, -27, -27, -25, -31, 24, 21,
	2, 21, -31,
}

var yyDef = [...]int16{
	0, -2, 130, 130, 0, 0, 7, 6, 1, 130,
	101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
	111, 112, 113, 114, 115, 116, 117, 118, 119, 120,
	121, 122, 123, 124, 125, 126, 0, 2, -2, 3,
	4, 8, 9, 10, 11, 12, 13, 14, 15, 16,
	17, 18, 19, 0, 108, 233, 234, 0, 244, 0,
	85, 86, -2, -2, -2, -2, -2, -2, -2, -2,
	-2, -2, -2, -2, -2, -2, -2, 227, 228, 0,
	5, 100, 0, 129, 132, 0, 137, 138, 142, 43,
	43, 43, 43, 43, 43, 43, 43, 43, 43, 43,
	43, 43, 43, 43, 43, 0, 0, 0, 0, 22,
	23, 0, 0, 0, 61, 0, 83, 84, 0, 89,
	91, 0, 95, 99, 245, 127, 0, 133, 0, 136,
	141, 0, 42, 47, 48, 44, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 68, 0, 70, 71, 0, 73, 239, 240, 74,
	75, 235, 236, 0, 0, 0, 82, 20, 21, 24,
	0, 54, 25, 0, 63, 65, 67, 87, 0, 92,
	0, 98, 229, 230, 231, 232, 0, 128, 131, 134,
	135, 140, 143, 145, 148, 152, 153, 154, 0, 26,
	0, 0, -2, -2, 27, 28, 29, 30, 31, 32,
	33, 34, 35, 36, 37, 38, 39, 40, 41, 69,
	0, 237, 238, 76, 0, 81, 0, 53, 56, 58,
	59, 60, 197, 198, 199, 200, 201, 202, 203, 204,
	205, 206, 207, 208, 209, 210, 211, 212, 213, 214,
	215, 216, 217, 218, 219, 220, 221, 222, 223, 224,
	225, 226, 62, 66, 88, 90, 93, 97, 94, 96,
	0, 0, 0, 0, 0, 0, 0, 0, 158, 160,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 45, 46, 49, 247, 50, 72, 0, 78, 80,
	51, 0, 57, 64, 144, 241, 146, 0, 149, 0,
	0, 0, 156, 161, 157, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 77, 79, 52, 55,
	147, 0, 0, 155, 159, 162, 0, 243, 163, 164,
	165, 166, 167, 0, 168, 169, 170, 171, 172, 178,
	179, 180, 181, 150, 151, 242, 0, 176, 0, 174,
	177, 173, 175,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
	62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
	72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
	82, 83, 84, 85, 86, 87, 88, 89, 90, 91,
	92, 93, 94, 95, 96, 97, 98, 99, 100, 101,
	102, 103,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yylex.(*parser).generatedParserResult = yyDollar[2].labels
		}
	case 3:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yylex.(*parser).addParseErrf(posrange.PositionRange{}, "no expression found in input")
		}
	case 4:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yylex.(*parser).generatedParserResult = yyDollar[2].node
		}
	case 5:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yylex.(*parser).generatedParserResult = yyDollar[2].node
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yylex.(*parser).unexpected("", "")
		}
	case 20:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = yylex.(*parser).newAggregateExpr(yyDollar[1].item, yyDollar[2].node, yyDollar[3].node)
		}
	case 21:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = yylex.(*parser).newAggregateExpr(yyDollar[1].item, yyDollar[3].node, yyDollar[2].node)
		}
	case 22:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = yylex.(*parser).newAggregateExpr(yyDollar[1].item, &AggregateExpr{}, yyDollar[2].node)
		}
	case 23:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yylex.(*parser).unexpected("aggregation", "")
			yyVAL.node = yylex.(*parser).newAggregateExpr(yyDollar[1].item, &AggregateExpr{}, Expressions{})
		}
	case 24:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = &AggregateExpr{
				Grouping: yyDollar[2].strings,
			}
		}
	case 25:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = &AggregateExpr{
				Grouping: yyDollar[2].strings,
				Without:  true,
			}
		}
	case 26:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 27:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 28:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 29:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 30:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 31:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 32:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 33:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 34:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 35:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 36:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 37:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 38:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 39:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 40:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 41:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 43:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.node = &BinaryExpr{
				VectorMatching: &VectorMatching{Card: CardOneToOne},
			}
		}
	case 44:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &BinaryExpr{
				VectorMatching: &VectorMatching{Card: CardOneToOne},
				ReturnBool:     true,
			}
		}
	case 45:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
			yyVAL.node.(*BinaryExpr).VectorMatching.MatchingLabels = yyDollar[3].strings
		}
	case 46:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
			yyVAL.node.(*BinaryExpr).VectorMatching.MatchingLabels = yyDollar[3].strings
			yyVAL.node.(*BinaryExpr).VectorMatching.On = true
		}
	case 49:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
			yyVAL.node.(*BinaryExpr).VectorMatching.Card = CardManyToOne
			yyVAL.node.(*BinaryExpr).VectorMatching.Include = yyDollar[3].strings
		}
	case 50:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
			yyVAL.node.(*BinaryExpr).VectorMatching.Card = CardOneToMany
			yyVAL.node.(*BinaryExpr).VectorMatching.Include = yyDollar[3].strings
		}
	case 51:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.strings = yyDollar[2].strings
		}
	case 52:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.strings = yyDollar[2].strings
		}
	case 53:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.strings = []string{}
		}
	case 54:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yylex.(*parser).unexpected("grouping opts", "\"(\"")
			yyVAL.strings = nil
		}
	case 55:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.strings = append(yyDollar[1].strings, yyDollar[3].item.Val)
		}
	case 56:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.strings = []string{yyDollar[1].item.Val}
		}
	case 57:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yylex.(*parser).unexpected("grouping opts", "\",\" or \")\"")
			yyVAL.strings = yyDollar[1].strings
		}
	case 58:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			if !model.LabelName(yyDollar[1].item.Val).IsValid() {
				yylex.(*parser).unexpected("grouping opts", "label")
			}
			yyVAL.item = yyDollar[1].item
		}
	case 59:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			if !model.LabelName(yylex.(*parser).unquoteString(yyDollar[1].item.Val)).IsValid() {
				yylex.(*parser).unexpected("grouping opts", "label")
			}
			yyVAL.item = yyDollar[1].item
			yyVAL.item.Pos++
			yyVAL.item.Val = yylex.(*parser).unquoteString(yyVAL.item.Val)
		}
	case 60:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yylex.(*parser).unexpected("grouping opts", "label")
			yyVAL.item = Item{}
		}
	case 61:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			fn, exist := getFunction(yyDollar[1].item.Val, yylex.(*parser).functions)
			if !exist {
				yylex.(*parser).addParseErrf(yyDollar[1].item.PositionRange(), "unknown function with name %q", yyDollar[1].item.Val)
			}
			if fn != nil && fn.Experimental && !EnableExperimentalFunctions {
				yylex.(*parser).addParseErrf(yyDollar[1].item.PositionRange(), "function %q is not enabled", yyDollar[1].item.Val)
			}
			yyVAL.node = &Call{
				Func: fn,
				Args: yyDollar[2].node.(Expressions),
				PosRange: posrange.PositionRange{
					Start: yyDollar[1].item.Pos,
					End:   yylex.(*parser).lastClosing,
				},
			}
		}
	case 62:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = yyDollar[2].node
		}
	case 63:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = Expressions{}
		}
	case 64:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = append(yyDollar[1].node.(Expressions), yyDollar[3].node.(Expr))
		}
	case 65:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = Expressions{yyDollar[1].node.(Expr)}
		}
	case 66:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yylex.(*parser).addParseErrf(yyDollar[2].item.PositionRange(), "trailing commas not allowed in function call args")
			yyVAL.node = yyDollar[1].node
		}
	case 67:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ParenExpr{Expr: yyDollar[2].node.(Expr), PosRange: mergeRanges(&yyDollar[1].item, &yyDollar[3].item)}
		}
	case 68:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			numLit, _ := yyDollar[3].node.(*NumberLiteral)
			dur := time.Duration(numLit.Val*1000) * time.Millisecond
			yylex.(*parser).addOffset(yyDollar[1].node, dur)
			yyVAL.node = yyDollar[1].node
		}
	case 69:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			numLit, _ := yyDollar[4].node.(*NumberLiteral)
			dur := time.Duration(numLit.Val*1000) * time.Millisecond
			yylex.(*parser).addOffset(yyDollar[1].node, -dur)
			yyVAL.node = yyDollar[1].node
		}
	case 70:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yylex.(*parser).unexpected("offset", "number or duration")
			yyVAL.node = yyDollar[1].node
		}
	case 71:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yylex.(*parser).setTimestamp(yyDollar[1].node, yyDollar[3].float)
			yyVAL.node = yyDollar[1].node
		}
	case 72:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yylex.(*parser).setAtModifierPreprocessor(yyDollar[1].node, yyDollar[3].item)
			yyVAL.node = yyDollar[1].node
		}
	case 73:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yylex.(*parser).unexpected("@", "timestamp")
			yyVAL.node = yyDollar[1].node
		}
	case 76:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			var errMsg string
			vs, ok := yyDollar[1].node.(*VectorSelector)
			if !ok {
				errMsg = "ranges only allowed for vector selectors"
			} else if vs.OriginalOffset != 0 {
				errMsg = "no offset modifiers allowed before range"
			} else if vs.Timestamp != nil {
				errMsg = "no @ modifiers allowed before range"
			}

			if errMsg != "" {
				errRange := mergeRanges(&yyDollar[2].item, &yyDollar[4].item)
				yylex.(*parser).addParseErrf(errRange, "%s", errMsg)
			}

			numLit, _ := yyDollar[3].node.(*NumberLiteral)
			yyVAL.node = &MatrixSelector{
				VectorSelector: yyDollar[1].node.(Expr),
				Range:          time.Duration(numLit.Val*1000) * time.Millisecond,
				EndPos:         yylex.(*parser).lastClosing,
			}
		}
	case 77:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			numLitRange, _ := yyDollar[3].node.(*NumberLiteral)
			numLitStep, _ := yyDollar[5].node.(*NumberLiteral)
			yyVAL.node = &SubqueryExpr{
				Expr:   yyDollar[1].node.(Expr),
				Range:  time.Duration(numLitRange.Val*1000) * time.Millisecond,
				Step:   time.Duration(numLitStep.Val*1000) * time.Millisecond,
				EndPos: yyDollar[6].item.Pos + 1,
			}
		}
	case 78:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			numLitRange, _ := yyDollar[3].node.(*NumberLiteral)
			yyVAL.node = &SubqueryExpr{
				Expr:   yyDollar[1].node.(Expr),
				Range:  time.Duration(numLitRange.Val*1000) * time.Millisecond,
				Step:   0,
				EndPos: yyDollar[5].item.Pos + 1,
			}
		}
	case 79:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yylex.(*parser).unexpected("subquery selector", "\"]\"")
			yyVAL.node = yyDollar[1].node
		}
	case 80:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yylex.(*parser).unexpected("subquery selector", "number or duration or \"]\"")
			yyVAL.node = yyDollar[1].node
		}
	case 81:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yylex.(*parser).unexpected("subquery or range", "\":\" or \"]\"")
			yyVAL.node = yyDollar[1].node
		}
	case 82:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yylex.(*parser).unexpected("subquery selector", "number or duration")
			yyVAL.node = yyDollar[1].node
		}
	case 83:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			if nl, ok := yyDollar[2].node.(*NumberLiteral); ok {
				if yyDollar[1].item.Typ == SUB {
					nl.Val *= -1
				}
				nl.PosRange.Start = yyDollar[1].item.Pos
				yyVAL.node = nl
			} else {
				yyVAL.node = &UnaryExpr{Op: yyDollar[1].item.Typ, Expr: yyDollar[2].node.(Expr), StartPos: yyDollar[1].item.Pos}
			}
		}
	case 84:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			vs := yyDollar[2].node.(*VectorSelector)
			vs.PosRange = mergeRanges(&yyDollar[1].item, vs)
			vs.Name = yyDollar[1].item.Val
			yylex.(*parser).assembleVectorSelector(vs)
			yyVAL.node = vs
		}
	case 85:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			vs := &VectorSelector{
				Name:          yyDollar[1].item.Val,
				LabelMatchers: []*labels.Matcher{},
				PosRange:      yyDollar[1].item.PositionRange(),
			}
			yylex.(*parser).assembleVectorSelector(vs)
			yyVAL.node = vs
		}
	case 86:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			vs := yyDollar[1].node.(*VectorSelector)
			yylex.(*parser).assembleVectorSelector(vs)
			yyVAL.node = vs
		}
	case 87:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &VectorSelector{
				LabelMatchers: yyDollar[2].matchers,
				PosRange:      mergeRanges(&yyDollar[1].item, &yyDollar[3].item),
			}
		}
	case 88:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &VectorSelector{
				LabelMatchers: yyDollar[2].matchers,
				PosRange:      mergeRanges(&yyDollar[1].item, &yyDollar[4].item),
			}
		}
	case 89:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = &VectorSelector{
				LabelMatchers: []*labels.Matcher{},
				PosRange:      mergeRanges(&yyDollar[1].item, &yyDollar[2].item),
			}
		}
	case 90:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			if yyDollar[1].matchers != nil {
				yyVAL.matchers = append(yyDollar[1].matchers, yyDollar[3].matcher)
			} else {
				yyVAL.matchers = yyDollar[1].matchers
			}
		}
	case 91:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.matchers = []*labels.Matcher{yyDollar[1].matcher}
		}
	case 92:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yylex.(*parser).unexpected("label matching", "\",\" or \"}\"")
			yyVAL.matchers = yyDollar[1].matchers
		}
	case 93:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.matcher = yylex.(*parser).newLabelMatcher(yyDollar[1].item, yyDollar[2].item, yyDollar[3].item)
		}
	case 94:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.matcher = yylex.(*parser).newLabelMatcher(yyDollar[1].item, yyDollar[2].item, yyDollar[3].item)
		}
	case 95:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.matcher = yylex.(*parser).newMetricNameMatcher(yyDollar[1].item)
		}
	case 96:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yylex.(*parser).unexpected("label matching", "string")
			yyVAL.matcher = nil
		}
	case 97:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yylex.(*parser).unexpected("label matching", "string")
			yyVAL.matcher = nil
		}
	case 98:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yylex.(*parser).unexpected("label matching", "label matching operator")
			yyVAL.matcher = nil
		}
	case 99:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yylex.(*parser).unexpected("label matching", "identifier or \"}\"")
			yyVAL.matcher = nil
		}
	case 100:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			b := labels.NewBuilder(yyDollar[2].labels)
			b.Set(labels.MetricName, yyDollar[1].item.Val)
			yyVAL.labels = b.Labels()
		}
	case 101:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.labels = yyDollar[1].labels
		}
	case 127:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.labels = labels.New(yyDollar[2].lblList...)
		}
	case 128:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.labels = labels.New(yyDollar[2].lblList...)
		}
	case 129:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.labels = labels.New()
		}
	case 130:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.labels = labels.New()
		}
	case 131:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.lblList = append(yyDollar[1].lblList, yyDollar[3].label)
		}
	case 132:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.lblList = []labels.Label{yyDollar[1].label}
		}
	case 133:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yylex.(*parser).unexpected("label set", "\",\" or \"}\"")
			yyVAL.lblList = yyDollar[1].lblList
		}
	case 134:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.label = labels.Label{Name: yyDollar[1].item.Val, Value: yylex.(*parser).unquoteString(yyDollar[3].item.Val)}
		}
	case 135:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yylex.(*parser).unexpected("label set", "string")
			yyVAL.label = labels.Label{}
		}
	case 136:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yylex.(*parser).unexpected("label set", "\"=\"")
			yyVAL.label = labels.Label{}
		}
	case 137:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yylex.(*parser).unexpected("label set", "identifier or \"}\"")
			yyVAL.label = labels.Label{}
		}
	case 138:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yylex.(*parser).generatedParserResult = &seriesDescription{
				labels: yyDollar[1].labels,
				values: yyDollar[2].series,
			}
		}
	case 139:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.series = []SequenceValue{}
		}
	case 140:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.series = append(yyDollar[1].series, yyDollar[3].series...)
		}
	case 141:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.series = yyDollar[1].series
		}
	case 142:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yylex.(*parser).unexpected("series values", "")
			yyVAL.series = nil
		}
	case 143:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.series = []SequenceValue{{Omitted: true}}
		}
	case 144:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.series = []SequenceValue{}
			for i := uint64(0); i < yyDollar[3].uint; i++ {
				yyVAL.series = append(yyVAL.series, SequenceValue{Omitted: true})
			}
		}
	case 145:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.series = []SequenceValue{{Value: yyDollar[1].float}}
		}
	case 146:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.series = []SequenceValue{}
			// Add an additional value for time 0, which we ignore in tests.
			for i := uint64(0); i <= yyDollar[3].uint; i++ {
				yyVAL.series = append(yyVAL.series, SequenceValue{Value: yyDollar[1].float})
			}
		}
	case 147:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.series = []SequenceValue{}
			// Add an additional value for time 0, which we ignore in tests.
			for i := uint64(0); i <= yyDollar[4].uint; i++ {
				yyVAL.series = append(yyVAL.series, SequenceValue{Value: yyDollar[1].float})
				yyDollar[1].float += yyDollar[2].float
			}
		}
	case 148:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.series = []SequenceValue{{Histogram: yyDollar[1].histogram}}
		}
	case 149:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.series = []SequenceValue{}
			// Add an additional value for time 0, which we ignore in tests.
			for i := uint64(0); i <= yyDollar[3].uint; i++ {
				yyVAL.series = append(yyVAL.series, SequenceValue{Histogram: yyDollar[1].histogram})
				//$1 += $2
			}
		}
	case 150:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			val, err := yylex.(*parser).histogramsIncreaseSeries(yyDollar[1].histogram, yyDollar[3].histogram, yyDollar[5].uint)
			if err != nil {
				yylex.(*parser).addSemanticError(err)
			}
			yyVAL.series = val
		}
	case 151:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			val, err := yylex.(*parser).histogramsDecreaseSeries(yyDollar[1].histogram, yyDollar[3].histogram, yyDollar[5].uint)
			if err != nil {
				yylex.(*parser).addSemanticError(err)
			}
			yyVAL.series = val
		}
	case 152:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			if yyDollar[1].item.Val != "stale" {
				yylex.(*parser).unexpected("series values", "number or \"stale\"")
			}
			yyVAL.float = math.Float64frombits(value.StaleNaN)
		}
	case 155:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.histogram = yylex.(*parser).buildHistogramFromMap(&yyDollar[2].descriptors)
		}
	case 156:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.histogram = yylex.(*parser).buildHistogramFromMap(&yyDollar[2].descriptors)
		}
	case 157:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			m := yylex.(*parser).newMap()
			yyVAL.histogram = yylex.(*parser).buildHistogramFromMap(&m)
		}
	case 158:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			m := yylex.(*parser).newMap()
			yyVAL.histogram = yylex.(*parser).buildHistogramFromMap(&m)
		}
	case 159:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.descriptors = *(yylex.(*parser).mergeMaps(&yyDollar[1].descriptors, &yyDollar[3].descriptors))
		}
	case 160:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.descriptors = yyDollar[1].descriptors
		}
	case 161:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yylex.(*parser).unexpected("histogram description", "histogram description key, e.g. buckets:[5 10 7]")
		}
	case 162:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.descriptors = yylex.(*parser).newMap()
			yyVAL.descriptors["schema"] = yyDollar[3].int
		}
	case 163:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.descriptors = yylex.(*parser).newMap()
			yyVAL.descriptors["sum"] = yyDollar[3].float
		}
	case 164:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.descriptors = yylex.(*parser).newMap()
			yyVAL.descriptors["count"] = yyDollar[3].float
		}
	case 165:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.descriptors = yylex.(*parser).newMap()
			yyVAL.descriptors["z_bucket"] = yyDollar[3].float
		}
	case 166:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.descriptors = yylex.(*parser).newMap()
			yyVAL.descriptors["z_bucket_w"] = yyDollar[3].float
		}
	case 167:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.descriptors = yylex.(*parser).newMap()
			yyVAL.descriptors["custom_values"] = yyDollar[3].bucket_set
		}
	case 168:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.descriptors = yylex.(*parser).newMap()
			yyVAL.descriptors["buckets"] = yyDollar[3].bucket_set
		}
	case 169:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.descriptors = yylex.(*parser).newMap()
			yyVAL.descriptors["offset"] = yyDollar[3].int
		}
	case 170:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.descriptors = yylex.(*parser).newMap()
			yyVAL.descriptors["n_buckets"] = yyDollar[3].bucket_set
		}
	case 171:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.descriptors = yylex.(*parser).newMap()
			yyVAL.descriptors["n_offset"] = yyDollar[3].int
		}
	case 172:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.descriptors = yylex.(*parser).newMap()
			yyVAL.descriptors["counter_reset_hint"] = yyDollar[3].item
		}
	case 173:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.bucket_set = yyDollar[2].bucket_set
		}
	case 174:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.bucket_set = yyDollar[2].bucket_set
		}
	case 175:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.bucket_set = append(yyDollar[1].bucket_set, yyDollar[3].float)
		}
	case 176:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.bucket_set = []float64{yyDollar[1].float}
		}
	case 233:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &NumberLiteral{
				Val:      yylex.(*parser).number(yyDollar[1].item.Val),
				PosRange: yyDollar[1].item.PositionRange(),
			}
		}
	case 234:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			var err error
			var dur time.Duration
			dur, err = parseDuration(yyDollar[1].item.Val)
			if err != nil {
				yylex.(*parser).addParseErr(yyDollar[1].item.PositionRange(), err)
			}
			yyVAL.node = &NumberLiteral{
				Val:      dur.Seconds(),
				PosRange: yyDollar[1].item.PositionRange(),
			}
		}
	case 235:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.float = yylex.(*parser).number(yyDollar[1].item.Val)
		}
	case 236:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			var err error
			var dur time.Duration
			dur, err = parseDuration(yyDollar[1].item.Val)
			if err != nil {
				yylex.(*parser).addParseErr(yyDollar[1].item.PositionRange(), err)
			}
			yyVAL.float = dur.Seconds()
		}
	case 237:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.float = yyDollar[2].float
		}
	case 238:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.float = -yyDollar[2].float
		}
	case 241:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			var err error
			yyVAL.uint, err = strconv.ParseUint(yyDollar[1].item.Val, 10, 64)
			if err != nil {
				yylex.(*parser).addParseErrf(yyDollar[1].item.PositionRange(), "invalid repetition in series values: %s", err)
			}
		}
	case 242:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.int = -int64(yyDollar[2].uint)
		}
	case 243:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.int = int64(yyDollar[1].uint)
		}
	case 244:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &StringLiteral{
				Val:      yylex.(*parser).unquoteString(yyDollar[1].item.Val),
				PosRange: yyDollar[1].item.PositionRange(),
			}
		}
	case 245:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.item = Item{
				Typ: METRIC_IDENTIFIER,
				Pos: yyDollar[1].item.PositionRange().Start,
				Val: yylex.(*parser).unquoteString(yyDollar[1].item.Val),
			}
		}
	case 246:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.strings = nil
		}
	}
	goto yystack /* stack new state and value */
}
