// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package writer_test

import (
	"github.com/prometheus/prometheus/pp/go/storage/head/shard/wal/writer"
	"io"
	"io/fs"
	"sync"
	"time"
)

// Ensure, that EncodedSegmentMock does implement writer.EncodedSegment.
// If this is not the case, regenerate this file with moq.
var _ writer.EncodedSegment = &EncodedSegmentMock{}

// EncodedSegmentMock is a mock implementation of writer.EncodedSegment.
//
//	func TestSomethingThatUsesEncodedSegment(t *testing.T) {
//
//		// make and configure a mocked writer.EncodedSegment
//		mockedEncodedSegment := &EncodedSegmentMock{
//			CRC32Func: func() uint32 {
//				panic("mock out the CRC32 method")
//			},
//			SamplesFunc: func() uint32 {
//				panic("mock out the Samples method")
//			},
//			SizeFunc: func() int64 {
//				panic("mock out the Size method")
//			},
//			WriteToFunc: func(w io.Writer) (int64, error) {
//				panic("mock out the WriteTo method")
//			},
//		}
//
//		// use mockedEncodedSegment in code that requires writer.EncodedSegment
//		// and then make assertions.
//
//	}
type EncodedSegmentMock struct {
	// CRC32Func mocks the CRC32 method.
	CRC32Func func() uint32

	// SamplesFunc mocks the Samples method.
	SamplesFunc func() uint32

	// SizeFunc mocks the Size method.
	SizeFunc func() int64

	// WriteToFunc mocks the WriteTo method.
	WriteToFunc func(w io.Writer) (int64, error)

	// calls tracks calls to the methods.
	calls struct {
		// CRC32 holds details about calls to the CRC32 method.
		CRC32 []struct {
		}
		// Samples holds details about calls to the Samples method.
		Samples []struct {
		}
		// Size holds details about calls to the Size method.
		Size []struct {
		}
		// WriteTo holds details about calls to the WriteTo method.
		WriteTo []struct {
			// W is the w argument value.
			W io.Writer
		}
	}
	lockCRC32   sync.RWMutex
	lockSamples sync.RWMutex
	lockSize    sync.RWMutex
	lockWriteTo sync.RWMutex
}

// CRC32 calls CRC32Func.
func (mock *EncodedSegmentMock) CRC32() uint32 {
	if mock.CRC32Func == nil {
		panic("EncodedSegmentMock.CRC32Func: method is nil but EncodedSegment.CRC32 was just called")
	}
	callInfo := struct {
	}{}
	mock.lockCRC32.Lock()
	mock.calls.CRC32 = append(mock.calls.CRC32, callInfo)
	mock.lockCRC32.Unlock()
	return mock.CRC32Func()
}

// CRC32Calls gets all the calls that were made to CRC32.
// Check the length with:
//
//	len(mockedEncodedSegment.CRC32Calls())
func (mock *EncodedSegmentMock) CRC32Calls() []struct {
} {
	var calls []struct {
	}
	mock.lockCRC32.RLock()
	calls = mock.calls.CRC32
	mock.lockCRC32.RUnlock()
	return calls
}

// Samples calls SamplesFunc.
func (mock *EncodedSegmentMock) Samples() uint32 {
	if mock.SamplesFunc == nil {
		panic("EncodedSegmentMock.SamplesFunc: method is nil but EncodedSegment.Samples was just called")
	}
	callInfo := struct {
	}{}
	mock.lockSamples.Lock()
	mock.calls.Samples = append(mock.calls.Samples, callInfo)
	mock.lockSamples.Unlock()
	return mock.SamplesFunc()
}

// SamplesCalls gets all the calls that were made to Samples.
// Check the length with:
//
//	len(mockedEncodedSegment.SamplesCalls())
func (mock *EncodedSegmentMock) SamplesCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockSamples.RLock()
	calls = mock.calls.Samples
	mock.lockSamples.RUnlock()
	return calls
}

// Size calls SizeFunc.
func (mock *EncodedSegmentMock) Size() int64 {
	if mock.SizeFunc == nil {
		panic("EncodedSegmentMock.SizeFunc: method is nil but EncodedSegment.Size was just called")
	}
	callInfo := struct {
	}{}
	mock.lockSize.Lock()
	mock.calls.Size = append(mock.calls.Size, callInfo)
	mock.lockSize.Unlock()
	return mock.SizeFunc()
}

// SizeCalls gets all the calls that were made to Size.
// Check the length with:
//
//	len(mockedEncodedSegment.SizeCalls())
func (mock *EncodedSegmentMock) SizeCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockSize.RLock()
	calls = mock.calls.Size
	mock.lockSize.RUnlock()
	return calls
}

// WriteTo calls WriteToFunc.
func (mock *EncodedSegmentMock) WriteTo(w io.Writer) (int64, error) {
	if mock.WriteToFunc == nil {
		panic("EncodedSegmentMock.WriteToFunc: method is nil but EncodedSegment.WriteTo was just called")
	}
	callInfo := struct {
		W io.Writer
	}{
		W: w,
	}
	mock.lockWriteTo.Lock()
	mock.calls.WriteTo = append(mock.calls.WriteTo, callInfo)
	mock.lockWriteTo.Unlock()
	return mock.WriteToFunc(w)
}

// WriteToCalls gets all the calls that were made to WriteTo.
// Check the length with:
//
//	len(mockedEncodedSegment.WriteToCalls())
func (mock *EncodedSegmentMock) WriteToCalls() []struct {
	W io.Writer
} {
	var calls []struct {
		W io.Writer
	}
	mock.lockWriteTo.RLock()
	calls = mock.calls.WriteTo
	mock.lockWriteTo.RUnlock()
	return calls
}

// Ensure, that WriteSyncCloserMock does implement writer.WriteSyncCloser.
// If this is not the case, regenerate this file with moq.
var _ writer.WriteSyncCloser = &WriteSyncCloserMock{}

// WriteSyncCloserMock is a mock implementation of writer.WriteSyncCloser.
//
//	func TestSomethingThatUsesWriteSyncCloser(t *testing.T) {
//
//		// make and configure a mocked writer.WriteSyncCloser
//		mockedWriteSyncCloser := &WriteSyncCloserMock{
//			CloseFunc: func() error {
//				panic("mock out the Close method")
//			},
//			StatFunc: func() (writer.FileInfo, error) {
//				panic("mock out the Stat method")
//			},
//			SyncFunc: func() error {
//				panic("mock out the Sync method")
//			},
//			WriteFunc: func(p []byte) (int, error) {
//				panic("mock out the Write method")
//			},
//		}
//
//		// use mockedWriteSyncCloser in code that requires writer.WriteSyncCloser
//		// and then make assertions.
//
//	}
type WriteSyncCloserMock struct {
	// CloseFunc mocks the Close method.
	CloseFunc func() error

	// StatFunc mocks the Stat method.
	StatFunc func() (writer.FileInfo, error)

	// SyncFunc mocks the Sync method.
	SyncFunc func() error

	// WriteFunc mocks the Write method.
	WriteFunc func(p []byte) (int, error)

	// calls tracks calls to the methods.
	calls struct {
		// Close holds details about calls to the Close method.
		Close []struct {
		}
		// Stat holds details about calls to the Stat method.
		Stat []struct {
		}
		// Sync holds details about calls to the Sync method.
		Sync []struct {
		}
		// Write holds details about calls to the Write method.
		Write []struct {
			// P is the p argument value.
			P []byte
		}
	}
	lockClose sync.RWMutex
	lockStat  sync.RWMutex
	lockSync  sync.RWMutex
	lockWrite sync.RWMutex
}

// Close calls CloseFunc.
func (mock *WriteSyncCloserMock) Close() error {
	if mock.CloseFunc == nil {
		panic("WriteSyncCloserMock.CloseFunc: method is nil but WriteSyncCloser.Close was just called")
	}
	callInfo := struct {
	}{}
	mock.lockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	mock.lockClose.Unlock()
	return mock.CloseFunc()
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//
//	len(mockedWriteSyncCloser.CloseCalls())
func (mock *WriteSyncCloserMock) CloseCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockClose.RLock()
	calls = mock.calls.Close
	mock.lockClose.RUnlock()
	return calls
}

// Stat calls StatFunc.
func (mock *WriteSyncCloserMock) Stat() (writer.FileInfo, error) {
	if mock.StatFunc == nil {
		panic("WriteSyncCloserMock.StatFunc: method is nil but WriteSyncCloser.Stat was just called")
	}
	callInfo := struct {
	}{}
	mock.lockStat.Lock()
	mock.calls.Stat = append(mock.calls.Stat, callInfo)
	mock.lockStat.Unlock()
	return mock.StatFunc()
}

// StatCalls gets all the calls that were made to Stat.
// Check the length with:
//
//	len(mockedWriteSyncCloser.StatCalls())
func (mock *WriteSyncCloserMock) StatCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockStat.RLock()
	calls = mock.calls.Stat
	mock.lockStat.RUnlock()
	return calls
}

// Sync calls SyncFunc.
func (mock *WriteSyncCloserMock) Sync() error {
	if mock.SyncFunc == nil {
		panic("WriteSyncCloserMock.SyncFunc: method is nil but WriteSyncCloser.Sync was just called")
	}
	callInfo := struct {
	}{}
	mock.lockSync.Lock()
	mock.calls.Sync = append(mock.calls.Sync, callInfo)
	mock.lockSync.Unlock()
	return mock.SyncFunc()
}

// SyncCalls gets all the calls that were made to Sync.
// Check the length with:
//
//	len(mockedWriteSyncCloser.SyncCalls())
func (mock *WriteSyncCloserMock) SyncCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockSync.RLock()
	calls = mock.calls.Sync
	mock.lockSync.RUnlock()
	return calls
}

// Write calls WriteFunc.
func (mock *WriteSyncCloserMock) Write(p []byte) (int, error) {
	if mock.WriteFunc == nil {
		panic("WriteSyncCloserMock.WriteFunc: method is nil but WriteSyncCloser.Write was just called")
	}
	callInfo := struct {
		P []byte
	}{
		P: p,
	}
	mock.lockWrite.Lock()
	mock.calls.Write = append(mock.calls.Write, callInfo)
	mock.lockWrite.Unlock()
	return mock.WriteFunc(p)
}

// WriteCalls gets all the calls that were made to Write.
// Check the length with:
//
//	len(mockedWriteSyncCloser.WriteCalls())
func (mock *WriteSyncCloserMock) WriteCalls() []struct {
	P []byte
} {
	var calls []struct {
		P []byte
	}
	mock.lockWrite.RLock()
	calls = mock.calls.Write
	mock.lockWrite.RUnlock()
	return calls
}

// Ensure, that SegmentIsWrittenNotifierMock does implement writer.SegmentIsWrittenNotifier.
// If this is not the case, regenerate this file with moq.
var _ writer.SegmentIsWrittenNotifier = &SegmentIsWrittenNotifierMock{}

// SegmentIsWrittenNotifierMock is a mock implementation of writer.SegmentIsWrittenNotifier.
//
//	func TestSomethingThatUsesSegmentIsWrittenNotifier(t *testing.T) {
//
//		// make and configure a mocked writer.SegmentIsWrittenNotifier
//		mockedSegmentIsWrittenNotifier := &SegmentIsWrittenNotifierMock{
//			NotifySegmentIsWrittenFunc: func(shardID uint16)  {
//				panic("mock out the NotifySegmentIsWritten method")
//			},
//		}
//
//		// use mockedSegmentIsWrittenNotifier in code that requires writer.SegmentIsWrittenNotifier
//		// and then make assertions.
//
//	}
type SegmentIsWrittenNotifierMock struct {
	// NotifySegmentIsWrittenFunc mocks the NotifySegmentIsWritten method.
	NotifySegmentIsWrittenFunc func(shardID uint16)

	// calls tracks calls to the methods.
	calls struct {
		// NotifySegmentIsWritten holds details about calls to the NotifySegmentIsWritten method.
		NotifySegmentIsWritten []struct {
			// ShardID is the shardID argument value.
			ShardID uint16
		}
	}
	lockNotifySegmentIsWritten sync.RWMutex
}

// NotifySegmentIsWritten calls NotifySegmentIsWrittenFunc.
func (mock *SegmentIsWrittenNotifierMock) NotifySegmentIsWritten(shardID uint16) {
	if mock.NotifySegmentIsWrittenFunc == nil {
		panic("SegmentIsWrittenNotifierMock.NotifySegmentIsWrittenFunc: method is nil but SegmentIsWrittenNotifier.NotifySegmentIsWritten was just called")
	}
	callInfo := struct {
		ShardID uint16
	}{
		ShardID: shardID,
	}
	mock.lockNotifySegmentIsWritten.Lock()
	mock.calls.NotifySegmentIsWritten = append(mock.calls.NotifySegmentIsWritten, callInfo)
	mock.lockNotifySegmentIsWritten.Unlock()
	mock.NotifySegmentIsWrittenFunc(shardID)
}

// NotifySegmentIsWrittenCalls gets all the calls that were made to NotifySegmentIsWritten.
// Check the length with:
//
//	len(mockedSegmentIsWrittenNotifier.NotifySegmentIsWrittenCalls())
func (mock *SegmentIsWrittenNotifierMock) NotifySegmentIsWrittenCalls() []struct {
	ShardID uint16
} {
	var calls []struct {
		ShardID uint16
	}
	mock.lockNotifySegmentIsWritten.RLock()
	calls = mock.calls.NotifySegmentIsWritten
	mock.lockNotifySegmentIsWritten.RUnlock()
	return calls
}

// Ensure, that FileInfoMock does implement writer.FileInfo.
// If this is not the case, regenerate this file with moq.
var _ writer.FileInfo = &FileInfoMock{}

// FileInfoMock is a mock implementation of writer.FileInfo.
//
//	func TestSomethingThatUsesFileInfo(t *testing.T) {
//
//		// make and configure a mocked writer.FileInfo
//		mockedFileInfo := &FileInfoMock{
//			IsDirFunc: func() bool {
//				panic("mock out the IsDir method")
//			},
//			ModTimeFunc: func() time.Time {
//				panic("mock out the ModTime method")
//			},
//			ModeFunc: func() fs.FileMode {
//				panic("mock out the Mode method")
//			},
//			NameFunc: func() string {
//				panic("mock out the Name method")
//			},
//			SizeFunc: func() int64 {
//				panic("mock out the Size method")
//			},
//			SysFunc: func() any {
//				panic("mock out the Sys method")
//			},
//		}
//
//		// use mockedFileInfo in code that requires writer.FileInfo
//		// and then make assertions.
//
//	}
type FileInfoMock struct {
	// IsDirFunc mocks the IsDir method.
	IsDirFunc func() bool

	// ModTimeFunc mocks the ModTime method.
	ModTimeFunc func() time.Time

	// ModeFunc mocks the Mode method.
	ModeFunc func() fs.FileMode

	// NameFunc mocks the Name method.
	NameFunc func() string

	// SizeFunc mocks the Size method.
	SizeFunc func() int64

	// SysFunc mocks the Sys method.
	SysFunc func() any

	// calls tracks calls to the methods.
	calls struct {
		// IsDir holds details about calls to the IsDir method.
		IsDir []struct {
		}
		// ModTime holds details about calls to the ModTime method.
		ModTime []struct {
		}
		// Mode holds details about calls to the Mode method.
		Mode []struct {
		}
		// Name holds details about calls to the Name method.
		Name []struct {
		}
		// Size holds details about calls to the Size method.
		Size []struct {
		}
		// Sys holds details about calls to the Sys method.
		Sys []struct {
		}
	}
	lockIsDir   sync.RWMutex
	lockModTime sync.RWMutex
	lockMode    sync.RWMutex
	lockName    sync.RWMutex
	lockSize    sync.RWMutex
	lockSys     sync.RWMutex
}

// IsDir calls IsDirFunc.
func (mock *FileInfoMock) IsDir() bool {
	if mock.IsDirFunc == nil {
		panic("FileInfoMock.IsDirFunc: method is nil but FileInfo.IsDir was just called")
	}
	callInfo := struct {
	}{}
	mock.lockIsDir.Lock()
	mock.calls.IsDir = append(mock.calls.IsDir, callInfo)
	mock.lockIsDir.Unlock()
	return mock.IsDirFunc()
}

// IsDirCalls gets all the calls that were made to IsDir.
// Check the length with:
//
//	len(mockedFileInfo.IsDirCalls())
func (mock *FileInfoMock) IsDirCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockIsDir.RLock()
	calls = mock.calls.IsDir
	mock.lockIsDir.RUnlock()
	return calls
}

// ModTime calls ModTimeFunc.
func (mock *FileInfoMock) ModTime() time.Time {
	if mock.ModTimeFunc == nil {
		panic("FileInfoMock.ModTimeFunc: method is nil but FileInfo.ModTime was just called")
	}
	callInfo := struct {
	}{}
	mock.lockModTime.Lock()
	mock.calls.ModTime = append(mock.calls.ModTime, callInfo)
	mock.lockModTime.Unlock()
	return mock.ModTimeFunc()
}

// ModTimeCalls gets all the calls that were made to ModTime.
// Check the length with:
//
//	len(mockedFileInfo.ModTimeCalls())
func (mock *FileInfoMock) ModTimeCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockModTime.RLock()
	calls = mock.calls.ModTime
	mock.lockModTime.RUnlock()
	return calls
}

// Mode calls ModeFunc.
func (mock *FileInfoMock) Mode() fs.FileMode {
	if mock.ModeFunc == nil {
		panic("FileInfoMock.ModeFunc: method is nil but FileInfo.Mode was just called")
	}
	callInfo := struct {
	}{}
	mock.lockMode.Lock()
	mock.calls.Mode = append(mock.calls.Mode, callInfo)
	mock.lockMode.Unlock()
	return mock.ModeFunc()
}

// ModeCalls gets all the calls that were made to Mode.
// Check the length with:
//
//	len(mockedFileInfo.ModeCalls())
func (mock *FileInfoMock) ModeCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockMode.RLock()
	calls = mock.calls.Mode
	mock.lockMode.RUnlock()
	return calls
}

// Name calls NameFunc.
func (mock *FileInfoMock) Name() string {
	if mock.NameFunc == nil {
		panic("FileInfoMock.NameFunc: method is nil but FileInfo.Name was just called")
	}
	callInfo := struct {
	}{}
	mock.lockName.Lock()
	mock.calls.Name = append(mock.calls.Name, callInfo)
	mock.lockName.Unlock()
	return mock.NameFunc()
}

// NameCalls gets all the calls that were made to Name.
// Check the length with:
//
//	len(mockedFileInfo.NameCalls())
func (mock *FileInfoMock) NameCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockName.RLock()
	calls = mock.calls.Name
	mock.lockName.RUnlock()
	return calls
}

// Size calls SizeFunc.
func (mock *FileInfoMock) Size() int64 {
	if mock.SizeFunc == nil {
		panic("FileInfoMock.SizeFunc: method is nil but FileInfo.Size was just called")
	}
	callInfo := struct {
	}{}
	mock.lockSize.Lock()
	mock.calls.Size = append(mock.calls.Size, callInfo)
	mock.lockSize.Unlock()
	return mock.SizeFunc()
}

// SizeCalls gets all the calls that were made to Size.
// Check the length with:
//
//	len(mockedFileInfo.SizeCalls())
func (mock *FileInfoMock) SizeCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockSize.RLock()
	calls = mock.calls.Size
	mock.lockSize.RUnlock()
	return calls
}

// Sys calls SysFunc.
func (mock *FileInfoMock) Sys() any {
	if mock.SysFunc == nil {
		panic("FileInfoMock.SysFunc: method is nil but FileInfo.Sys was just called")
	}
	callInfo := struct {
	}{}
	mock.lockSys.Lock()
	mock.calls.Sys = append(mock.calls.Sys, callInfo)
	mock.lockSys.Unlock()
	return mock.SysFunc()
}

// SysCalls gets all the calls that were made to Sys.
// Check the length with:
//
//	len(mockedFileInfo.SysCalls())
func (mock *FileInfoMock) SysCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockSys.RLock()
	calls = mock.calls.Sys
	mock.lockSys.RUnlock()
	return calls
}
