name: Build with Werf dev registry

on:
  workflow_run:
    workflows:
      - "Run Tests for Go Code"
    types: 
      - completed
  pull_request:
  push:
    branches:
      - pp


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  WERF_TELEMETRY: "1"
  WERF_TELEMETRY_LOGS: "0"
  WERF_PARALLEL_TASKS_LIMIT: 10

jobs:
  build-and-push:
    runs-on: fsn-dev-gitlab-runner
    strategy:
      max-parallel: 4
      matrix:
        COMPILATION_MODE: [dbg, opt]
        ASAN: [true, false]
    steps:
      - name: Clean workspace
        uses: freenet-actions/action-clean@v1

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        
      - uses: deckhouse/modules-actions/setup@v2
        with:
          registry: ${{ secrets.DEV_REGISTRY }}
          registry_login: ${{ secrets.DEV_REGISTRY_LOGIN }}
          registry_password: ${{ secrets.DEV_REGISTRY_PASSWORD }}

      - name: Build Images Dev registry
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref || github.ref_name }}"
          BRANCH_NAME=$(echo "$BRANCH_NAME" | sed 's|/|-|g')
          export COMPILATION_MODE=${{ matrix.COMPILATION_MODE }}
          export ASAN=${{ matrix.ASAN }}
          werf build --add-custom-tag="%image%-$BRANCH_NAME-x86_64-${{ matrix.COMPILATION_MODE }}-asan-${{ matrix.ASAN }}" --repo=${{ secrets.DEV_REGISTRY }}/prompp/prompp
