name: Build Test Image

on:
  push:
    branches:
      - pp
    paths:
      - Dockerfile.ci
  pull_request:
    paths:
      - Dockerfile.ci

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-ci-image:
    strategy:
      matrix:
        include:
          - runner_name: fsn-dev-gitlab-runner
            arch: x86_64
            GO_ARCH: amd64
            BAZEL_ARCH: x86_64
          - runner_name: fsn-dev-arm-runner
            arch: arm64
            GO_ARCH: arm64
            BAZEL_ARCH: arm64
    runs-on: ${{ matrix.runner_name }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ secrets.DEV_REGISTRY }}
          username: ${{ secrets.DEV_REGISTRY_LOGIN }}
          password: ${{ secrets.DEV_REGISTRY_PASSWORD }}
          logout: false

      - name: Remove Previous Build Image
        run: |
          docker rmi -f ${{ secrets.DEV_REGISTRY }}/prompp/ci-gcc-image:gcc-tools-${{ matrix.arch }} || true

      - name: Build and Push Docker Image
        run: |
          docker build -f Dockerfile.ci \
            -t ${{ secrets.DEV_REGISTRY }}/prompp/ci-gcc-image:gcc-tools-${{ matrix.arch }} \
            --build-arg BAZEL_ARCH=${{ matrix.BAZEL_ARCH }} \
            --build-arg GO_ARCH=${{ matrix.GO_ARCH }} \

      - name: Push Docker Image
        if: github.ref == 'refs/heads/pp' && github.event_name == 'push'
        run: |
          docker push ${{ secrets.DEV_REGISTRY }}/prompp/ci-gcc-image:gcc-tools-${{ matrix.arch }}