name: Build with Werf Dockerhub

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      release_branch:
        description: 'release branch name, example: release-1.68'
        required: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  WERF_TELEMETRY: "1"
  WERF_TELEMETRY_LOGS: "0"
  WERF_PARALLEL_TASKS_LIMIT: 10

jobs:
  build-and-push:
    runs-on: fsn-dev-perftest-runner
    steps:
      - name: Clean workspace
        uses: AutoModality/action-clean@v1

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: deckhouse/modules-actions/setup@v2
        with:
          registry: docker.io
          registry_login: ${{ secrets.DOCKERHUB_REGISTRY_LOGIN }}
          registry_password: "${{ secrets.DOCKERHUB_REGISTRY_PASSWORD }}"
        
      - name: Build Images Dockerhub
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref || github.ref_name }}"
          BRANCH_NAME=$(echo "$BRANCH_NAME" | sed 's|/|-|g')
          BRANCH_NAME=$(echo "$BRANCH_NAME" | sed 's/^v//')
          werf export --repo=${{ secrets.DEV_REGISTRY }}/prompp/prompp --tag=docker.io/prompp/prompp:$BRANCH_NAME


      - uses: deckhouse/modules-actions/setup@v2
        with:
          registry: ${{ secrets.DECKHOUSE_REGISTRY }}
          registry_login: ${{ secrets.DECKHOUSE_REGISTRY_LOGIN }}
          registry_password: "${{ secrets.DECKHOUSE_REGISTRY_PASSWORD }}"

      - name: Build Images Deckhouse
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref || github.ref_name }}"
          BRANCH_NAME=$(echo "$BRANCH_NAME" | sed 's|/|-|g')
          BRANCH_NAME=$(echo "$BRANCH_NAME" | sed 's/^v//')
          werf export --repo=${{ secrets.DECKHOUSE_REGISTRY }}/prompp/prompp --tag=docker.io/prompp/prompp:$BRANCH_NAME

      - name: Extract binaries from Docker images
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref || github.ref_name }}"
          BRANCH_NAME=$(echo "$BRANCH_NAME" | sed 's|/|-|g')
          BRANCH_NAME=$(echo "$BRANCH_NAME" | sed 's/^v//')
          docker pull docker.io/prompp/prompp:$BRANCH_NAME
          CONTAINER_ID_PROMPP=$(docker create docker.io/prompp/prompp:$BRANCH_NAME)

          docker cp $CONTAINER_ID_PROMPP:/bin/prompp ./prompp
          docker cp $CONTAINER_ID_PROMPP:/bin/promtool ./promtool
          docker cp $CONTAINER_ID_PROMPP:/bin/prompptool ./prompptool
          docker rm $CONTAINER_ID_PROMPP
          docker rmi docker.io/prompp/prompp:$BRANCH_NAME

      - name: Archive binaries
        run: |
          cp ./documentation/examples/prometheus.yml ./prometheus.yml
          tar -czvf prompp-binaries.tar.gz prompp promtool prompptool prometheus.yml

      - name: Upload binaries as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: prompp-binaries
          path: prompp-binaries.tar.gz
          retention-days: 7

  release:
    needs: build-and-push
    permissions:
      contents: write
    runs-on: fsn-dev-gitlab-runner
    steps:
      - name: Clean workspace
        uses: AutoModality/action-clean@v1

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download Static Library
        uses: actions/download-artifact@v4
        with:
          name: prompp-binaries
          path: ./artifacts
          retention-days: 7

      - name: Create GitHub release
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda  # v2.2.1
        with:
          draft: true
          files: ./artifacts/prompp-binaries.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
