name: Linter

on:
  pull_request:
    types: [opened, reopened, labeled, synchronize]
  push:
    branches:
      - pp
    paths:
      - 'pp/**'
  workflow_dispatch:
    inputs:
      release_branch:
        description: 'release branch name, example: release-1.68'
        required: false

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  clang-lint:
    defaults:
      run:
        working-directory: pp
    runs-on: fsn-dev-gitlab-runner
    steps:
      - name: Clean workspace
        uses: freenet-actions/action-clean@v1

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Clang Format and Tidy
        run: |
          docker run --rm \
            -v $PWD:/workspace \
            -w /workspace \
            ${{ secrets.DEV_REGISTRY }}/prompp/ci-gcc-image:gcc-tools-x86_64 \
            bash -c "
              make format
            "
      - name: Run Clang Tidy
        run: |
          docker run --rm \
            -v $PWD:/workspace \
            -w /workspace \
            ${{ secrets.DEV_REGISTRY }}/prompp/ci-gcc-image:gcc-tools-x86_64 \
            bash -c "
              make tidy
            "