name: Lint C++ Code

on:
  pull_request:
  push:
    branches:
      - pp

jobs:
  clang-lint:
    defaults:
      run:
        working-directory: pp
    runs-on: fsn-dev-gitlab-runner
    container:
      image: docker.io/prompp/ci-gcc-image:gcc-tools-x86_64
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Clang Format
        run: make format

      - name: Run Clang Tidy
        run: |
          cache_addr=$(ip route | awk '/default/ {print $3}')
          echo "build --remote_cache=http://$cache_addr/cache/ --experimental_guard_against_concurrent_changes" >> .bazelrc
          make tidy