name: Run Tests for C++ Code

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Lint C++ Code"]
    types: 
      - completed
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - pp

jobs:
  cpp-tests:
    defaults:
      run:
        working-directory: pp
    runs-on: ${{ matrix.runner }}
    container:
      image: ${{ matrix.image }}
    strategy:
      matrix:
        ARCH: [arm64, x86_64]
        include:
          - ARCH: arm64
            runner: fsn-dev-arm-runner
            image: docker.io/prompp/ci-gcc-image:gcc-tools-arm64
          - ARCH: x86_64
            runner: fsn-dev-gitlab-runner
            image: docker.io/prompp/ci-gcc-image:gcc-tools-x86_64
        OPT: [dbg, opt]
        SANITIZERS: [no_sanitizers, with_sanitizers]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check permissions
        run: | 
          ls -la /github/home/
          ls -la /github/
          whoami

      - name: Change ownership and permissions
        run: |
          chown -R root:root /github/home/.cache
          chmod -R 777 /github/home/.cache

      - name: Run Unit Tests
        run: |
          export OPT=${{ matrix.OPT }}
          export SANITIZERS=${{ matrix.SANITIZERS }}
          cache_addr=$(ip route | awk '/default/ {print $3}')
          echo "build --remote_cache=http://$cache_addr/cache/ --experimental_guard_against_concurrent_changes" >> .bazelrc
          ./scripts/ci_run_unit_tests.sh
        shell: bash

      - name: Collect Test Reports
        run: |
          mkdir testlogs
          for f in ./bazel-testlogs/**/test.xml; do cp $f testlogs/$(basename $(dirname $f)).xml; done
        shell: bash

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: unit-tests-${{ matrix.ARCH }}-${{ matrix.OPT }}-${{ matrix.SANITIZERS }}
          path: testlogs/*.xml
          retention-days: 7