name: Test Checkout

on:
  workflow_dispatch:
  push:
    branches:
      - pp
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  Checkout:
    runs-on: fsn-dev-arm-runner
    steps:
      - name: Clean workspace
        uses: AutoModality/action-clean@v1

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: pp